#include "textparser.h"
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct AttribValuePair
#define TYPE_parse_AttribValuePair AttribValuePair
ParseTable parse_AttribValuePair[] =
{
	{ "AttribValuePair", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(AttribValuePair), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "pchAttribute",		TOK_PERSIST | TOK_SUBSCRIBE | TOK_KEY | TOK_STRING(AttribValuePair, pchAttribute, 0), NULL },
	{ "pchValue",			TOK_PERSIST | TOK_SUBSCRIBE | TOK_STRING(AttribValuePair, pchValue, 0), NULL },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_AttribValuePair()
{
	int iSize = sizeof(AttribValuePair);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_AttribValuePair, iSize, "AttribValuePair", NULL, "GameAccountData.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct ParsedAVP
#define TYPE_parse_ParsedAVP ParsedAVP
ParseTable parse_ParsedAVP[] =
{
	{ "ParsedAVP", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(ParsedAVP), 0, NULL, 0, NULL },
	{ "{",			TOK_START, 0 },
	{ "Attribute",	TOK_KEY | TOK_STRING(ParsedAVP, pchAttribute, 0), NULL },
	{ "Value",		TOK_STRING(ParsedAVP, pchValue, 0), NULL },
	{ "GameTitle",	TOK_STRING(ParsedAVP, pchGameTitle, 0), NULL },
	{ "Type",		TOK_AUTOINT(ParsedAVP, eType, 0), MicroItemTypeEnum },
	{ "ItemIdent",	TOK_STRING(ParsedAVP, pchItemIdent, 0), NULL },
	{ "Count",		TOK_AUTOINT(ParsedAVP, iCount, 0), NULL },
	{ "}",			TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_ParsedAVP()
{
	int iSize = sizeof(ParsedAVP);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_ParsedAVP, iSize, "ParsedAVP", NULL, "GameAccountData.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_ParsedAVP[];
#define TYPE_parse_ParsedAVP ParsedAVP
//Structparser.exe autogenerated ParseTable for struct ParsedAVPList
#define TYPE_parse_ParsedAVPList ParsedAVPList
ParseTable parse_ParsedAVPList[] =
{
	{ "ParsedAVPList", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(ParsedAVPList), 0, NULL, 0, NULL },
	{ "{",				TOK_START, 0 },
	{ "Pairs",			TOK_STRUCT(ParsedAVPList, eaPairs, parse_ParsedAVP) },
	{ "}",				TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_ParsedAVPList()
{
	int iSize = sizeof(ParsedAVPList);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_ParsedAVPList, iSize, "ParsedAVPList", NULL, "GameAccountData.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct GamePermission
#define TYPE_parse_GamePermission GamePermission
ParseTable parse_GamePermission[] =
{
	{ "GamePermission", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(GamePermission), 0, NULL, 0, NULL },
	{ "{",				TOK_START, 0 },
	{ "pchName",		TOK_PERSIST | TOK_POOL_STRING | TOK_SUBSCRIBE | TOK_KEY | TOK_STRING(GamePermission, pchName, 0), NULL },
	{ "}",				TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_GamePermission()
{
	int iSize = sizeof(GamePermission);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_GamePermission, iSize, "GamePermission", NULL, "GameAccountData.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct GameToken
#define TYPE_parse_GameToken GameToken
ParseTable parse_GameToken[] =
{
	{ "GameToken", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(GameToken), 0, NULL, 0, NULL },
	{ "{",			TOK_START, 0 },
	{ "pchKey",		TOK_PERSIST | TOK_POOL_STRING | TOK_SUBSCRIBE | TOK_KEY | TOK_STRING(GameToken, pchKey, 0), NULL },
	{ "}",			TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_GameToken()
{
	int iSize = sizeof(GameToken);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_GameToken, iSize, "GameToken", NULL, "GameAccountData.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct FoundryTipRecord
#define TYPE_parse_FoundryTipRecord FoundryTipRecord
ParseTable parse_FoundryTipRecord[] =
{
	{ "FoundryTipRecord", 		TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(FoundryTipRecord), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "uTimeOfTip",				TOK_PERSIST | TOK_SUBSCRIBE | TOK_AUTOINT(FoundryTipRecord, uTimeOfTip, 0), NULL },
	{ "uTipAuthorAccountID",	TOK_PERSIST | TOK_SUBSCRIBE | TOK_AUTOINT(FoundryTipRecord, uTipAuthorAccountID, 0), NULL },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_FoundryTipRecord()
{
	int iSize = sizeof(FoundryTipRecord);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_FoundryTipRecord, iSize, "FoundryTipRecord", NULL, "GameAccountData.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_AttribValuePair[];
#define TYPE_parse_AttribValuePair AttribValuePair
extern ParseTable parse_AttribValuePair[];
#define TYPE_parse_AttribValuePair AttribValuePair
extern ParseTable parse_MicroTransaction[];
#define TYPE_parse_MicroTransaction MicroTransaction
extern ParseTable parse_GamePermission[];
#define TYPE_parse_GamePermission GamePermission
extern ParseTable parse_GameToken[];
#define TYPE_parse_GameToken GameToken
extern ParseTable parse_RecruiterContainer[];
#define TYPE_parse_RecruiterContainer RecruiterContainer
extern ParseTable parse_RecruitContainer[];
#define TYPE_parse_RecruitContainer RecruitContainer
extern ParseTable parse_FoundryTipRecord[];
#define TYPE_parse_FoundryTipRecord FoundryTipRecord
extern ParseTable parse_AccountProxyKeyValueInfoContainer[];
#define TYPE_parse_AccountProxyKeyValueInfoContainer AccountProxyKeyValueInfoContainer
//Structparser.exe autogenerated ParseTable for struct GameAccountData
#define TYPE_parse_GameAccountData GameAccountData
ParseTable parse_GameAccountData[] =
{
	{ "GameAccountData", 								TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(GameAccountData), 0, NULL, 0, NULL },
	{ "{",												TOK_START, 0 },
	{ "iAccountID",										TOK_PERSIST | TOK_SUBSCRIBE | TOK_KEY | TOK_AUTOINT(GameAccountData, iAccountID, 0), NULL },
	{ "eaKeys",											TOK_PERSIST | TOK_SUBSCRIBE | TOK_STRUCT(GameAccountData, eaKeys, parse_AttribValuePair) },
	{ "eaVanityPets",									TOK_PERSIST | TOK_SUBSCRIBE | TOK_STRINGARRAY(GameAccountData, eaVanityPets), NULL },
	{ "eaCostumeKeys",									TOK_PERSIST | TOK_SUBSCRIBE | TOK_STRUCT(GameAccountData, eaCostumeKeys, parse_AttribValuePair) },
	{ "eaAllPurchases",									TOK_PERSIST | TOK_SUBSCRIBE | TOK_STRUCT(GameAccountData, eaAllPurchases, parse_MicroTransaction) },
	{ "eaPermissions",									TOK_PERSIST | TOK_SUBSCRIBE | TOK_STRUCT(GameAccountData, eaPermissions, parse_GamePermission) },
	{ "eaTokens",										TOK_PERSIST | TOK_SUBSCRIBE | TOK_STRUCT(GameAccountData, eaTokens, parse_GameToken) },
	{ "pchVoiceUsername",								TOK_PERSIST | TOK_SUBSCRIBE | TOK_STRING(GameAccountData, pchVoiceUsername, 0), NULL },
	{ "pchVoicePassword",								TOK_PERSIST | TOK_SELF_ONLY | TOK_SUBSCRIBE | TOK_STRING(GameAccountData, pchVoicePassword, 0), NULL },
	{ "iVoiceAccountID",								TOK_PERSIST | TOK_SUBSCRIBE | TOK_AUTOINT(GameAccountData, iVoiceAccountID, 0), NULL },
	{ "iVersion",										TOK_PERSIST | TOK_SUBSCRIBE | TOK_AUTOINT(GameAccountData, iVersion, 0), NULL },
	{ "iDaysSubscribed",								TOK_PERSIST | TOK_SUBSCRIBE | TOK_AUTOINT(GameAccountData, iDaysSubscribed, 0), NULL },
	{ "fLongPlayTime",									TOK_PERSIST | TOK_SUBSCRIBE | TOK_F32(GameAccountData, fLongPlayTime, 0), NULL },
	{ "uFirstPlayedTime",								TOK_PERSIST | TOK_SUBSCRIBE | TOK_AUTOINT(GameAccountData, uFirstPlayedTime, 0), NULL },
	{ "uTotalPlayedTime",								TOK_PERSIST | TOK_SUBSCRIBE | TOK_AUTOINT(GameAccountData, uTotalPlayedTime_AccountServer, 0), NULL },
	{ "uTotalPlayedTime_AccountServer",					TOK_REDUNDANTNAME | TOK_PERSIST | TOK_SUBSCRIBE | TOK_AUTOINT(GameAccountData, uTotalPlayedTime_AccountServer, 0), NULL },
	{ "uLastRefreshTime",								TOK_PERSIST | TOK_SUBSCRIBE | TOK_AUTOINT(GameAccountData, uLastRefreshTime, 0), NULL },
	{ "bLifetimeSubscription",							TOK_PERSIST | TOK_SUBSCRIBE | TOK_BIT, 0, 8, NULL},
	{ "bPress",											TOK_PERSIST | TOK_SUBSCRIBE | TOK_BIT, 0, 8, NULL},
	{ "bLinkedAccount",									TOK_PERSIST | TOK_SUBSCRIBE | TOK_BIT, 0, 8, NULL},
	{ "bShadowAccount",									TOK_PERSIST | TOK_SUBSCRIBE | TOK_BIT, 0, 8, NULL},
	{ "bBilled",										TOK_PERSIST | TOK_SUBSCRIBE | TOK_BIT, 0, 8, NULL},
	{ "chatConfig",										TOK_PERSIST | TOK_AUTOINT(GameAccountData, chatConfig, 0), ChatConfigEnum },
	{ "iLastChatAccessLevel",							TOK_PERSIST | TOK_SUBSCRIBE | TOK_AUTOINT(GameAccountData, iLastChatAccessLevel, 0), NULL },
	{ "eaRecruiters",									TOK_PERSIST | TOK_SUBSCRIBE | TOK_STRUCT(GameAccountData, eaRecruiters, parse_RecruiterContainer) },
	{ "eaRecruits",										TOK_PERSIST | TOK_SUBSCRIBE | TOK_STRUCT(GameAccountData, eaRecruits, parse_RecruitContainer) },
	{ "bUGCAccountCreated",								TOK_PERSIST | TOK_SUBSCRIBE | TOK_AUTOINT(GameAccountData, bUGCAccountCreated, 0), NULL },
	{ "iFoundryTipBalance",								TOK_PERSIST | TOK_SUBSCRIBE | TOK_AUTOINT(GameAccountData, iFoundryTipBalance, 0), NULL },
	{ "eaTipRecords",									TOK_PERSIST | TOK_SUBSCRIBE | TOK_STRUCT(GameAccountData, eaTipRecords, parse_FoundryTipRecord) },
	{ "eaAccountKeyValues",								TOK_PERSIST | TOK_SUBSCRIBE | TOK_STRUCT(GameAccountData, eaAccountKeyValues, parse_AccountProxyKeyValueInfoContainer) },
	{ "uMaxCharacterLevelCached",						TOK_PERSIST | TOK_SUBSCRIBE | TOK_AUTOINT(GameAccountData, uMaxCharacterLevelCached, 0), NULL },
	{ "cachedGamePermissionsFromAccountPermissions",	TOK_PERSIST | TOK_POOL_STRING | TOK_SUBSCRIBE | TOK_STRINGARRAY(GameAccountData, cachedGamePermissionsFromAccountPermissions), NULL },
	{ "uGameSpecficGameAccountDataVersion",				TOK_PERSIST | TOK_SUBSCRIBE | TOK_AUTOINT(GameAccountData, uGameSpecficGameAccountDataVersion, 0), NULL },
	{ "bLevelUnrestricted",								TOK_IGNORE, 0 },
	{ "bTradePermitted",								TOK_IGNORE, 0 },
	{ "bSocialPermitted",								TOK_IGNORE, 0 },
	{ "bAllBasicZones",									TOK_IGNORE, 0 },
	{ "}",												TOK_END, 0 },
	{ "", 0, 0 }
};
void FindAutoStructBitField(char *pStruct, int iAllocedSizeInWords, ParseTable *pTPIColumn);
int autoStruct_fixup_GameAccountData()
{
	int iSize = sizeof(GameAccountData);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_GameAccountData, iSize, "GameAccountData", NULL, "GameAccountData.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	{
		int iSizeInWords = (sizeof(NOCONST(GameAccountData)) + 7) / 4;
		NOCONST(GameAccountData) *pTemp = alloca(iSizeInWords * 4);
		memset(pTemp, 0, iSizeInWords * 4);
		pTemp->bLifetimeSubscription = ~0;
		FindAutoStructBitField((char*)pTemp, iSizeInWords, &parse_GameAccountData[19]);
		pTemp->bLifetimeSubscription = 0;
		pTemp->bPress = ~0;
		FindAutoStructBitField((char*)pTemp, iSizeInWords, &parse_GameAccountData[20]);
		pTemp->bPress = 0;
		pTemp->bLinkedAccount = ~0;
		FindAutoStructBitField((char*)pTemp, iSizeInWords, &parse_GameAccountData[21]);
		pTemp->bLinkedAccount = 0;
		pTemp->bShadowAccount = ~0;
		FindAutoStructBitField((char*)pTemp, iSizeInWords, &parse_GameAccountData[22]);
		pTemp->bShadowAccount = 0;
		pTemp->bBilled = ~0;
		FindAutoStructBitField((char*)pTemp, iSizeInWords, &parse_GameAccountData[23]);
		pTemp->bBilled = 0;
	}
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_AttribValuePair[];
#define TYPE_parse_AttribValuePair AttribValuePair
extern ParseTable parse_AttribValuePair[];
#define TYPE_parse_AttribValuePair AttribValuePair
extern ParseTable parse_GameToken[];
#define TYPE_parse_GameToken GameToken
extern ParseTable parse_AccountProxyKeyValueInfoContainer[];
#define TYPE_parse_AccountProxyKeyValueInfoContainer AccountProxyKeyValueInfoContainer
//Structparser.exe autogenerated ParseTable for struct GameAccountDataExtract
#define TYPE_parse_GameAccountDataExtract GameAccountDataExtract
ParseTable parse_GameAccountDataExtract[] =
{
	{ "GameAccountDataExtract", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(GameAccountDataExtract), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "Keys",					TOK_STRUCT(GameAccountDataExtract, eaKeys, parse_AttribValuePair) },
	{ "CostumeKeys",			TOK_STRUCT(GameAccountDataExtract, eaCostumeKeys, parse_AttribValuePair) },
	{ "Tokens",					TOK_STRUCT(GameAccountDataExtract, eaTokens, parse_GameToken) },
	{ "AccountKeyValues",		TOK_STRUCT(GameAccountDataExtract, eaAccountKeyValues, parse_AccountProxyKeyValueInfoContainer) },
	{ "DaysSubscribed",			TOK_AUTOINT(GameAccountDataExtract, iDaysSubscribed, 0), NULL },
	{ "LevelUnrestricted",		TOK_BIT, 0, 8, NULL},
	{ "LinkedAccount",			TOK_BIT, 0, 8, NULL},
	{ "ShadowAccount",			TOK_BIT, 0, 8, NULL},
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
void FindAutoStructBitField(char *pStruct, int iAllocedSizeInWords, ParseTable *pTPIColumn);
int autoStruct_fixup_GameAccountDataExtract()
{
	int iSize = sizeof(GameAccountDataExtract);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_GameAccountDataExtract, iSize, "GameAccountDataExtract", NULL, "GameAccountData.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	{
		int iSizeInWords = (sizeof(GameAccountDataExtract) + 7) / 4;
		GameAccountDataExtract *pTemp = alloca(iSizeInWords * 4);
		memset(pTemp, 0, iSizeInWords * 4);
		pTemp->bLevelUnrestricted = ~0;
		FindAutoStructBitField((char*)pTemp, iSizeInWords, &parse_GameAccountDataExtract[7]);
		pTemp->bLevelUnrestricted = 0;
		pTemp->bLinkedAccount = ~0;
		FindAutoStructBitField((char*)pTemp, iSizeInWords, &parse_GameAccountDataExtract[8]);
		pTemp->bLinkedAccount = 0;
		pTemp->bShadowAccount = ~0;
		FindAutoStructBitField((char*)pTemp, iSizeInWords, &parse_GameAccountDataExtract[9]);
		pTemp->bShadowAccount = 0;
	}
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct SpeciesUnlock
#define TYPE_parse_SpeciesUnlock SpeciesUnlock
ParseTable parse_SpeciesUnlock[] =
{
	{ "SpeciesUnlock", 		TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(SpeciesUnlock), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "SpeciesName",		TOK_POOL_STRING | TOK_KEY | TOK_STRING(SpeciesUnlock, pchSpeciesName, 0), NULL },
	{ "SpeciesUnlockCode",	TOK_STRING(SpeciesUnlock, pchSpeciesUnlockCode, 0), NULL },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_SpeciesUnlock()
{
	int iSize = sizeof(SpeciesUnlock);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_SpeciesUnlock, iSize, "SpeciesUnlock", NULL, "GameAccountData.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_SpeciesUnlock[];
#define TYPE_parse_SpeciesUnlock SpeciesUnlock
//Structparser.exe autogenerated ParseTable for struct SpeciesUnlockList
#define TYPE_parse_SpeciesUnlockList SpeciesUnlockList
ParseTable parse_SpeciesUnlockList[] =
{
	{ "SpeciesUnlockList", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(SpeciesUnlockList), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "SpeciesUnlocks",		TOK_STRUCT(SpeciesUnlockList, eaSpeciesUnlocks, parse_SpeciesUnlock) },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_SpeciesUnlockList()
{
	int iSize = sizeof(SpeciesUnlockList);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_SpeciesUnlockList, iSize, "SpeciesUnlockList", NULL, "GameAccountData.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
