#ifndef __GSLNNOUGCGENESISMISSIONS_H_AST_H_
#define __GSLNNOUGCGENESISMISSIONS_H_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \gslNNOUGCGenesisMissions.h
//autogeneratednocheckin

extern ParseTable parse_UGCGenesisMissionAdditionalParams[];
#define TYPE_parse_UGCGenesisMissionAdditionalParams UGCGenesisMissionAdditionalParams

#endif
