#include "textparser.h"
//autogeneratednocheckin
extern ParseTable parse_DisplayMessage[];
#define TYPE_parse_DisplayMessage DisplayMessage
//Structparser.exe autogenerated ParseTable for struct UGCGenesisMissionExtraMessages
#define TYPE_parse_UGCGenesisMissionExtraMessages UGCGenesisMissionExtraMessages
ParseTable parse_UGCGenesisMissionExtraMessages[] =
{
	{ "UGCGenesisMissionExtraMessages", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCGenesisMissionExtraMessages), 0, NULL, 0, NULL },
	{ "{",								TOK_START, 0 },
	{ "filename",						TOK_POOL_STRING | TOK_CURRENTFILE(UGCGenesisMissionExtraMessages, filename), NULL},
	{ "ExtraMessage",					TOK_STRUCT(UGCGenesisMissionExtraMessages, messages, parse_DisplayMessage) },
	{ "}",								TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCGenesisMissionExtraMessages()
{
	int iSize = sizeof(UGCGenesisMissionExtraMessages);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCGenesisMissionExtraMessages, iSize, "UGCGenesisMissionExtraMessages", NULL, "gslNNOUGCGenesisMissions.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
