#ifndef __GSLNNOUGCGENESISMISSIONS_C_AST_H_
#define __GSLNNOUGCGENESISMISSIONS_C_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \gslNNOUGCGenesisMissions.c
//autogeneratednocheckin

extern ParseTable parse_UGCGenesisMissionExtraMessages[];
#define TYPE_parse_UGCGenesisMissionExtraMessages UGCGenesisMissionExtraMessages

#endif
