#include "textparser.h"
//autogeneratednocheckin
extern ParseTable parse_InteractableOverride[];
#define TYPE_parse_InteractableOverride InteractableOverride
extern ParseTable parse_MissionOfferOverride[];
#define TYPE_parse_MissionOfferOverride MissionOfferOverride
extern ParseTable parse_ImageMenuItemOverride[];
#define TYPE_parse_ImageMenuItemOverride ImageMenuItemOverride
extern ParseTable parse_WorldGameActionProperties[];
#define TYPE_parse_WorldGameActionProperties WorldGameActionProperties
//Structparser.exe autogenerated ParseTable for struct UGCGenesisMissionAdditionalParams
#define TYPE_parse_UGCGenesisMissionAdditionalParams UGCGenesisMissionAdditionalParams
ParseTable parse_UGCGenesisMissionAdditionalParams[] =
{
	{ "UGCGenesisMissionAdditionalParams", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCGenesisMissionAdditionalParams), 0, NULL, 0, NULL },
	{ "{",									TOK_START, 0 },
	{ "InteractableOverrides",				TOK_STRUCT(UGCGenesisMissionAdditionalParams, eaInteractableOverrides, parse_InteractableOverride) },
	{ "MissionOfferOverrides",				TOK_STRUCT(UGCGenesisMissionAdditionalParams, eaMissionOfferOverrides, parse_MissionOfferOverride) },
	{ "ImageMenuItemOverrides",				TOK_STRUCT(UGCGenesisMissionAdditionalParams, eaImageMenuItemOverrides, parse_ImageMenuItemOverride) },
	{ "SuccessActions",						TOK_STRUCT(UGCGenesisMissionAdditionalParams, eaSuccessActions, parse_WorldGameActionProperties) },
	{ "}",									TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCGenesisMissionAdditionalParams()
{
	int iSize = sizeof(UGCGenesisMissionAdditionalParams);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCGenesisMissionAdditionalParams, iSize, "UGCGenesisMissionAdditionalParams", NULL, "gslNNOUGCGenesisMissions.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
