#include "textparser.h"

//auto-generated staticdefine for enum SkillType
//autogeneratednocheckin
StaticDefineInt SkillTypeEnum[] =
{
	DEFINE_INT
	{ "None", kSkillType_None},
	{ "Arms", kSkillType_Arms},
	{ "Mysticism", kSkillType_Mysticism},
	{ "Science", kSkillType_Science},
	DEFINE_END
};
void autoEnum_fixup_SkillType(void)
{
	static bool bOnce = false; if (bOnce) return; bOnce = true;
	RegisterNamedStaticDefine(SkillTypeEnum, "SkillType");
}

//auto-generated staticdefine for enum ItemQuality
//autogeneratednocheckin
extern DefineContext *g_pDefineItemQualities;
StaticDefineInt ItemQualityEnum[] =
{
	DEFINE_INT
	{ "None", kItemQuality_None},
	DEFINE_EMBEDDYNAMIC_INT(g_pDefineItemQualities)
	DEFINE_END
};
void autoEnum_fixup_ItemQuality(void)
{
	static bool bOnce = false; if (bOnce) return; bOnce = true;
	RegisterNamedStaticDefine(ItemQualityEnum, "ItemQuality");
}

//auto-generated staticdefine for enum InvBagIDs
//autogeneratednocheckin
extern DefineContext *g_InvExtraBagIDs;
StaticDefineInt InvBagIDsEnum[] =
{
	DEFINE_INT
	{ "None", InvBagIDs_None},
	{ "Numeric", InvBagIDs_Numeric},
	{ "Inventory", InvBagIDs_Inventory},
	{ "Recipe", InvBagIDs_Recipe},
	{ "Callout", InvBagIDs_Callout},
	{ "Lore", InvBagIDs_Lore},
	{ "Tokens", InvBagIDs_Tokens},
	{ "Emotes", InvBagIDs_Tokens},
	{ "Titles", InvBagIDs_Titles},
	{ "ItemSet", InvBagIDs_ItemSet},
	{ "PlayerBags", InvBagIDs_PlayerBags},
	{ "PlayerBag1", InvBagIDs_PlayerBag1},
	{ "PlayerBag2", InvBagIDs_PlayerBag2},
	{ "PlayerBag3", InvBagIDs_PlayerBag3},
	{ "PlayerBag4", InvBagIDs_PlayerBag4},
	{ "PlayerBag5", InvBagIDs_PlayerBag5},
	{ "PlayerBag6", InvBagIDs_PlayerBag6},
	{ "PlayerBag7", InvBagIDs_PlayerBag7},
	{ "PlayerBag8", InvBagIDs_PlayerBag8},
	{ "PlayerBag9", InvBagIDs_PlayerBag9},
	{ "Bank", InvBagIDs_Bank},
	{ "Bank1", InvBagIDs_Bank1},
	{ "Bank2", InvBagIDs_Bank2},
	{ "Bank3", InvBagIDs_Bank3},
	{ "Bank4", InvBagIDs_Bank4},
	{ "Bank5", InvBagIDs_Bank5},
	{ "Bank6", InvBagIDs_Bank6},
	{ "Bank7", InvBagIDs_Bank7},
	{ "Bank8", InvBagIDs_Bank8},
	{ "Bank9", InvBagIDs_Bank9},
	{ "HiddenLocationData", InvBagIDs_HiddenLocationData},
	{ "LocationData", InvBagIDs_LocationData},
	{ "Buyback", InvBagIDs_Buyback},
	{ "Hidden", InvBagIDs_Hidden},
	{ "Overflow", InvBagIDs_Overflow},
	{ "Injuries", InvBagIDs_Injuries},
	{ "SuperCritterPets", InvBagIDs_SuperCritterPets},
	{ "PetEquipBag", InvBagIDs_PetEquipBag},
	{ "Loot", InvBagIDs_Loot},
	DEFINE_EMBEDDYNAMIC_INT(g_InvExtraBagIDs)
	DEFINE_END
};
void autoEnum_fixup_InvBagIDs(void)
{
	static bool bOnce = false; if (bOnce) return; bOnce = true;
	RegisterNamedStaticDefine(InvBagIDsEnum, "InvBagIDs");
}

//auto-generated staticdefine for enum ItemTag
//autogeneratednocheckin
extern DefineContext *s_pDefineItemTags;
StaticDefineInt ItemTagEnum[] =
{
	DEFINE_INT
	{ "None", ItemTag_None},
	DEFINE_EMBEDDYNAMIC_INT(s_pDefineItemTags)
	DEFINE_END
};
void autoEnum_fixup_ItemTag(void)
{
	static bool bOnce = false; if (bOnce) return; bOnce = true;
	RegisterNamedStaticDefine(ItemTagEnum, "ItemTag");
}

//auto-generated staticdefine for enum ItemCategory
//autogeneratednocheckin
extern DefineContext *s_pDefineItemCategories;
StaticDefineInt ItemCategoryEnum[] =
{
	DEFINE_INT
	{ "None", kItemCategory_None},
	{ "DDWeapon", kItemCategory_DDWeapon},
	{ "DDImplement", kItemCategory_DDImplement},
	{ "DDShield", kItemCategory_DDShield},
	DEFINE_EMBEDDYNAMIC_INT(s_pDefineItemCategories)
	DEFINE_END
};
void autoEnum_fixup_ItemCategory(void)
{
	static bool bOnce = false; if (bOnce) return; bOnce = true;
	RegisterNamedStaticDefine(ItemCategoryEnum, "ItemCategory");
}

//auto-generated staticdefine for enum NumericOp
//autogeneratednocheckin
StaticDefineInt NumericOpEnum[] =
{
	DEFINE_INT
	{ "Add", NumericOp_Add},
	{ "RaiseTo", NumericOp_RaiseTo},
	{ "LowerTo", NumericOp_LowerTo},
	{ "SetTo", NumericOp_SetTo},
	DEFINE_END
};
void autoEnum_fixup_NumericOp(void)
{
	static bool bOnce = false; if (bOnce) return; bOnce = true;
	RegisterNamedStaticDefine(NumericOpEnum, "NumericOp");
}
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct ItemTagData
#define TYPE_parse_ItemTagData ItemTagData
ParseTable parse_ItemTagData[] =
{
	{ "ItemTagData", 			TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(ItemTagData), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "ItemTag",				TOK_KEY | TOK_AUTOINT(ItemTagData, eItemTag, 0), ItemTagEnum },
	{ "esItemTagName",			TOK_ESTRING | TOK_STRING(ItemTagData, esItemTagName, 0), NULL },
	{ "SkillType",				TOK_AUTOINT(ItemTagData, eSkillType, 0), SkillTypeEnum },
	{ "SpecializationRequired",	TOK_AUTOINT(ItemTagData, bSpecializationRequired, 0), NULL },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_ItemTagData()
{
	int iSize = sizeof(ItemTagData);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_ItemTagData, iSize, "ItemTagData", NULL, "itemEnums.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_ItemTagData[];
#define TYPE_parse_ItemTagData ItemTagData
//Structparser.exe autogenerated ParseTable for struct ItemTagInfo
#define TYPE_parse_ItemTagInfo ItemTagInfo
ParseTable parse_ItemTagInfo[] =
{
	{ "ItemTagInfo", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(ItemTagInfo), 0, NULL, 0, NULL },
	{ "{",				TOK_START, 0 },
	{ "ItemTagData",	TOK_STRUCT(ItemTagInfo, eItemTagData, parse_ItemTagData) },
	{ "}",				TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_ItemTagInfo()
{
	int iSize = sizeof(ItemTagInfo);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_ItemTagInfo, iSize, "ItemTagInfo", NULL, "itemEnums.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
