#include "textparser.h"
//autogeneratednocheckin
extern ParseTable parse_DisplayMessage[];
#define TYPE_parse_DisplayMessage DisplayMessage
extern ParseTable parse_DisplayMessage[];
#define TYPE_parse_DisplayMessage DisplayMessage
extern ParseTable parse_DisplayMessage[];
#define TYPE_parse_DisplayMessage DisplayMessage
//Structparser.exe autogenerated ParseTable for struct CharacterBackgroundChoice
#define TYPE_parse_CharacterBackgroundChoice CharacterBackgroundChoice
ParseTable parse_CharacterBackgroundChoice[] =
{
	{ "CharacterBackgroundChoice", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(CharacterBackgroundChoice), 0, NULL, 0, NULL },
	{ "{",							TOK_START, 0 },
	{ "Name",						TOK_STRUCTPARAM | TOK_POOL_STRING | TOK_KEY | TOK_STRING(CharacterBackgroundChoice, pchName, 0), NULL },
	{ "DisplayName",				TOK_EMBEDDEDSTRUCT(CharacterBackgroundChoice, pDisplayName, parse_DisplayMessage)},
	{ "FlavorText",					TOK_EMBEDDEDSTRUCT(CharacterBackgroundChoice, pFlavorText, parse_DisplayMessage)},
	{ "BioText",					TOK_EMBEDDEDSTRUCT(CharacterBackgroundChoice, pBiographyText, parse_DisplayMessage)},
	{ "GrantedItem",				TOK_GLOBAL_NAME | TOK_POOL_STRING | TOK_SERVER_ONLY | TOK_STRINGARRAY(CharacterBackgroundChoice, ppchGrantedItems), "ItemDef" },
	{ "PowerTreeNode",				TOK_GLOBAL_NAME | TOK_POOL_STRING | TOK_STRINGARRAY(CharacterBackgroundChoice, ppchPowerTreeNodeChoices), "PTNodeDef" },
	{ "}",							TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_CharacterBackgroundChoice()
{
	int iSize = sizeof(CharacterBackgroundChoice);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_CharacterBackgroundChoice, iSize, "CharacterBackgroundChoice", NULL, "NNOCharacterBackground.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_DisplayMessage[];
#define TYPE_parse_DisplayMessage DisplayMessage
extern ParseTable parse_DisplayMessage[];
#define TYPE_parse_DisplayMessage DisplayMessage
extern ParseTable parse_CharacterBackgroundChoice[];
#define TYPE_parse_CharacterBackgroundChoice CharacterBackgroundChoice
//Structparser.exe autogenerated ParseTable for struct CharacterBackgroundGroup
#define TYPE_parse_CharacterBackgroundGroup CharacterBackgroundGroup
ParseTable parse_CharacterBackgroundGroup[] =
{
	{ "CharacterBackgroundGroup", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(CharacterBackgroundGroup), 0, NULL, 0, NULL },
	{ "{",							TOK_START, 0 },
	{ "Name",						TOK_STRUCTPARAM | TOK_POOL_STRING | TOK_KEY | TOK_STRING(CharacterBackgroundGroup, pchName, 0), NULL },
	{ "File",						TOK_POOL_STRING | TOK_CURRENTFILE(CharacterBackgroundGroup, pchFile), NULL},
	{ "DisplayName",				TOK_EMBEDDEDSTRUCT(CharacterBackgroundGroup, pDisplayName, parse_DisplayMessage)},
	{ "FlavorText",					TOK_EMBEDDEDSTRUCT(CharacterBackgroundGroup, pFlavorText, parse_DisplayMessage)},
	{ "Texture",					TOK_POOL_STRING | TOK_STRING(CharacterBackgroundGroup, pchTextureName, 0), NULL },
	{ "GrantedItem",				TOK_GLOBAL_NAME | TOK_POOL_STRING | TOK_SERVER_ONLY | TOK_STRINGARRAY(CharacterBackgroundGroup, ppchGrantedItems), "ItemDef" },
	{ "XPercent",					TOK_F32(CharacterBackgroundGroup, XPercent, 0), NULL },
	{ "YPercent",					TOK_F32(CharacterBackgroundGroup, YPercent, 0), NULL },
	{ "Backgrounds",				TOK_STRUCT(CharacterBackgroundGroup, ppBackgrounds, parse_CharacterBackgroundChoice) },
	{ "}",							TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_CharacterBackgroundGroup()
{
	int iSize = sizeof(CharacterBackgroundGroup);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_CharacterBackgroundGroup, iSize, "CharacterBackgroundGroup", NULL, "NNOCharacterBackground.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
