//This file is autogenerated. It contains function prototypes for all AUTO_COMMANDS
//from the NNOGameServer project. autogeneratednocheckin
#ifndef CMD_DECLSPEC
#define CMD_DECLSPEC
#endif


//////-----------------  PROTOTYPE FOR COMMAND GatewayMail_Delete
CMD_DECLSPEC U32 cmd_GatewayMail_Delete(const char* pchID);


//////-----------------  PROTOTYPE FOR COMMAND GatewayMail_ReportSpam
CMD_DECLSPEC U32 cmd_GatewayMail_ReportSpam(const char* pchSpammer, const char* pchID);


//////-----------------  PROTOTYPE FOR COMMAND GatewayMail_Send
CMD_DECLSPEC U32 cmd_GatewayMail_Send(const char* pchTo, const char* pchSubject, const char* pchBody);


//////-----------------  PROTOTYPE FOR COMMAND NWCureAll
CMD_DECLSPEC U32 cmd_NWCureAll( void );


//////-----------------  PROTOTYPE FOR COMMAND SetUGCDebugFailAllValidation
CMD_DECLSPEC U32 cmd_SetUGCDebugFailAllValidation(__int64 valToSet);


//////-----------------  PROTOTYPE FOR COMMAND GetUGCDebugFailAllValidation
CMD_DECLSPEC U32 cmd_GetUGCDebugFailAllValidation( void );


//////-----------------  PROTOTYPE FOR COMMAND SetUGCResourceValidation
CMD_DECLSPEC U32 cmd_SetUGCResourceValidation(__int64 valToSet);


//////-----------------  PROTOTYPE FOR COMMAND GetUGCResourceValidation
CMD_DECLSPEC U32 cmd_GetUGCResourceValidation( void );


//////-----------------  PROTOTYPE FOR COMMAND SetugcDataCorruptionDoesNotAssert
CMD_DECLSPEC U32 cmd_SetugcDataCorruptionDoesNotAssert(__int64 valToSet);


//////-----------------  PROTOTYPE FOR COMMAND GetugcDataCorruptionDoesNotAssert
CMD_DECLSPEC U32 cmd_GetugcDataCorruptionDoesNotAssert( void );


//////-----------------  PROTOTYPE FOR COMMAND SetugcVisibleFSMObjectives
CMD_DECLSPEC U32 cmd_SetugcVisibleFSMObjectives(__int64 valToSet);


//////-----------------  PROTOTYPE FOR COMMAND GetugcVisibleFSMObjectives
CMD_DECLSPEC U32 cmd_GetugcVisibleFSMObjectives( void );


//////-----------------  PROTOTYPE FOR COMMAND Setugc_RoomInfosDebug
CMD_DECLSPEC U32 cmd_Setugc_RoomInfosDebug(__int64 valToSet);


//////-----------------  PROTOTYPE FOR COMMAND Getugc_RoomInfosDebug
CMD_DECLSPEC U32 cmd_Getugc_RoomInfosDebug( void );
