//This file is autogenerated. It contains functions to call all AUTO_COMMANDS
//from the NNOGameServer project. autogeneratednocheckin
#include "ClientControllerLib.h"
#ifndef CMD_DECLSPEC
#define CMD_DECLSPEC
#endif

//////-----------------  WRAPPER FUNCTION FOR COMMAND GatewayMail_Delete (from I:\Night\Night\src\Night\GameServer\Gateway\NNOGatewayMail_cmd.c(56))
#ifndef _DEFINED_GATEWAYMAIL_DELETE
#define _DEFINED_GATEWAYMAIL_DELETE
CMD_DECLSPEC U32 cmd_GatewayMail_Delete(const char* pchID)
{
	U32 iAUTOGENReturnId;
	char *pAUTOGENWorkString = NULL;
	estrStackCreate(&pAUTOGENWorkString);
	estrCopy2(&pAUTOGENWorkString, "GatewayMail_Delete ");
	estrConcatf(&pAUTOGENWorkString, " \"%s\" ", pchID ? pchID : "");
	iAUTOGENReturnId = ClientController_SendCommandToClient(pAUTOGENWorkString);
	estrDestroy(&pAUTOGENWorkString);
	return iAUTOGENReturnId;
}

#endif

//////-----------------  WRAPPER FUNCTION FOR COMMAND GatewayMail_ReportSpam (from I:\Night\Night\src\Night\GameServer\Gateway\NNOGatewayMail_cmd.c(62))
#ifndef _DEFINED_GATEWAYMAIL_REPORTSPAM
#define _DEFINED_GATEWAYMAIL_REPORTSPAM
CMD_DECLSPEC U32 cmd_GatewayMail_ReportSpam(const char* pchSpammer, const char* pchID)
{
	U32 iAUTOGENReturnId;
	char *pAUTOGENWorkString = NULL;
	estrStackCreate(&pAUTOGENWorkString);
	estrCopy2(&pAUTOGENWorkString, "GatewayMail_ReportSpam ");
	estrConcatf(&pAUTOGENWorkString, " \"%s\" ", pchSpammer ? pchSpammer : "");
	estrConcatf(&pAUTOGENWorkString, " \"%s\" ", pchID ? pchID : "");
	iAUTOGENReturnId = ClientController_SendCommandToClient(pAUTOGENWorkString);
	estrDestroy(&pAUTOGENWorkString);
	return iAUTOGENReturnId;
}

#endif

//////-----------------  WRAPPER FUNCTION FOR COMMAND GatewayMail_Send (from I:\Night\Night\src\Night\GameServer\Gateway\NNOGatewayMail_cmd.c(50))
#ifndef _DEFINED_GATEWAYMAIL_SEND
#define _DEFINED_GATEWAYMAIL_SEND
CMD_DECLSPEC U32 cmd_GatewayMail_Send(const char* pchTo, const char* pchSubject, const char* pchBody)
{
	U32 iAUTOGENReturnId;
	char *pAUTOGENWorkString = NULL;
	estrStackCreate(&pAUTOGENWorkString);
	estrCopy2(&pAUTOGENWorkString, "GatewayMail_Send ");
	estrConcatf(&pAUTOGENWorkString, " \"%s\" ", pchTo ? pchTo : "");
	estrConcatf(&pAUTOGENWorkString, " \"%s\" ", pchSubject ? pchSubject : "");
	estrConcatf(&pAUTOGENWorkString, " \"%s\" ", pchBody ? pchBody : "");
	iAUTOGENReturnId = ClientController_SendCommandToClient(pAUTOGENWorkString);
	estrDestroy(&pAUTOGENWorkString);
	return iAUTOGENReturnId;
}

#endif

//////-----------------  WRAPPER FUNCTION FOR COMMAND NWCureAll (from I:\Night\Night\src\Night\GameServer\NNOGameServer.c(26))
#ifndef _DEFINED_NWCUREALL
#define _DEFINED_NWCUREALL
CMD_DECLSPEC U32 cmd_NWCureAll( void )
{
	U32 iAUTOGENReturnId;
	char *pAUTOGENWorkString = NULL;
	estrStackCreate(&pAUTOGENWorkString);
	estrCopy2(&pAUTOGENWorkString, "NWCureAll ");
	iAUTOGENReturnId = ClientController_SendCommandToClient(pAUTOGENWorkString);
	estrDestroy(&pAUTOGENWorkString);
	return iAUTOGENReturnId;
}

#endif

//////-----------------  WRAPPER FUNCTION FOR COMMAND SetUGCDebugFailAllValidation (from I:\Night\Night\src\Night\GameServer\..\Common\UGC\NNOUGCValidateCommon.c(0))
#ifndef _DEFINED_SETUGCDEBUGFAILALLVALIDATION
#define _DEFINED_SETUGCDEBUGFAILALLVALIDATION
CMD_DECLSPEC U32 cmd_SetUGCDebugFailAllValidation(__int64 valToSet)
{
	U32 iAUTOGENReturnId;
	char *pAUTOGENWorkString = NULL;
	estrStackCreate(&pAUTOGENWorkString);
	estrCopy2(&pAUTOGENWorkString, "UGCDebugFailAllValidation ");
	estrConcatf(&pAUTOGENWorkString, PRINTF_CODE_FOR_INT(valToSet), valToSet);
	iAUTOGENReturnId = ClientController_SendCommandToClient(pAUTOGENWorkString);
	estrDestroy(&pAUTOGENWorkString);
	return iAUTOGENReturnId;
}

#endif

//////-----------------  WRAPPER FUNCTION FOR COMMAND GetUGCDebugFailAllValidation (from I:\Night\Night\src\Night\GameServer\..\Common\UGC\NNOUGCValidateCommon.c(0))
#ifndef _DEFINED_GETUGCDEBUGFAILALLVALIDATION
#define _DEFINED_GETUGCDEBUGFAILALLVALIDATION
CMD_DECLSPEC U32 cmd_GetUGCDebugFailAllValidation( void )
{
	U32 iAUTOGENReturnId;
	char *pAUTOGENWorkString = NULL;
	estrStackCreate(&pAUTOGENWorkString);
	estrCopy2(&pAUTOGENWorkString, "UGCDebugFailAllValidation ");
	iAUTOGENReturnId = ClientController_SendCommandToClient(pAUTOGENWorkString);
	estrDestroy(&pAUTOGENWorkString);
	return iAUTOGENReturnId;
}

#endif

//////-----------------  WRAPPER FUNCTION FOR COMMAND SetUGCResourceValidation (from I:\Night\Night\src\Night\GameServer\..\Common\UGC\NNOUGCCommon.c(0))
#ifndef _DEFINED_SETUGCRESOURCEVALIDATION
#define _DEFINED_SETUGCRESOURCEVALIDATION
CMD_DECLSPEC U32 cmd_SetUGCResourceValidation(__int64 valToSet)
{
	U32 iAUTOGENReturnId;
	char *pAUTOGENWorkString = NULL;
	estrStackCreate(&pAUTOGENWorkString);
	estrCopy2(&pAUTOGENWorkString, "UGCResourceValidation ");
	estrConcatf(&pAUTOGENWorkString, PRINTF_CODE_FOR_INT(valToSet), valToSet);
	iAUTOGENReturnId = ClientController_SendCommandToClient(pAUTOGENWorkString);
	estrDestroy(&pAUTOGENWorkString);
	return iAUTOGENReturnId;
}

#endif

//////-----------------  WRAPPER FUNCTION FOR COMMAND GetUGCResourceValidation (from I:\Night\Night\src\Night\GameServer\..\Common\UGC\NNOUGCCommon.c(0))
#ifndef _DEFINED_GETUGCRESOURCEVALIDATION
#define _DEFINED_GETUGCRESOURCEVALIDATION
CMD_DECLSPEC U32 cmd_GetUGCResourceValidation( void )
{
	U32 iAUTOGENReturnId;
	char *pAUTOGENWorkString = NULL;
	estrStackCreate(&pAUTOGENWorkString);
	estrCopy2(&pAUTOGENWorkString, "UGCResourceValidation ");
	iAUTOGENReturnId = ClientController_SendCommandToClient(pAUTOGENWorkString);
	estrDestroy(&pAUTOGENWorkString);
	return iAUTOGENReturnId;
}

#endif

//////-----------------  WRAPPER FUNCTION FOR COMMAND SetugcDataCorruptionDoesNotAssert (from I:\Night\Night\src\Night\GameServer\..\Common\UGC\NNOUGCFixupCommon.c(0))
#ifndef _DEFINED_SETUGCDATACORRUPTIONDOESNOTASSERT
#define _DEFINED_SETUGCDATACORRUPTIONDOESNOTASSERT
CMD_DECLSPEC U32 cmd_SetugcDataCorruptionDoesNotAssert(__int64 valToSet)
{
	U32 iAUTOGENReturnId;
	char *pAUTOGENWorkString = NULL;
	estrStackCreate(&pAUTOGENWorkString);
	estrCopy2(&pAUTOGENWorkString, "ugcDataCorruptionDoesNotAssert ");
	estrConcatf(&pAUTOGENWorkString, PRINTF_CODE_FOR_INT(valToSet), valToSet);
	iAUTOGENReturnId = ClientController_SendCommandToClient(pAUTOGENWorkString);
	estrDestroy(&pAUTOGENWorkString);
	return iAUTOGENReturnId;
}

#endif

//////-----------------  WRAPPER FUNCTION FOR COMMAND GetugcDataCorruptionDoesNotAssert (from I:\Night\Night\src\Night\GameServer\..\Common\UGC\NNOUGCFixupCommon.c(0))
#ifndef _DEFINED_GETUGCDATACORRUPTIONDOESNOTASSERT
#define _DEFINED_GETUGCDATACORRUPTIONDOESNOTASSERT
CMD_DECLSPEC U32 cmd_GetugcDataCorruptionDoesNotAssert( void )
{
	U32 iAUTOGENReturnId;
	char *pAUTOGENWorkString = NULL;
	estrStackCreate(&pAUTOGENWorkString);
	estrCopy2(&pAUTOGENWorkString, "ugcDataCorruptionDoesNotAssert ");
	iAUTOGENReturnId = ClientController_SendCommandToClient(pAUTOGENWorkString);
	estrDestroy(&pAUTOGENWorkString);
	return iAUTOGENReturnId;
}

#endif

//////-----------------  WRAPPER FUNCTION FOR COMMAND SetugcVisibleFSMObjectives (from I:\Night\Night\src\Night\GameServer\UGC\gslNNOUGCGenerateMission.c(0))
#ifndef _DEFINED_SETUGCVISIBLEFSMOBJECTIVES
#define _DEFINED_SETUGCVISIBLEFSMOBJECTIVES
CMD_DECLSPEC U32 cmd_SetugcVisibleFSMObjectives(__int64 valToSet)
{
	U32 iAUTOGENReturnId;
	char *pAUTOGENWorkString = NULL;
	estrStackCreate(&pAUTOGENWorkString);
	estrCopy2(&pAUTOGENWorkString, "ugcVisibleFSMObjectives ");
	estrConcatf(&pAUTOGENWorkString, PRINTF_CODE_FOR_INT(valToSet), valToSet);
	iAUTOGENReturnId = ClientController_SendCommandToClient(pAUTOGENWorkString);
	estrDestroy(&pAUTOGENWorkString);
	return iAUTOGENReturnId;
}

#endif

//////-----------------  WRAPPER FUNCTION FOR COMMAND GetugcVisibleFSMObjectives (from I:\Night\Night\src\Night\GameServer\UGC\gslNNOUGCGenerateMission.c(0))
#ifndef _DEFINED_GETUGCVISIBLEFSMOBJECTIVES
#define _DEFINED_GETUGCVISIBLEFSMOBJECTIVES
CMD_DECLSPEC U32 cmd_GetugcVisibleFSMObjectives( void )
{
	U32 iAUTOGENReturnId;
	char *pAUTOGENWorkString = NULL;
	estrStackCreate(&pAUTOGENWorkString);
	estrCopy2(&pAUTOGENWorkString, "ugcVisibleFSMObjectives ");
	iAUTOGENReturnId = ClientController_SendCommandToClient(pAUTOGENWorkString);
	estrDestroy(&pAUTOGENWorkString);
	return iAUTOGENReturnId;
}

#endif

//////-----------------  WRAPPER FUNCTION FOR COMMAND Setugc_RoomInfosDebug (from I:\Night\Night\src\Night\GameServer\..\Common\UGC\NNOUGCInteriorCommon.c(0))
#ifndef _DEFINED_SETUGC_ROOMINFOSDEBUG
#define _DEFINED_SETUGC_ROOMINFOSDEBUG
CMD_DECLSPEC U32 cmd_Setugc_RoomInfosDebug(__int64 valToSet)
{
	U32 iAUTOGENReturnId;
	char *pAUTOGENWorkString = NULL;
	estrStackCreate(&pAUTOGENWorkString);
	estrCopy2(&pAUTOGENWorkString, "ugc_RoomInfosDebug ");
	estrConcatf(&pAUTOGENWorkString, PRINTF_CODE_FOR_INT(valToSet), valToSet);
	iAUTOGENReturnId = ClientController_SendCommandToClient(pAUTOGENWorkString);
	estrDestroy(&pAUTOGENWorkString);
	return iAUTOGENReturnId;
}

#endif

//////-----------------  WRAPPER FUNCTION FOR COMMAND Getugc_RoomInfosDebug (from I:\Night\Night\src\Night\GameServer\..\Common\UGC\NNOUGCInteriorCommon.c(0))
#ifndef _DEFINED_GETUGC_ROOMINFOSDEBUG
#define _DEFINED_GETUGC_ROOMINFOSDEBUG
CMD_DECLSPEC U32 cmd_Getugc_RoomInfosDebug( void )
{
	U32 iAUTOGENReturnId;
	char *pAUTOGENWorkString = NULL;
	estrStackCreate(&pAUTOGENWorkString);
	estrCopy2(&pAUTOGENWorkString, "ugc_RoomInfosDebug ");
	iAUTOGENReturnId = ClientController_SendCommandToClient(pAUTOGENWorkString);
	estrDestroy(&pAUTOGENWorkString);
	return iAUTOGENReturnId;
}

#endif
