//This file contains data and prototypes for magic commands. It is autogenerated by StructParser

//autogeneratednocheckin
#include "cmdparse.h"
#include "textparser.h"
#include "globaltypes.h"
#include "net/net.h"
#include "net/netpacketutil.h"
#include "structnet.h"
#include "structInternals.h"
static char sNNOGameServerName[] = "NNOGameServer";
//if one of these includes fails, you're trying to use expression list commands somewhere illegal... talk to Raoul
#include "ExpressionMinimal.h"
#include "ExpressionFunc.h"
#include "ScratchStack.h"
#include "mathutil.h"
#include "timing.h"
typedef struct Entity Entity;

//About to make prototype for entExternGetCommandEntity and Entity.
//If entExterGetCommandEntity fails to link, it's because you're in a project that doesn't
//support entities. Talk to Ben or Alex
typedef struct Entity Entity;
extern Entity *entExternGetCommandEntity(CmdContext *context);
extern void GatewayMail_Delete(Entity* pEnt, const char* pchID); // function defined in I:\Night\Night\src\Night\GameServer\Gateway\NNOGatewayMail_cmd.c
static void GatewayMail_Delete_MAGICCOMMANDWRAPPER(CMDARGS) { 	READARGS1(char*, arg1);
	CHECK_ENTITY_PTR_VALIDITY(pEnt);
	GatewayMail_Delete((Entity*)entExternGetCommandEntity(cmd_context), arg1);
	CHECK_ENTITY_PTR_VALIDITY(pEnt);
}
extern void GatewayMail_ReportSpam(Entity* pEnt, const char* pchSpammer, const char* pchID); // function defined in I:\Night\Night\src\Night\GameServer\Gateway\NNOGatewayMail_cmd.c
static void GatewayMail_ReportSpam_MAGICCOMMANDWRAPPER(CMDARGS) { 	READARGS2(char*, arg1, char*, arg2);
	CHECK_ENTITY_PTR_VALIDITY(pEnt);
	GatewayMail_ReportSpam((Entity*)entExternGetCommandEntity(cmd_context), arg1, arg2);
	CHECK_ENTITY_PTR_VALIDITY(pEnt);
}
extern void GatewayMail_Send(Entity* pEnt, const char* pchTo, const char* pchSubject, const char* pchBody); // function defined in I:\Night\Night\src\Night\GameServer\Gateway\NNOGatewayMail_cmd.c
static void GatewayMail_Send_MAGICCOMMANDWRAPPER(CMDARGS) { 	READARGS3(char*, arg1, char*, arg2, char*, arg3);
	CHECK_ENTITY_PTR_VALIDITY(pEnt);
	GatewayMail_Send((Entity*)entExternGetCommandEntity(cmd_context), arg1, arg2, arg3);
	CHECK_ENTITY_PTR_VALIDITY(pEnt);
}
extern void NWCureAll(Entity* e); // function defined in I:\Night\Night\src\Night\GameServer\NNOGameServer.c
static void NWCureAll_MAGICCOMMANDWRAPPER(CMDARGS) { 	CHECK_ENTITY_PTR_VALIDITY(e);
	NWCureAll((Entity*)entExternGetCommandEntity(cmd_context));
	CHECK_ENTITY_PTR_VALIDITY(e);
}
static Cmd cmdSetData_gGatewayCmdList_GatewayMail_Delete[] = {
	{ 0, "GatewayMail_Delete", "NNOGatewayMail_cmd.c", 56, NULL, sNNOGameServerName, " ggatewaycmdlist ", {{"pchID", MULTI_STRING, 0, 0, CMDAF_ALLOCATED, 0,  NAMELISTTYPE_NONE, NULL }},0 | CMDF_PASSENTITY,
		"No comment provided", GatewayMail_Delete_MAGICCOMMANDWRAPPER,{NULL,MULTI_NONE,NULL,0,0}, NULL}
	
};
static Cmd cmdSetData_gGatewayCmdList_GatewayMail_ReportSpam[] = {
	{ 0, "GatewayMail_ReportSpam", "NNOGatewayMail_cmd.c", 62, NULL, sNNOGameServerName, " ggatewaycmdlist ", {{"pchSpammer", MULTI_STRING, 0, 0, CMDAF_ALLOCATED, 0,  NAMELISTTYPE_NONE, NULL }, {"pchID", MULTI_STRING, 0, 0, CMDAF_ALLOCATED, 0,  NAMELISTTYPE_NONE, NULL }},0 | CMDF_PASSENTITY,
		"No comment provided", GatewayMail_ReportSpam_MAGICCOMMANDWRAPPER,{NULL,MULTI_NONE,NULL,0,0}, NULL}
	
};
static Cmd cmdSetData_gGatewayCmdList_GatewayMail_Send[] = {
	{ 0, "GatewayMail_Send", "NNOGatewayMail_cmd.c", 50, NULL, sNNOGameServerName, " ggatewaycmdlist ", {{"pchTo", MULTI_STRING, 0, 0, CMDAF_ALLOCATED, 0,  NAMELISTTYPE_NONE, NULL }, {"pchSubject", MULTI_STRING, 0, 0, CMDAF_ALLOCATED, 0,  NAMELISTTYPE_NONE, NULL }, {"pchBody", MULTI_STRING, 0, 0, CMDAF_ALLOCATED, 0,  NAMELISTTYPE_NONE, NULL }},0 | CMDF_PASSENTITY,
		"No comment provided", GatewayMail_Send_MAGICCOMMANDWRAPPER,{NULL,MULTI_NONE,NULL,0,0}, NULL}
	
};
static Cmd cmdSetData_NWCureAll[] = {
	{ 5, "NWCureAll", "NNOGameServer.c", 26, NULL, sNNOGameServerName, NULL, {{0}},0 | CMDF_PASSENTITY,
		"For Neverwinter devs. Refill character hp, action points, remove injuries. based on Refill_HP_POW()\n", NWCureAll_MAGICCOMMANDWRAPPER,{NULL,MULTI_NONE,NULL,0,0}, NULL}
	
};
static Cmd cmdVarSetData_UGCDebugFailAllValidation =
{
	9, "UGCDebugFailAllValidation", "NNOUGCValidateCommon.c", 38, NULL, sNNOGameServerName,  NULL, {{ NULL, MULTI_INT, NULL, 0, 0, 0 }},CMDF_PRINTVARS  | CMDF_COMMANDLINE | CMDF_COMMANDLINEONLY,
		"No comment provided", NULL, {NULL, MULTI_NONE,0,0,0}, NULL
};

static Cmd cmdVarSetData_UGCResourceValidation =
{
	9, "UGCResourceValidation", "NNOUGCCommon.c", 81, NULL, sNNOGameServerName,  NULL, {{ NULL, MULTI_INT, NULL, 0, 0, 0 }},CMDF_PRINTVARS  | CMDF_COMMANDLINE | CMDF_COMMANDLINEONLY,
		"No comment provided", NULL, {NULL, MULTI_NONE,0,0,0}, NULL
};

static Cmd cmdVarSetData_ugcDataCorruptionDoesNotAssert =
{
	9, "ugcDataCorruptionDoesNotAssert", "NNOUGCFixupCommon.c", 1187, NULL, sNNOGameServerName,  NULL, {{ NULL, MULTI_INT, NULL, 0, 0, 0 }},CMDF_PRINTVARS ,
		"No comment provided", NULL, {NULL, MULTI_NONE,0,0,0}, NULL
};

static Cmd cmdVarSetData_ugcVisibleFSMObjectives =
{
	9, "ugcVisibleFSMObjectives", "gslNNOUGCGenerateMission.c", 27, NULL, sNNOGameServerName,  NULL, {{ NULL, MULTI_INT, NULL, 0, 0, 0 }},CMDF_PRINTVARS ,
		"No comment provided", NULL, {NULL, MULTI_NONE,0,0,0}, NULL
};

static Cmd cmdVarSetData_ugc_RoomInfosDebug =
{
	9, "ugc_RoomInfosDebug", "NNOUGCInteriorCommon.c", 25, NULL, sNNOGameServerName,  NULL, {{ NULL, MULTI_INT, NULL, 0, 0, 0 }},CMDF_PRINTVARS ,
		"No comment provided", NULL, {NULL, MULTI_NONE,0,0,0}, NULL
};


void AutoGen_RegisterAutoCmd_UGCDebugFailAllValidation(void *pAddress, int iSize)
{
	cmdVarSetData_UGCDebugFailAllValidation.data[0].ptr = pAddress;
	cmdVarSetData_UGCDebugFailAllValidation.data[0].data_size = iSize;
}
void AutoGen_RegisterAutoCmd_UGCResourceValidation(void *pAddress, int iSize)
{
	cmdVarSetData_UGCResourceValidation.data[0].ptr = pAddress;
	cmdVarSetData_UGCResourceValidation.data[0].data_size = iSize;
}
void AutoGen_RegisterAutoCmd_ugcDataCorruptionDoesNotAssert(void *pAddress, int iSize)
{
	cmdVarSetData_ugcDataCorruptionDoesNotAssert.data[0].ptr = pAddress;
	cmdVarSetData_ugcDataCorruptionDoesNotAssert.data[0].data_size = iSize;
}
void AutoGen_RegisterAutoCmd_ugcVisibleFSMObjectives(void *pAddress, int iSize)
{
	cmdVarSetData_ugcVisibleFSMObjectives.data[0].ptr = pAddress;
	cmdVarSetData_ugcVisibleFSMObjectives.data[0].data_size = iSize;
}
void AutoGen_RegisterAutoCmd_ugc_RoomInfosDebug(void *pAddress, int iSize)
{
	cmdVarSetData_ugc_RoomInfosDebug.data[0].ptr = pAddress;
	cmdVarSetData_ugc_RoomInfosDebug.data[0].data_size = iSize;
}

extern CmdList gGatewayCmdList;
extern CmdList gGatewayCmdList;
extern CmdList gGatewayCmdList;
extern CmdList gRemoteCmdList;
extern CmdList gSlowRemoteCmdList;
extern ParseTable parse_Entity[];
void Add_Auto_Cmds_NNOGameServer(void)
{
	cmdAddSingleCmdToList(&gGatewayCmdList, &cmdSetData_gGatewayCmdList_GatewayMail_Delete[0]);
	cmdAddSingleCmdToList(&gGatewayCmdList, &cmdSetData_gGatewayCmdList_GatewayMail_ReportSpam[0]);
	cmdAddSingleCmdToList(&gGatewayCmdList, &cmdSetData_gGatewayCmdList_GatewayMail_Send[0]);
	cmdAddSingleCmdToList(&gGlobalCmdList, &cmdSetData_NWCureAll[0]);
	cmdAddSingleCmdToList(&gGlobalCmdList, &cmdVarSetData_UGCDebugFailAllValidation);
	cmdAddSingleCmdToList(&gGlobalCmdList, &cmdVarSetData_UGCResourceValidation);
	cmdAddSingleCmdToList(&gGlobalCmdList, &cmdVarSetData_ugcDataCorruptionDoesNotAssert);
	cmdAddSingleCmdToList(&gGlobalCmdList, &cmdVarSetData_ugcVisibleFSMObjectives);
	cmdAddSingleCmdToList(&gGlobalCmdList, &cmdVarSetData_ugc_RoomInfosDebug);
};
void Add_Auto_Cmds_NNOGameServer_Later(void)
{
};
#pragma warning (disable:4054) // casting function pointers as data pointers
extern char* scp_ExprNNOTranslatePowerAutoDesc(ExprContext* pContext, const char* pchPowerDefName);
ExprFuncDesc AutoCmd_NNOGameServer_ExprList[] = 
{
	{ 0, 0, (void**)scp_ExprNNOTranslatePowerAutoDesc, NULL, "scp_NNOTranslatePowerAutoDesc", "Gets the formatted AutoDesc message for the PowerDef\n", "NNOItemDescription.c", 662, {
		{ MULTI_STRING, "pchPowerDefName", NULL, NULL, false, ExprStaticCheckCat_None }, 		{ MULTI_NONE, NULL, NULL, NULL, false, ExprStaticCheckCat_None}},
		 {MULTI_STRING, NULL, NULL, NULL, false, ExprStaticCheckCat_None},
		{ {"UIGen"}, {NULL} },  0, "STR_EXPRCX_STR", NULL},
};
void AutoCmds_NNOGameServer_RegisterExprLists(void)
{
	exprRegisterFunctionTable(AutoCmd_NNOGameServer_ExprList, sizeof(AutoCmd_NNOGameServer_ExprList)/sizeof(AutoCmd_NNOGameServer_ExprList[0]), false);
}

#ifdef THIS_SYMBOL_IS_NOT_DEFINED
PARSABLE
5
 4194304 0 "GatewayMail_Delete" "GatewayMail_Delete"  ""  ""  ""  ""  ""  ""  ""  "" 0 "" 0 "I:\Night\Night\src\Night\GameServer\Gateway\NNOGatewayMail_cmd.c" 56 "No comment provided"  "gGatewayCmdList"  ""  ""  ""  ""  ""  ""  ""  "ggatewaycmdlist"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  0 "void" "" 0 "" 0 2 39 "Entity*" "pEnt" "" "" 0 0 0 0 0 "" 7 "char*" "pchID" "" "" 0 0 0 0 0 "" 0  ""  ""  ""  ""  ""  ""  ""  ""  "" "" "" 0 0 0 0 0 0  0  0 
 4194304 0 "GatewayMail_ReportSpam" "GatewayMail_ReportSpam"  ""  ""  ""  ""  ""  ""  ""  "" 0 "" 0 "I:\Night\Night\src\Night\GameServer\Gateway\NNOGatewayMail_cmd.c" 62 "No comment provided"  "gGatewayCmdList"  ""  ""  ""  ""  ""  ""  ""  "ggatewaycmdlist"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  0 "void" "" 0 "" 0 3 39 "Entity*" "pEnt" "" "" 0 0 0 0 0 "" 7 "char*" "pchSpammer" "" "" 0 0 0 0 0 "" 7 "char*" "pchID" "" "" 0 0 0 0 0 "" 0  ""  ""  ""  ""  ""  ""  ""  ""  "" "" "" "" 0 0 0 0 0 0 0 0  0  0 
 4194304 0 "GatewayMail_Send" "GatewayMail_Send"  ""  ""  ""  ""  ""  ""  ""  "" 0 "" 0 "I:\Night\Night\src\Night\GameServer\Gateway\NNOGatewayMail_cmd.c" 50 "No comment provided"  "gGatewayCmdList"  ""  ""  ""  ""  ""  ""  ""  "ggatewaycmdlist"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  0 "void" "" 0 "" 0 4 39 "Entity*" "pEnt" "" "" 0 0 0 0 0 "" 7 "const char*" "pchTo" "" "" 0 0 0 0 0 "" 7 "const char*" "pchSubject" "" "" 0 0 0 0 0 "" 7 "const char*" "pchBody" "" "" 0 0 0 0 0 "" 0  ""  ""  ""  ""  ""  ""  ""  ""  "" "" "" "" "" 0 0 0 0 0 0 0 0 0 0  0  0 
 4194304 0 "NWCureAll" "NWCureAll"  ""  ""  ""  ""  ""  ""  ""  "" 5 "" 0 "I:\Night\Night\src\Night\GameServer\NNOGameServer.c" 26 "For Neverwinter devs. Refill character hp, action points, remove injuries. based on Refill_HP_POW()\n"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  0 "void" "" 0 "" 0 1 39 "Entity*" "e" "" "" 0 0 0 0 0 "" 0  ""  ""  ""  ""  ""  ""  ""  ""  "" "" 0 0 0 0  0  0 
 2048 0 "scp_ExprNNOTranslatePowerAutoDesc" "scp_NNOTranslatePowerAutoDesc"  ""  ""  ""  ""  ""  ""  ""  "" 9 "" 0 "I:\Night\Night\src\Night\GameServer\..\Common\NNOItemDescription.c" 662 "Gets the formatted AutoDesc message for the PowerDef\n"  ""  ""  ""  ""  ""  ""  ""  ""  "uigen"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  7 "char*" "" 0 "" 0 2 26 "ExprContext*" "pContext" "" "" 0 0 0 0 0 "" 7 "const char*" "pchPowerDefName" "" "" 0 0 0 0 0 "" 1  "UIGen"  ""  ""  ""  ""  ""  ""  ""  "" "" "" 0 0 0 0 0 1  0  0 
5
 2129920 0 "UGCDebugFailAllValidation" "I:\Night\Night\src\Night\GameServer\..\Common\UGC\NNOUGCValidateCommon.c" 38 1 9 "" 0  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "No comment provided" "" 0  0  0  0 
 2129920 0 "UGCResourceValidation" "I:\Night\Night\src\Night\GameServer\..\Common\UGC\NNOUGCCommon.c" 81 1 9 "" 0  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "No comment provided" "" 0  0  0  0 
 0 0 "ugcDataCorruptionDoesNotAssert" "I:\Night\Night\src\Night\GameServer\..\Common\UGC\NNOUGCFixupCommon.c" 1187 1 9 "" 0  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "No comment provided" "" 0  0  0  0 
 0 0 "ugcVisibleFSMObjectives" "I:\Night\Night\src\Night\GameServer\UGC\gslNNOUGCGenerateMission.c" 27 1 9 "" 0  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "No comment provided" "" 0  0  0  0 
 0 0 "ugc_RoomInfosDebug" "I:\Night\Night\src\Night\GameServer\..\Common\UGC\NNOUGCInteriorCommon.c" 25 1 9 "" 0  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "No comment provided" "" 0  0  0  0 
#endif
