#include "textparser.h"
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct MappedPowerDef
#define TYPE_parse_MappedPowerDef MappedPowerDef
ParseTable parse_MappedPowerDef[] =
{
	{ "MappedPowerDef", 		TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MappedPowerDef), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "Name",				TOK_POOL_STRING | TOK_STRING(MappedPowerDef, pchName, 0), NULL },
	{ "DisplayName",		TOK_REFERENCE(MappedPowerDef, hDisplayName, 0, "Message") },
	{ "Description",		TOK_REFERENCE(MappedPowerDef, hDescription, 0, "Message") },
	{ "DescriptionLong",	TOK_REFERENCE(MappedPowerDef, hDescriptionLong, 0, "Message") },
	{ "AutoDesc",			TOK_REFERENCE(MappedPowerDef, hAutoDesc, 0, "Message") },
	{ "Icon",				TOK_POOL_STRING | TOK_STRING(MappedPowerDef, pchIconName, 0), NULL },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_MappedPowerDef()
{
	int iSize = sizeof(MappedPowerDef);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_MappedPowerDef, iSize, "MappedPowerDef", NULL, "NNOGatewayStructMapping.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct MappedMissionDef
#define TYPE_parse_MappedMissionDef MappedMissionDef
ParseTable parse_MappedMissionDef[] =
{
	{ "MappedMissionDef", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MappedMissionDef), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "Name",				TOK_POOL_STRING | TOK_STRING(MappedMissionDef, pchName, 0), NULL },
	{ "DisplayName",		TOK_REFERENCE(MappedMissionDef, hDisplayName, 0, "Message") },
	{ "DisplayLong",		TOK_REFERENCE(MappedMissionDef, hDisplayLong, 0, "Message") },
	{ "Summary",			TOK_REFERENCE(MappedMissionDef, hSummary, 0, "Message") },
	{ "Icon",				TOK_POOL_STRING | TOK_STRING(MappedMissionDef, pchIconName, 0), NULL },
	{ "PerkPoints",			TOK_AUTOINT(MappedMissionDef, iPerkPoints, 0), NULL },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_MappedMissionDef()
{
	int iSize = sizeof(MappedMissionDef);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_MappedMissionDef, iSize, "MappedMissionDef", NULL, "NNOGatewayStructMapping.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct MappedCharacterClass
#define TYPE_parse_MappedCharacterClass MappedCharacterClass
ParseTable parse_MappedCharacterClass[] =
{
	{ "MappedCharacterClass", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MappedCharacterClass), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "Name",					TOK_POOL_STRING | TOK_STRING(MappedCharacterClass, pchName, 0), NULL },
	{ "DisplayName",			TOK_REFERENCE(MappedCharacterClass, hDisplayName, 0, "Message") },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_MappedCharacterClass()
{
	int iSize = sizeof(MappedCharacterClass);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_MappedCharacterClass, iSize, "MappedCharacterClass", NULL, "NNOGatewayStructMapping.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_ItemPowerDefRef[];
#define TYPE_parse_ItemPowerDefRef ItemPowerDefRef
//Structparser.exe autogenerated ParseTable for struct MappedItemDef
#define TYPE_parse_MappedItemDef MappedItemDef
ParseTable parse_MappedItemDef[] =
{
	{ "MappedItemDef", 		TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MappedItemDef), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "Name",				TOK_POOL_STRING | TOK_STRING(MappedItemDef, pchName, 0), NULL },
	{ "displayNameMsg",		TOK_REFERENCE(MappedItemDef, hDisplayName, 0, "Message") },
	{ "descriptionMsg",		TOK_REFERENCE(MappedItemDef, hDescription, 0, "Message") },
	{ "descShortMsg",		TOK_REFERENCE(MappedItemDef, hDescriptionShort, 0, "Message") },
	{ "msgAutoDesc",		TOK_REFERENCE(MappedItemDef, hAutoDesc, 0, "Message") },
	{ "Icon",				TOK_POOL_STRING | TOK_STRING(MappedItemDef, pchIconName, 0), NULL },
	{ "Type",				TOK_AUTOINT(MappedItemDef, eType, 0), ItemTypeEnum },
	{ "Quality",			TOK_AUTOINT(MappedItemDef, Quality, 0), ItemQualityEnum },
	{ "ItemPowerDefRefs",	TOK_STRUCT(MappedItemDef, eaItemPowerDefRefs, parse_ItemPowerDefRef) },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_MappedItemDef()
{
	int iSize = sizeof(MappedItemDef);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_MappedItemDef, iSize, "MappedItemDef", NULL, "NNOGatewayStructMapping.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct MappedItemAssignmentDef
#define TYPE_parse_MappedItemAssignmentDef MappedItemAssignmentDef
ParseTable parse_MappedItemAssignmentDef[] =
{
	{ "MappedItemAssignmentDef", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MappedItemAssignmentDef), 0, NULL, 0, NULL },
	{ "{",							TOK_START, 0 },
	{ "Name",						TOK_POOL_STRING | TOK_STRING(MappedItemAssignmentDef, pchName, 0), NULL },
	{ "Icon",						TOK_POOL_STRING | TOK_STRING(MappedItemAssignmentDef, pchIconName, 0), NULL },
	{ "RequiredRank",				TOK_AUTOINT(MappedItemAssignmentDef, iRequiredRank, 0), NULL },
	{ "Duration",					TOK_AUTOINT(MappedItemAssignmentDef, uDuration, 0), NULL },
	{ "DisplayName",				TOK_REFERENCE(MappedItemAssignmentDef, hDisplayName, 0, "Message") },
	{ "Description",				TOK_REFERENCE(MappedItemAssignmentDef, hDescription, 0, "Message") },
	{ "}",							TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_MappedItemAssignmentDef()
{
	int iSize = sizeof(MappedItemAssignmentDef);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_MappedItemAssignmentDef, iSize, "MappedItemAssignmentDef", NULL, "NNOGatewayStructMapping.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_MappedSortType[];
#define TYPE_parse_MappedSortType MappedSortType
//Structparser.exe autogenerated ParseTable for struct MappedSortType
#define TYPE_parse_MappedSortType MappedSortType
ParseTable parse_MappedSortType[] =
{
	{ "MappedSortType", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MappedSortType), 0, NULL, 0, NULL },
	{ "{",				TOK_START, 0 },
	{ "index",			TOK_AUTOINT(MappedSortType, iIndex, 0), NULL },
	{ "displayname",	TOK_REFERENCE(MappedSortType, hDisplayName, 0, "Message") },
	{ "subsorttypes",	TOK_STRUCT(MappedSortType, subSortTypes, parse_MappedSortType) },
	{ "type",			TOK_AUTOINT(MappedSortType, itemSortType, 0), NULL },
	{ "Category",		TOK_POOL_STRING | TOK_STRING(MappedSortType, pchItemCategory, 0), NULL },
	{ "}",				TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_MappedSortType()
{
	int iSize = sizeof(MappedSortType);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_MappedSortType, iSize, "MappedSortType", NULL, "NNOGatewayStructMapping.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct MappedAuctionDuration
#define TYPE_parse_MappedAuctionDuration MappedAuctionDuration
ParseTable parse_MappedAuctionDuration[] =
{
	{ "MappedAuctionDuration", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MappedAuctionDuration), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "displayname",			TOK_REFERENCE(MappedAuctionDuration, hDisplayName, 0, "Message") },
	{ "duration",				TOK_AUTOINT(MappedAuctionDuration, iDuration, 0), NULL },
	{ "defaultduration",		TOK_AUTOINT(MappedAuctionDuration, bDefaultDuration, 0), NULL },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_MappedAuctionDuration()
{
	int iSize = sizeof(MappedAuctionDuration);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_MappedAuctionDuration, iSize, "MappedAuctionDuration", NULL, "NNOGatewayStructMapping.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_MappedSortType[];
#define TYPE_parse_MappedSortType MappedSortType
extern ParseTable parse_MappedAuctionDuration[];
#define TYPE_parse_MappedAuctionDuration MappedAuctionDuration
//Structparser.exe autogenerated ParseTable for struct MappedAuctionSettings
#define TYPE_parse_MappedAuctionSettings MappedAuctionSettings
ParseTable parse_MappedAuctionSettings[] =
{
	{ "MappedAuctionSettings", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MappedAuctionSettings), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "sorttypes",				TOK_STRUCT(MappedAuctionSettings, SortTypes, parse_MappedSortType) },
	{ "auctiondurations",		TOK_STRUCT(MappedAuctionSettings, AuctionDurations, parse_MappedAuctionDuration) },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_MappedAuctionSettings()
{
	int iSize = sizeof(MappedAuctionSettings);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_MappedAuctionSettings, iSize, "MappedAuctionSettings", NULL, "NNOGatewayStructMapping.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct MappedMicroTransactionDef
#define TYPE_parse_MappedMicroTransactionDef MappedMicroTransactionDef
ParseTable parse_MappedMicroTransactionDef[] =
{
	{ "MappedMicroTransactionDef", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MappedMicroTransactionDef), 0, NULL, 0, NULL },
	{ "{",							TOK_START, 0 },
	{ "Name",						TOK_POOL_STRING | TOK_STRING(MappedMicroTransactionDef, pchName, 0), NULL },
	{ "DisplayName",				TOK_REFERENCE(MappedMicroTransactionDef, hDisplayName, 0, "Message") },
	{ "UsageInfo",					TOK_REFERENCE(MappedMicroTransactionDef, hUsageInfo, 0, "Message") },
	{ "Description",				TOK_REFERENCE(MappedMicroTransactionDef, hDescription, 0, "Message") },
	{ "ItemDef",					TOK_REFERENCE(MappedMicroTransactionDef, hItemDef, 0, "ItemDef") },
	{ "Icon",						TOK_POOL_STRING | TOK_STRING(MappedMicroTransactionDef, pchIcon, 0), NULL },
	{ "IconLarge",					TOK_POOL_STRING | TOK_STRING(MappedMicroTransactionDef, pchIconLarge, 0), NULL },
	{ "Previews",					TOK_POOL_STRING | TOK_STRINGARRAY(MappedMicroTransactionDef, eaPreviews), NULL },
	{ "}",							TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_MappedMicroTransactionDef()
{
	int iSize = sizeof(MappedMicroTransactionDef);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_MappedMicroTransactionDef, iSize, "MappedMicroTransactionDef", NULL, "NNOGatewayStructMapping.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
