#ifndef __NNOGATEWAYSTRUCTMAPPING_C_AST_H_
#define __NNOGATEWAYSTRUCTMAPPING_C_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \NNOGatewayStructMapping.c
//autogeneratednocheckin

extern ParseTable parse_MappedPowerDef[];
#define TYPE_parse_MappedPowerDef MappedPowerDef

extern ParseTable parse_MappedMissionDef[];
#define TYPE_parse_MappedMissionDef MappedMissionDef

extern ParseTable parse_MappedCharacterClass[];
#define TYPE_parse_MappedCharacterClass MappedCharacterClass

extern ParseTable parse_MappedItemDef[];
#define TYPE_parse_MappedItemDef MappedItemDef

extern ParseTable parse_MappedItemAssignmentDef[];
#define TYPE_parse_MappedItemAssignmentDef MappedItemAssignmentDef

extern ParseTable parse_MappedSortType[];
#define TYPE_parse_MappedSortType MappedSortType

extern ParseTable parse_MappedAuctionDuration[];
#define TYPE_parse_MappedAuctionDuration MappedAuctionDuration

extern ParseTable parse_MappedAuctionSettings[];
#define TYPE_parse_MappedAuctionSettings MappedAuctionSettings

extern ParseTable parse_MappedMicroTransactionDef[];
#define TYPE_parse_MappedMicroTransactionDef MappedMicroTransactionDef

#endif
