#ifndef __NNOGATEWAYMAPPEDENTITY_C_AST_H_
#define __NNOGATEWAYMAPPEDENTITY_C_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \NNOGatewayMappedEntity.c
//autogeneratednocheckin

extern ParseTable parse_OwnedContainer[];
#define TYPE_parse_OwnedContainer OwnedContainer

extern ParseTable parse_MappedInventory[];
#define TYPE_parse_MappedInventory MappedInventory

extern ParseTable parse_MappedAttribs[];
#define TYPE_parse_MappedAttribs MappedAttribs

extern ParseTable parse_MappedCurrencies[];
#define TYPE_parse_MappedCurrencies MappedCurrencies

extern ParseTable parse_MappedItemAssignment[];
#define TYPE_parse_MappedItemAssignment MappedItemAssignment

extern ParseTable parse_MappedItemAssignments[];
#define TYPE_parse_MappedItemAssignments MappedItemAssignments

extern ParseTable parse_MappedEntity[];
#define TYPE_parse_MappedEntity MappedEntity

#endif
