#include "textparser.h"
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct MappedMailHeader
#define TYPE_parse_MappedMailHeader MappedMailHeader
ParseTable parse_MappedMailHeader[] =
{
	{ "MappedMailHeader", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MappedMailHeader), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "From",				TOK_ESTRING | TOK_STRING(MappedMailHeader, estrFrom, 0), NULL },
	{ "FromHandle",			TOK_ESTRING | TOK_STRING(MappedMailHeader, estrFromHandle, 0), NULL },
	{ "Subject",			TOK_ESTRING | TOK_STRING(MappedMailHeader, estrSubject, 0), NULL },
	{ "Read",				TOK_AUTOINT(MappedMailHeader, bRead, -1), NULL },
	{ "ID",					TOK_AUTOINT(MappedMailHeader, uID, 0), NULL },
	{ "Sent",				TOK_AUTOINT(MappedMailHeader, sent, 0), NULL , 0 , "JSON_SECS_TO_RFC822 = 1"},
	{ "Type",				TOK_AUTOINT(MappedMailHeader, eType, -1), EMailV3SenderTypeEnum },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_MappedMailHeader()
{
	int iSize = sizeof(MappedMailHeader);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_MappedMailHeader, iSize, "MappedMailHeader", NULL, "NNOGatewayMailMapping.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_MappedMailHeader[];
#define TYPE_parse_MappedMailHeader MappedMailHeader
//Structparser.exe autogenerated ParseTable for struct MappedMailList
#define TYPE_parse_MappedMailList MappedMailList
ParseTable parse_MappedMailList[] =
{
	{ "MappedMailList", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MappedMailList), 0, NULL, 0, NULL },
	{ "{",				TOK_START, 0 },
	{ "Messages",		TOK_STRUCT(MappedMailList, ppMessages, parse_MappedMailHeader) },
	{ "}",				TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_MappedMailList()
{
	int iSize = sizeof(MappedMailList);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_MappedMailList, iSize, "MappedMailList", NULL, "NNOGatewayMailMapping.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct MappedMailItem
#define TYPE_parse_MappedMailItem MappedMailItem
ParseTable parse_MappedMailItem[] =
{
	{ "MappedMailItem", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MappedMailItem), 0, NULL, 0, NULL },
	{ "{",				TOK_START, 0 },
	{ "ItemDef",		TOK_REFERENCE(MappedMailItem, hItem, 0, "ItemDef") },
	{ "Count",			TOK_AUTOINT(MappedMailItem, iCount, 0), NULL },
	{ "}",				TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_MappedMailItem()
{
	int iSize = sizeof(MappedMailItem);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_MappedMailItem, iSize, "MappedMailItem", NULL, "NNOGatewayMailMapping.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_MappedMailItem[];
#define TYPE_parse_MappedMailItem MappedMailItem
//Structparser.exe autogenerated ParseTable for struct MappedMailBody
#define TYPE_parse_MappedMailBody MappedMailBody
ParseTable parse_MappedMailBody[] =
{
	{ "MappedMailBody", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MappedMailBody), 0, NULL, 0, NULL },
	{ "{",				TOK_START, 0 },
	{ "Body",			TOK_ESTRING | TOK_STRING(MappedMailBody, estrBody, 0), NULL },
	{ "Items",			TOK_STRUCT(MappedMailBody, ppItems, parse_MappedMailItem) },
	{ "}",				TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_MappedMailBody()
{
	int iSize = sizeof(MappedMailBody);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_MappedMailBody, iSize, "MappedMailBody", NULL, "NNOGatewayMailMapping.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_MappedMailHeader[];
#define TYPE_parse_MappedMailHeader MappedMailHeader
extern ParseTable parse_MappedMailBody[];
#define TYPE_parse_MappedMailBody MappedMailBody
//Structparser.exe autogenerated ParseTable for struct MappedMailDetail
#define TYPE_parse_MappedMailDetail MappedMailDetail
ParseTable parse_MappedMailDetail[] =
{
	{ "MappedMailDetail", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MappedMailDetail), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "Header",				TOK_OPTIONALSTRUCT(MappedMailDetail, pHeader, parse_MappedMailHeader) },
	{ "Body",				TOK_OPTIONALSTRUCT(MappedMailDetail, pBody, parse_MappedMailBody) },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_MappedMailDetail()
{
	int iSize = sizeof(MappedMailDetail);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_MappedMailDetail, iSize, "MappedMailDetail", NULL, "NNOGatewayMailMapping.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct MappedSharedBank
#define TYPE_parse_MappedSharedBank MappedSharedBank
ParseTable parse_MappedSharedBank[] =
{
	{ "MappedSharedBank", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MappedSharedBank), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "ID",					TOK_AUTOINT(MappedSharedBank, iID, 0), NULL },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_MappedSharedBank()
{
	int iSize = sizeof(MappedSharedBank);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_MappedSharedBank, iSize, "MappedSharedBank", NULL, "NNOGatewayMailMapping.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
