#ifndef __NNOGATEWAYCRAFTINGMAPPING_H_AST_H_
#define __NNOGATEWAYCRAFTINGMAPPING_H_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \NNOGatewayCraftingMapping.h
//autogeneratednocheckin

extern ParseTable parse_MappedCraftingItem[];
#define TYPE_parse_MappedCraftingItem MappedCraftingItem

extern ParseTable parse_MappedCraftingSlot[];
#define TYPE_parse_MappedCraftingSlot MappedCraftingSlot

extern ParseTable parse_MappedCraftingEntry[];
#define TYPE_parse_MappedCraftingEntry MappedCraftingEntry

extern ParseTable parse_MappedCraftingList[];
#define TYPE_parse_MappedCraftingList MappedCraftingList

extern ParseTable parse_ItemAssignmentGatewaySlotData[];
#define TYPE_parse_ItemAssignmentGatewaySlotData ItemAssignmentGatewaySlotData

extern ParseTable parse_MappedCraftingRewardRank[];
#define TYPE_parse_MappedCraftingRewardRank MappedCraftingRewardRank

extern ParseTable parse_MappedCraftingDetail[];
#define TYPE_parse_MappedCraftingDetail MappedCraftingDetail

extern ParseTable parse_ParamsCraftingList[];
#define TYPE_parse_ParamsCraftingList ParamsCraftingList

extern ParseTable parse_ParamsCraftingDetail[];
#define TYPE_parse_ParamsCraftingDetail ParamsCraftingDetail

#endif
