#ifndef __NNOGATEWAYCOMMONMAPPINGS_H_AST_H_
#define __NNOGATEWAYCOMMONMAPPINGS_H_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \NNOGatewayCommonMappings.h
//autogeneratednocheckin

extern ParseTable parse_MappedPower[];
#define TYPE_parse_MappedPower MappedPower

extern ParseTable parse_MappedGemSlot[];
#define TYPE_parse_MappedGemSlot MappedGemSlot

extern ParseTable parse_MappedInvSlot[];
#define TYPE_parse_MappedInvSlot MappedInvSlot

extern ParseTable parse_MappedInvBag[];
#define TYPE_parse_MappedInvBag MappedInvBag

#endif
