#include "textparser.h"
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct MappedCraftingItem
#define TYPE_parse_MappedCraftingItem MappedCraftingItem
ParseTable parse_MappedCraftingItem[] =
{
	{ "MappedCraftingItem", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MappedCraftingItem), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "hDef",				TOK_REFERENCE(MappedCraftingItem, hDef, 0, "ItemDef") },
	{ "Count",				TOK_AUTOINT(MappedCraftingItem, iCount, 0), NULL },
	{ "Required",			TOK_AUTOINT(MappedCraftingItem, iRequired, 0), NULL },
	{ "FillsRequirements",	TOK_AUTOINT(MappedCraftingItem, bFillsRequirements, -1), NULL },
	{ "uID",				TOK_AUTOINT(MappedCraftingItem, uID, 0), NULL },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_MappedCraftingItem()
{
	int iSize = sizeof(MappedCraftingItem);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_MappedCraftingItem, iSize, "MappedCraftingItem", NULL, "NNOGatewayCraftingMapping.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct MappedCraftingSlot
#define TYPE_parse_MappedCraftingSlot MappedCraftingSlot
ParseTable parse_MappedCraftingSlot[] =
{
	{ "MappedCraftingSlot", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MappedCraftingSlot), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "Icon",				TOK_ESTRING | TOK_STRING(MappedCraftingSlot, pchIcon, 0), NULL },
	{ "FillsRequirements",	TOK_AUTOINT(MappedCraftingSlot, bFillsRequirements, -1), NULL },
	{ "Categories",			TOK_ESTRING | TOK_STRING(MappedCraftingSlot, pchCategories, 0), NULL },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_MappedCraftingSlot()
{
	int iSize = sizeof(MappedCraftingSlot);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_MappedCraftingSlot, iSize, "MappedCraftingSlot", NULL, "NNOGatewayCraftingMapping.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_MappedCraftingSlot[];
#define TYPE_parse_MappedCraftingSlot MappedCraftingSlot
extern ParseTable parse_MappedCraftingItem[];
#define TYPE_parse_MappedCraftingItem MappedCraftingItem
extern ParseTable parse_MappedCraftingItem[];
#define TYPE_parse_MappedCraftingItem MappedCraftingItem
//Structparser.exe autogenerated ParseTable for struct MappedCraftingEntry
#define TYPE_parse_MappedCraftingEntry MappedCraftingEntry
ParseTable parse_MappedCraftingEntry[] =
{
	{ "MappedCraftingEntry", 			TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MappedCraftingEntry), 0, NULL, 0, NULL },
	{ "{",								TOK_START, 0 },
	{ "hDef",							TOK_REFERENCE(MappedCraftingEntry, hDef, 0, "ItemAssignmentDef") },
	{ "FailedRequirementsReasons",		TOK_ESTRING | TOK_STRING(MappedCraftingEntry, pchFailedRequirementsReasons, 0), NULL },
	{ "Header",							TOK_ESTRING | TOK_STRING(MappedCraftingEntry, pchHeader, 0), NULL },
	{ "Required",						TOK_STRUCT(MappedCraftingEntry, ppRequired, parse_MappedCraftingSlot) },
	{ "Consumables",					TOK_STRUCT(MappedCraftingEntry, ppConsumables, parse_MappedCraftingItem) },
	{ "Rewards",						TOK_STRUCT(MappedCraftingEntry, ppRewards, parse_MappedCraftingItem) },
	{ "IsHeader",						TOK_AUTOINT(MappedCraftingEntry, bIsHeader, -1), NULL },
	{ "FailsLevelRequirements",			TOK_AUTOINT(MappedCraftingEntry, bFailsLevelRequirements, -1), NULL },
	{ "FailsLevelRequirementsFilter",	TOK_AUTOINT(MappedCraftingEntry, bFailsLevelRequirementsFilter, -1), NULL },
	{ "FailsResourcesRequirements",		TOK_AUTOINT(MappedCraftingEntry, bFailsResourcesRequirements, -1), NULL },
	{ "uNextUpdateTime",				TOK_AUTOINT(MappedCraftingEntry, uNextUpdateTime, 0), NULL , 0 , "JSON_SECS_TO_RFC822 = 1"},
	{ "}",								TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_MappedCraftingEntry()
{
	int iSize = sizeof(MappedCraftingEntry);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_MappedCraftingEntry, iSize, "MappedCraftingEntry", NULL, "NNOGatewayCraftingMapping.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_DisplayMessage[];
#define TYPE_parse_DisplayMessage DisplayMessage
extern ParseTable parse_MappedCraftingEntry[];
#define TYPE_parse_MappedCraftingEntry MappedCraftingEntry
//Structparser.exe autogenerated ParseTable for struct MappedCraftingList
#define TYPE_parse_MappedCraftingList MappedCraftingList
ParseTable parse_MappedCraftingList[] =
{
	{ "MappedCraftingList", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MappedCraftingList), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "DisplayName",		TOK_EMBEDDEDSTRUCT(MappedCraftingList, DisplayName, parse_DisplayMessage)},
	{ "Entries",			TOK_STRUCT(MappedCraftingList, ppEntries, parse_MappedCraftingEntry) },
	{ "AvailabilityEvent",	TOK_POOL_STRING | TOK_STRING(MappedCraftingList, pchAvailabilityEvent, 0), NULL },
	{ "AvailabilityTime",	TOK_AUTOINT(MappedCraftingList, uAvailabilityTime, 0), NULL , 0 , "JSON_SECS_TO_RFC822 = 1"},
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_MappedCraftingList()
{
	int iSize = sizeof(MappedCraftingList);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_MappedCraftingList, iSize, "MappedCraftingList", NULL, "NNOGatewayCraftingMapping.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_ItemAssignmentSlotUI[];
#define TYPE_parse_ItemAssignmentSlotUI ItemAssignmentSlotUI
extern ParseTable parse_MappedCraftingItem[];
#define TYPE_parse_MappedCraftingItem MappedCraftingItem
//Structparser.exe autogenerated ParseTable for struct ItemAssignmentGatewaySlotData
#define TYPE_parse_ItemAssignmentGatewaySlotData ItemAssignmentGatewaySlotData
ParseTable parse_ItemAssignmentGatewaySlotData[] =
{
	{ "ItemAssignmentGatewaySlotData", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(ItemAssignmentGatewaySlotData), 0, NULL, 0, NULL },
	{ "{",								TOK_START, 0 },
	{ "Slot",							TOK_OPTIONALSTRUCT(ItemAssignmentGatewaySlotData, pSlot, parse_ItemAssignmentSlotUI) },
	{ "Items",							TOK_STRUCT(ItemAssignmentGatewaySlotData, ppItems, parse_MappedCraftingItem) },
	{ "index",							TOK_AUTOINT(ItemAssignmentGatewaySlotData, index, 0), NULL },
	{ "}",								TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_ItemAssignmentGatewaySlotData()
{
	int iSize = sizeof(ItemAssignmentGatewaySlotData);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_ItemAssignmentGatewaySlotData, iSize, "ItemAssignmentGatewaySlotData", NULL, "NNOGatewayCraftingMapping.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_InvRewardRequest[];
#define TYPE_parse_InvRewardRequest InvRewardRequest
extern ParseTable parse_ItemAssignmentOutcomeUI[];
#define TYPE_parse_ItemAssignmentOutcomeUI ItemAssignmentOutcomeUI
//Structparser.exe autogenerated ParseTable for struct MappedCraftingRewardRank
#define TYPE_parse_MappedCraftingRewardRank MappedCraftingRewardRank
ParseTable parse_MappedCraftingRewardRank[] =
{
	{ "MappedCraftingRewardRank", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MappedCraftingRewardRank), 0, NULL, 0, NULL },
	{ "{",							TOK_START, 0 },
	{ "Data",						TOK_OPTIONALSTRUCT(MappedCraftingRewardRank, pData, parse_InvRewardRequest) },
	{ "ChanceData",					TOK_OPTIONALSTRUCT(MappedCraftingRewardRank, pChanceData, parse_ItemAssignmentOutcomeUI) },
	{ "}",							TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_MappedCraftingRewardRank()
{
	int iSize = sizeof(MappedCraftingRewardRank);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_MappedCraftingRewardRank, iSize, "MappedCraftingRewardRank", NULL, "NNOGatewayCraftingMapping.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_MappedCraftingItem[];
#define TYPE_parse_MappedCraftingItem MappedCraftingItem
extern ParseTable parse_ItemAssignmentGatewaySlotData[];
#define TYPE_parse_ItemAssignmentGatewaySlotData ItemAssignmentGatewaySlotData
extern ParseTable parse_ItemAssignmentGatewaySlotData[];
#define TYPE_parse_ItemAssignmentGatewaySlotData ItemAssignmentGatewaySlotData
extern ParseTable parse_MappedCraftingRewardRank[];
#define TYPE_parse_MappedCraftingRewardRank MappedCraftingRewardRank
//Structparser.exe autogenerated ParseTable for struct MappedCraftingDetail
#define TYPE_parse_MappedCraftingDetail MappedCraftingDetail
ParseTable parse_MappedCraftingDetail[] =
{
	{ "MappedCraftingDetail", 		TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MappedCraftingDetail), 0, NULL, 0, NULL },
	{ "{",							TOK_START, 0 },
	{ "hDef",						TOK_REFERENCE(MappedCraftingDetail, hDef, 0, "ItemAssignmentDef") },
	{ "Consumables",				TOK_STRUCT(MappedCraftingDetail, ppConsumables, parse_MappedCraftingItem) },
	{ "Required",					TOK_STRUCT(MappedCraftingDetail, ppRequired, parse_ItemAssignmentGatewaySlotData) },
	{ "Optional",					TOK_STRUCT(MappedCraftingDetail, ppOptional, parse_ItemAssignmentGatewaySlotData) },
	{ "RewardOutcomes",				TOK_STRUCT(MappedCraftingDetail, ppRewardOutcomes, parse_MappedCraftingRewardRank) },
	{ "FailedRequirementsReasons",	TOK_ESTRING | TOK_STRING(MappedCraftingDetail, pchFailedRequirementsReasons, 0), NULL },
	{ "FailsRequirements",			TOK_AUTOINT(MappedCraftingDetail, bFailsRequirements, -1), NULL },
	{ "FailsRequiresReasons",		TOK_AUTOINT(MappedCraftingDetail, eFailsRequiresReasons, 0), ItemAssignmentFailsRequiresReasonEnum },
	{ "SlotRequirement",			TOK_FIXED_ARRAY | TOK_AUTOINTARRAY(MappedCraftingDetail, bfInvalidSlots), NULL },
	{ "Duration",					TOK_AUTOINT(MappedCraftingDetail, uDuration, 0), NULL },
	{ "}",							TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_MappedCraftingDetail()
{
	int iSize = sizeof(MappedCraftingDetail);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_MappedCraftingDetail, iSize, "MappedCraftingDetail", NULL, "NNOGatewayCraftingMapping.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct ParamsCraftingList
#define TYPE_parse_ParamsCraftingList ParamsCraftingList
ParseTable parse_ParamsCraftingList[] =
{
	{ "ParamsCraftingList", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(ParamsCraftingList), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "Empty",				TOK_AUTOINT(ParamsCraftingList, iEmpty, 0), NULL },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_ParamsCraftingList()
{
	int iSize = sizeof(ParamsCraftingList);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_ParamsCraftingList, iSize, "ParamsCraftingList", NULL, "NNOGatewayCraftingMapping.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct ParamsCraftingDetail
#define TYPE_parse_ParamsCraftingDetail ParamsCraftingDetail
ParseTable parse_ParamsCraftingDetail[] =
{
	{ "ParamsCraftingDetail", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(ParamsCraftingDetail), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "Empty",					TOK_AUTOINT(ParamsCraftingDetail, iEmpty, 0), NULL },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_ParamsCraftingDetail()
{
	int iSize = sizeof(ParamsCraftingDetail);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_ParamsCraftingDetail, iSize, "ParamsCraftingDetail", NULL, "NNOGatewayCraftingMapping.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
