#include "textparser.h"

//auto-generated staticdefine for enum DateType
//autogeneratednocheckin
StaticDefineInt DateTypeEnum[] =
{
	DEFINE_INT
	{ "None", DateType_None},
	{ "Today", DateType_Today},
	{ "Past", DateType_Past},
	{ "ThisMonth", DateType_ThisMonth},
	DEFINE_END
};
void autoEnum_fixup_DateType(void)
{
	static bool bOnce = false; if (bOnce) return; bOnce = true;
	RegisterNamedStaticDefine(DateTypeEnum, "DateType");
}
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct MappedGuildEventReply
#define TYPE_parse_MappedGuildEventReply MappedGuildEventReply
ParseTable parse_MappedGuildEventReply[] =
{
	{ "MappedGuildEventReply", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MappedGuildEventReply), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "ID",						TOK_AUTOINT(MappedGuildEventReply, iMemberID, -1), NULL },
	{ "Name",					TOK_ESTRING | TOK_STRING(MappedGuildEventReply, estrName, 0), NULL },
	{ "PublicAccountName",		TOK_ESTRING | TOK_STRING(MappedGuildEventReply, estrPublicAccountName, 0), NULL },
	{ "ReplyType",				TOK_AUTOINT(MappedGuildEventReply, eType, 0), GuildEventReplyTypeEnum },
	{ "ReplyMessage",			TOK_ESTRING | TOK_STRING(MappedGuildEventReply, estrMessage, 0), NULL },
	{ "StartTimeSeconds",		TOK_AUTOINT(MappedGuildEventReply, iStartTime, 0), NULL },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_MappedGuildEventReply()
{
	int iSize = sizeof(MappedGuildEventReply);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_MappedGuildEventReply, iSize, "MappedGuildEventReply", NULL, "NNOGatewayMappedGuild.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_MappedGuildEventReply[];
#define TYPE_parse_MappedGuildEventReply MappedGuildEventReply
//Structparser.exe autogenerated ParseTable for struct MappedGuildEvent
#define TYPE_parse_MappedGuildEvent MappedGuildEvent
ParseTable parse_MappedGuildEvent[] =
{
	{ "MappedGuildEvent", 		TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MappedGuildEvent), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "ID",						TOK_AUTOINT(MappedGuildEvent, uiID, -1), NULL },
	{ "Title",					TOK_ESTRING | TOK_STRING(MappedGuildEvent, estrTitle, 0), NULL },
	{ "Description",			TOK_ESTRING | TOK_STRING(MappedGuildEvent, estrDescription, 0), NULL },
	{ "StartTime",				TOK_ESTRING | TOK_STRING(MappedGuildEvent, estrStartTime, 0), NULL },
	{ "Duration",				TOK_ESTRING | TOK_AUTOINT(MappedGuildEvent, iDuration, 0), NULL },
	{ "RecurrenceFrequency",	TOK_AUTOINT(MappedGuildEvent, iRecurrenceFrequency, 0), NULL },
	{ "RecurrenceCount",		TOK_AUTOINT(MappedGuildEvent, iRecurrenceCount, 0), NULL },
	{ "Canceled",				TOK_AUTOINT(MappedGuildEvent, bCanceled, 0), NULL },
	{ "MinGuildRank",			TOK_ESTRING | TOK_STRING(MappedGuildEvent, estrMinGuildRank, 0), NULL },
	{ "MinGuildEditRank",		TOK_ESTRING | TOK_STRING(MappedGuildEvent, estrMinGuildEditRank, 0), NULL },
	{ "MinLevel",				TOK_AUTOINT(MappedGuildEvent, iMinLevel, 0), NULL },
	{ "MaxLevel",				TOK_AUTOINT(MappedGuildEvent, iMaxLevel, 0), NULL },
	{ "MinAccepts",				TOK_AUTOINT(MappedGuildEvent, iMinAccepts, -1), NULL },
	{ "MaxAccepts",				TOK_AUTOINT(MappedGuildEvent, iMaxAccepts, -1), NULL },
	{ "Replies",				TOK_STRUCT(MappedGuildEvent, eaReplies, parse_MappedGuildEventReply) },
	{ "Accepts",				TOK_AUTOINT(MappedGuildEvent, iAccepts, -1), NULL },
	{ "Maybes",					TOK_AUTOINT(MappedGuildEvent, iMaybes, -1), NULL },
	{ "Refusals",				TOK_AUTOINT(MappedGuildEvent, iRefusals, -1), NULL },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_MappedGuildEvent()
{
	int iSize = sizeof(MappedGuildEvent);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_MappedGuildEvent, iSize, "MappedGuildEvent", NULL, "NNOGatewayMappedGuild.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct MappedGuildEventOccurrence
#define TYPE_parse_MappedGuildEventOccurrence MappedGuildEventOccurrence
ParseTable parse_MappedGuildEventOccurrence[] =
{
	{ "MappedGuildEventOccurrence", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MappedGuildEventOccurrence), 0, NULL, 0, NULL },
	{ "{",							TOK_START, 0 },
	{ "ID",							TOK_AUTOINT(MappedGuildEventOccurrence, uiID, -1), NULL },
	{ "Title",						TOK_ESTRING | TOK_STRING(MappedGuildEventOccurrence, estrTitle, 0), NULL },
	{ "StartTime",					TOK_ESTRING | TOK_STRING(MappedGuildEventOccurrence, estrStartTime, 0), NULL },
	{ "StartTimeSeconds",			TOK_AUTOINT(MappedGuildEventOccurrence, iStartTime, 0), NULL },
	{ "}",							TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_MappedGuildEventOccurrence()
{
	int iSize = sizeof(MappedGuildEventOccurrence);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_MappedGuildEventOccurrence, iSize, "MappedGuildEventOccurrence", NULL, "NNOGatewayMappedGuild.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_MappedGuildEventOccurrence[];
#define TYPE_parse_MappedGuildEventOccurrence MappedGuildEventOccurrence
//Structparser.exe autogenerated ParseTable for struct MappedGuildDay
#define TYPE_parse_MappedGuildDay MappedGuildDay
ParseTable parse_MappedGuildDay[] =
{
	{ "MappedGuildDay", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MappedGuildDay), 0, NULL, 0, NULL },
	{ "{",				TOK_START, 0 },
	{ "Year",			TOK_AUTOINT(MappedGuildDay, iYear, -1), NULL },
	{ "Month",			TOK_AUTOINT(MappedGuildDay, iMonth, -1), NULL },
	{ "Date",			TOK_AUTOINT(MappedGuildDay, iDate, -1), NULL },
	{ "Time",			TOK_AUTOINT(MappedGuildDay, iTime, 0), NULL },
	{ "Type",			TOK_AUTOINT(MappedGuildDay, eDateType, 0), DateTypeEnum },
	{ "Events",			TOK_STRUCT(MappedGuildDay, eaEvents, parse_MappedGuildEventOccurrence) },
	{ "}",				TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_MappedGuildDay()
{
	int iSize = sizeof(MappedGuildDay);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_MappedGuildDay, iSize, "MappedGuildDay", NULL, "NNOGatewayMappedGuild.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_MappedGuildDay[];
#define TYPE_parse_MappedGuildDay MappedGuildDay
//Structparser.exe autogenerated ParseTable for struct MappedGuildWeek
#define TYPE_parse_MappedGuildWeek MappedGuildWeek
ParseTable parse_MappedGuildWeek[] =
{
	{ "MappedGuildWeek", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MappedGuildWeek), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "Days",				TOK_STRUCT(MappedGuildWeek, eaDays, parse_MappedGuildDay) },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_MappedGuildWeek()
{
	int iSize = sizeof(MappedGuildWeek);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_MappedGuildWeek, iSize, "MappedGuildWeek", NULL, "NNOGatewayMappedGuild.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_MappedGuildWeek[];
#define TYPE_parse_MappedGuildWeek MappedGuildWeek
//Structparser.exe autogenerated ParseTable for struct MappedGuildCalendar
#define TYPE_parse_MappedGuildCalendar MappedGuildCalendar
ParseTable parse_MappedGuildCalendar[] =
{
	{ "MappedGuildCalendar", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MappedGuildCalendar), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "Weeks",					TOK_STRUCT(MappedGuildCalendar, eaWeeks, parse_MappedGuildWeek) },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_MappedGuildCalendar()
{
	int iSize = sizeof(MappedGuildCalendar);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_MappedGuildCalendar, iSize, "MappedGuildCalendar", NULL, "NNOGatewayMappedGuild.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct MappedGuildActivityLogEntry
#define TYPE_parse_MappedGuildActivityLogEntry MappedGuildActivityLogEntry
ParseTable parse_MappedGuildActivityLogEntry[] =
{
	{ "MappedGuildActivityLogEntry", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MappedGuildActivityLogEntry), 0, NULL, 0, NULL },
	{ "{",								TOK_START, 0 },
	{ "Time",							TOK_ESTRING | TOK_STRING(MappedGuildActivityLogEntry, estrTime, 0), NULL },
	{ "Type",							TOK_ESTRING | TOK_STRING(MappedGuildActivityLogEntry, estrType, 0), NULL },
	{ "String",							TOK_ESTRING | TOK_STRING(MappedGuildActivityLogEntry, estrString, 0), NULL },
	{ "}",								TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_MappedGuildActivityLogEntry()
{
	int iSize = sizeof(MappedGuildActivityLogEntry);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_MappedGuildActivityLogEntry, iSize, "MappedGuildActivityLogEntry", NULL, "NNOGatewayMappedGuild.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct MappedGuildCustomRank
#define TYPE_parse_MappedGuildCustomRank MappedGuildCustomRank
ParseTable parse_MappedGuildCustomRank[] =
{
	{ "MappedGuildCustomRank", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MappedGuildCustomRank), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "Name",					TOK_ESTRING | TOK_STRING(MappedGuildCustomRank, estrName, 0), NULL },
	{ "Rank",					TOK_AUTOINT(MappedGuildCustomRank, iRank, 0), NULL },
	{ "Permissions",			TOK_AUTOINT(MappedGuildCustomRank, ePerms, 0), GuildRankPermissionsEnum  ,  TOK_FORMAT_FLAGS},
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_MappedGuildCustomRank()
{
	int iSize = sizeof(MappedGuildCustomRank);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_MappedGuildCustomRank, iSize, "MappedGuildCustomRank", NULL, "NNOGatewayMappedGuild.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct MappedGuildMember
#define TYPE_parse_MappedGuildMember MappedGuildMember
ParseTable parse_MappedGuildMember[] =
{
	{ "MappedGuildMember", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MappedGuildMember), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "id",					TOK_AUTOINT(MappedGuildMember, id, 0), NULL },
	{ "Name",				TOK_ESTRING | TOK_STRING(MappedGuildMember, estrName, 0), NULL },
	{ "Joined",				TOK_ESTRING | TOK_STRING(MappedGuildMember, estrJoined, 0), NULL },
	{ "PublicAccountName",	TOK_ESTRING | TOK_STRING(MappedGuildMember, estrPublicAccountName, 0), NULL },
	{ "Status",				TOK_ESTRING | TOK_STRING(MappedGuildMember, estrStatus, 0), NULL },
	{ "Level",				TOK_AUTOINT(MappedGuildMember, iLevel, 0), NULL },
	{ "PublicComment",		TOK_ESTRING | TOK_STRING(MappedGuildMember, estrPublicComment, 0), NULL },
	{ "OfficerComment",		TOK_ESTRING | TOK_STRING(MappedGuildMember, estrOfficerComment, 0), NULL },
	{ "ClassType",			TOK_ESTRING | TOK_STRING(MappedGuildMember, estrClassType, 0), NULL },
	{ "Rank",				TOK_AUTOINT(MappedGuildMember, iRank, 0), NULL },
	{ "OfficerRank",		TOK_ESTRING | TOK_STRING(MappedGuildMember, estrOfficerRank, 0), NULL },
	{ "GuildContribution1",	TOK_AUTOINT(MappedGuildMember, iGuildContribution1, 0), NULL },
	{ "GuildContribution2",	TOK_AUTOINT(MappedGuildMember, iGuildContribution2, 0), NULL },
	{ "Location",			TOK_ESTRING | TOK_STRING(MappedGuildMember, estrLocation, 0), NULL },
	{ "LogoutTime",			TOK_ESTRING | TOK_STRING(MappedGuildMember, estrLogoutTime, 0), NULL },
	{ "LFG",				TOK_AUTOINT(MappedGuildMember, eLFG, 0), TeamModeEnum },
	{ "Online",				TOK_AUTOINT(MappedGuildMember, bOnline, 0), NULL },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_MappedGuildMember()
{
	int iSize = sizeof(MappedGuildMember);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_MappedGuildMember, iSize, "MappedGuildMember", NULL, "NNOGatewayMappedGuild.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_MappedGuildCustomRank[];
#define TYPE_parse_MappedGuildCustomRank MappedGuildCustomRank
extern ParseTable parse_MappedGuildMember[];
#define TYPE_parse_MappedGuildMember MappedGuildMember
extern ParseTable parse_MappedGuildActivityLogEntry[];
#define TYPE_parse_MappedGuildActivityLogEntry MappedGuildActivityLogEntry
extern ParseTable parse_MappedGuildCalendar[];
#define TYPE_parse_MappedGuildCalendar MappedGuildCalendar
extern ParseTable parse_MappedGuildEvent[];
#define TYPE_parse_MappedGuildEvent MappedGuildEvent
//Structparser.exe autogenerated ParseTable for struct MappedGuild
#define TYPE_parse_MappedGuild MappedGuild
ParseTable parse_MappedGuild[] =
{
	{ "MappedGuild", 		TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MappedGuild), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "id",					TOK_AUTOINT(MappedGuild, id, 0), NULL },
	{ "ViewerIsMember",		TOK_AUTOINT(MappedGuild, bViewerIsMember, 0), NULL },
	{ "Name",				TOK_ESTRING | TOK_STRING(MappedGuild, estrName, 0), NULL },
	{ "CreatedOn",			TOK_ESTRING | TOK_STRING(MappedGuild, estrCreatedOn, 0), NULL },
	{ "MotD",				TOK_ESTRING | TOK_STRING(MappedGuild, estrMotD, 0), NULL },
	{ "Description",		TOK_ESTRING | TOK_STRING(MappedGuild, estrDescription, 0), NULL },
	{ "Website",			TOK_ESTRING | TOK_STRING(MappedGuild, estrWebsite, 0), NULL },
	{ "RecruitMessage",		TOK_ESTRING | TOK_STRING(MappedGuild, estrRecruitMessage, 0), NULL },
	{ "MinLevelRecruit",	TOK_AUTOINT(MappedGuild, iMinLevelRecruit, 0), NULL },
	{ "Ranks",				TOK_STRUCT(MappedGuild, eaRanks, parse_MappedGuildCustomRank) },
	{ "Members",			TOK_STRUCT(MappedGuild, eaMembers, parse_MappedGuildMember) },
	{ "TotalMembers",		TOK_AUTOINT(MappedGuild, iTotalMembers, 0), NULL },
	{ "ActivityEntries",	TOK_STRUCT(MappedGuild, eaEntries, parse_MappedGuildActivityLogEntry) },
	{ "Calendar",			TOK_OPTIONALSTRUCT(MappedGuild, pCalendar, parse_MappedGuildCalendar) },
	{ "Events",				TOK_STRUCT(MappedGuild, eaEvents, parse_MappedGuildEvent) },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_MappedGuild()
{
	int iSize = sizeof(MappedGuild);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_MappedGuild, iSize, "MappedGuild", NULL, "NNOGatewayMappedGuild.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
