#ifndef __NNOGATEWAYGAMEMAPPING_H_AST_H_
#define __NNOGATEWAYGAMEMAPPING_H_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \NNOGatewayGameMapping.h
//autogeneratednocheckin

extern ParseTable parse_MappedRewardBag[];
#define TYPE_parse_MappedRewardBag MappedRewardBag

extern ParseTable parse_MappedSCP[];
#define TYPE_parse_MappedSCP MappedSCP

extern ParseTable parse_MappedSCA[];
#define TYPE_parse_MappedSCA MappedSCA

extern ParseTable parse_MappedGatewayGameData[];
#define TYPE_parse_MappedGatewayGameData MappedGatewayGameData

#endif
