#ifndef __NNOGATEWAYMAILMAPPING_H_AST_H_
#define __NNOGATEWAYMAILMAPPING_H_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \NNOGatewayMailMapping.h
//autogeneratednocheckin

extern ParseTable parse_MappedMailHeader[];
#define TYPE_parse_MappedMailHeader MappedMailHeader

extern ParseTable parse_MappedMailList[];
#define TYPE_parse_MappedMailList MappedMailList

extern ParseTable parse_MappedMailItem[];
#define TYPE_parse_MappedMailItem MappedMailItem

extern ParseTable parse_MappedMailBody[];
#define TYPE_parse_MappedMailBody MappedMailBody

extern ParseTable parse_MappedMailDetail[];
#define TYPE_parse_MappedMailDetail MappedMailDetail

extern ParseTable parse_MappedSharedBank[];
#define TYPE_parse_MappedSharedBank MappedSharedBank

#endif
