#include "textparser.h"
//autogeneratednocheckin
extern ParseTable parse_MappedInvSlot[];
#define TYPE_parse_MappedInvSlot MappedInvSlot
//Structparser.exe autogenerated ParseTable for struct MappedRewardBag
#define TYPE_parse_MappedRewardBag MappedRewardBag
ParseTable parse_MappedRewardBag[] =
{
	{ "MappedRewardBag", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MappedRewardBag), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "Rewards",			TOK_STRUCT(MappedRewardBag, ppSlots, parse_MappedInvSlot) },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_MappedRewardBag()
{
	int iSize = sizeof(MappedRewardBag);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_MappedRewardBag, iSize, "MappedRewardBag", NULL, "NNOGatewayGameMapping.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct MappedSCP
#define TYPE_parse_MappedSCP MappedSCP
ParseTable parse_MappedSCP[] =
{
	{ "MappedSCP", 			TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MappedSCP), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "ItemName",			TOK_REFERENCE(MappedSCP, hItemName, 0, "Message") },
	{ "ID",					TOK_AUTOINT(MappedSCP, uID, 0), NULL },
	{ "Quality",			TOK_AUTOINT(MappedSCP, eQuality, 0), ItemQualityEnum },
	{ "Name",				TOK_STRING(MappedSCP, pchName, 0), NULL },
	{ "XP",					TOK_AUTOINT(MappedSCP, uXP, 0), NULL },
	{ "Level",				TOK_AUTOINT(MappedSCP, uLevel, 0), NULL },
	{ "LastLevel",			TOK_AUTOINT(MappedSCP, uLastLevel, 0), NULL },
	{ "NextLevel",			TOK_AUTOINT(MappedSCP, uNextLevel, 0), NULL },
	{ "NextXP",				TOK_AUTOINT(MappedSCP, uXPNextLevel, 0), NULL },
	{ "LastXP",				TOK_AUTOINT(MappedSCP, uXPLastLevel, 0), NULL },
	{ "Costume",			TOK_POOL_STRING | TOK_STRING(MappedSCP, pchCostume, 0), NULL },
	{ "SCPDef",				TOK_REFERENCE(MappedSCP, hSCPDef, 0, "SuperCritterPetDef") },
	{ "TrainingEndTime",	TOK_AUTOINT(MappedSCP, uTrainingEndTime, 0), NULL , 0 , "JSON_SECS_TO_RFC822 = 1"},
	{ "isTraining",			TOK_AUTOINT(MappedSCP, bTraining, 0), NULL },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_MappedSCP()
{
	int iSize = sizeof(MappedSCP);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_MappedSCP, iSize, "MappedSCP", NULL, "NNOGatewayGameMapping.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_MappedSCP[];
#define TYPE_parse_MappedSCP MappedSCP
extern ParseTable parse_MappedRewardBag[];
#define TYPE_parse_MappedRewardBag MappedRewardBag
extern ParseTable parse_MappedRewardBag[];
#define TYPE_parse_MappedRewardBag MappedRewardBag
extern ParseTable parse_MappedRewardBag[];
#define TYPE_parse_MappedRewardBag MappedRewardBag
//Structparser.exe autogenerated ParseTable for struct MappedSCA
#define TYPE_parse_MappedSCA MappedSCA
ParseTable parse_MappedSCA[] =
{
	{ "MappedSCA", 				TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MappedSCA), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "Companions",				TOK_STRUCT(MappedSCA, ppCritterPets, parse_MappedSCP) },
	{ "QueuedRewardBag",		TOK_OPTIONALSTRUCT(MappedSCA, pQueuedRewardBag, parse_MappedRewardBag) },
	{ "LastQueuedRewardBag",	TOK_OPTIONALSTRUCT(MappedSCA, pLastQueuedRewardBag, parse_MappedRewardBag) },
	{ "LastRewardBag",			TOK_OPTIONALSTRUCT(MappedSCA, pLastRewardBag, parse_MappedRewardBag) },
	{ "SaveState",				TOK_STRING(MappedSCA, pchSaveState, 0), NULL },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_MappedSCA()
{
	int iSize = sizeof(MappedSCA);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_MappedSCA, iSize, "MappedSCA", NULL, "NNOGatewayGameMapping.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_MappedSCA[];
#define TYPE_parse_MappedSCA MappedSCA
//Structparser.exe autogenerated ParseTable for struct MappedGatewayGameData
#define TYPE_parse_MappedGatewayGameData MappedGatewayGameData
ParseTable parse_MappedGatewayGameData[] =
{
	{ "MappedGatewayGameData", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MappedGatewayGameData), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "SCA",					TOK_OPTIONALSTRUCT(MappedGatewayGameData, pSCA, parse_MappedSCA) },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_MappedGatewayGameData()
{
	int iSize = sizeof(MappedGatewayGameData);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_MappedGatewayGameData, iSize, "MappedGatewayGameData", NULL, "NNOGatewayGameMapping.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
