#ifndef __NNOGATEWAYEXCHANGEMAPPING_H_AST_H_
#define __NNOGATEWAYEXCHANGEMAPPING_H_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \NNOGatewayExchangeMapping.h
//autogeneratednocheckin

extern ParseTable parse_MappedExchangeOpenOrder[];
#define TYPE_parse_MappedExchangeOpenOrder MappedExchangeOpenOrder

extern ParseTable parse_MappedExchangeLogEntry[];
#define TYPE_parse_MappedExchangeLogEntry MappedExchangeLogEntry

extern ParseTable parse_MappedExchangeAccountData[];
#define TYPE_parse_MappedExchangeAccountData MappedExchangeAccountData

#endif
