#include "textparser.h"
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct MappedPower
#define TYPE_parse_MappedPower MappedPower
ParseTable parse_MappedPower[] =
{
	{ "MappedPower", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MappedPower), 0, NULL, 0, NULL },
	{ "{",				TOK_START, 0 },
	{ "PowerDef",		TOK_REFERENCE(MappedPower, hPowerDef, 0, "PowerDef") },
	{ "}",				TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_MappedPower()
{
	int iSize = sizeof(MappedPower);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_MappedPower, iSize, "MappedPower", NULL, "NNOGatewayCommonMappings.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct MappedGemSlot
#define TYPE_parse_MappedGemSlot MappedGemSlot
ParseTable parse_MappedGemSlot[] =
{
	{ "MappedGemSlot", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MappedGemSlot), 0, NULL, 0, NULL },
	{ "{",				TOK_START, 0 },
	{ "TYPE",			TOK_STRUCTPARAM | TOK_AUTOINT(MappedGemSlot, eType, 0), ItemGemTypeEnum  ,  TOK_FORMAT_FLAGS},
	{ "Filled",			TOK_AUTOINT(MappedGemSlot, bFilled, -1), NULL },
	{ "}",				TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_MappedGemSlot()
{
	int iSize = sizeof(MappedGemSlot);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_MappedGemSlot, iSize, "MappedGemSlot", NULL, "NNOGatewayCommonMappings.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_MappedPower[];
#define TYPE_parse_MappedPower MappedPower
extern ParseTable parse_MappedGemSlot[];
#define TYPE_parse_MappedGemSlot MappedGemSlot
//Structparser.exe autogenerated ParseTable for struct MappedInvSlot
#define TYPE_parse_MappedInvSlot MappedInvSlot
ParseTable parse_MappedInvSlot[] =
{
	{ "MappedInvSlot", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MappedInvSlot), 0, NULL, 0, NULL },
	{ "{",				TOK_START, 0 },
	{ "Count",			TOK_AUTOINT(MappedInvSlot, count, 0), NULL },
	{ "Name",			TOK_ESTRING | TOK_STRING(MappedInvSlot, estrName, 0), NULL },
	{ "ItemDef",		TOK_REFERENCE(MappedInvSlot, hItemDef, 0, "ItemDef") },
	{ "Powers",			TOK_STRUCT(MappedInvSlot, ppPowers, parse_MappedPower) },
	{ "Rarity",			TOK_AUTOINT(MappedInvSlot, Quality, kItemQuality_None), ItemQualityEnum },
	{ "BoundToAccount",	TOK_AUTOINT(MappedInvSlot, bBoundToAccount, -1), NULL },
	{ "Bound",			TOK_AUTOINT(MappedInvSlot, bBound, -1), NULL },
	{ "Sellable",		TOK_AUTOINT(MappedInvSlot, bSellable, -1), NULL },
	{ "Discardable",	TOK_AUTOINT(MappedInvSlot, bDiscardable, -1), NULL },
	{ "IsUsable",		TOK_AUTOINT(MappedInvSlot, bIsUsable, -1), NULL },
	{ "HasClass",		TOK_AUTOINT(MappedInvSlot, bHasClass, -1), NULL },
	{ "MeetsLevel",		TOK_AUTOINT(MappedInvSlot, bMeetsLevelRequirements, -1), NULL },
	{ "MeetsExpr",		TOK_AUTOINT(MappedInvSlot, bMeetsExpressionRequirements, -1), NULL },
	{ "IsNew",			TOK_AUTOINT(MappedInvSlot, bIsNew, -1), NULL },
	{ "BoundText",		TOK_ESTRING | TOK_STRING(MappedInvSlot, esBoundText, 0), NULL },
	{ "SortText",		TOK_ESTRING | TOK_STRING(MappedInvSlot, esSortText, 0), NULL },
	{ "RareText",		TOK_ESTRING | TOK_STRING(MappedInvSlot, esRareText, 0), NULL },
	{ "Value",			TOK_AUTOINT(MappedInvSlot, iValue, -1), NULL },
	{ "uID",			TOK_AUTOINT(MappedInvSlot, uID, 0), NULL },
	{ "GemSlots",		TOK_STRUCT(MappedInvSlot, ppGemSlots, parse_MappedGemSlot) },
	{ "}",				TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_MappedInvSlot()
{
	int iSize = sizeof(MappedInvSlot);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_MappedInvSlot, iSize, "MappedInvSlot", NULL, "NNOGatewayCommonMappings.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_MappedInvSlot[];
#define TYPE_parse_MappedInvSlot MappedInvSlot
//Structparser.exe autogenerated ParseTable for struct MappedInvBag
#define TYPE_parse_MappedInvBag MappedInvBag
ParseTable parse_MappedInvBag[] =
{
	{ "MappedInvBag", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MappedInvBag), 0, NULL, 0, NULL },
	{ "{",				TOK_START, 0 },
	{ "BagID",			TOK_AUTOINT(MappedInvBag, BagID, 0), InvBagIDsEnum },
	{ "Name",			TOK_ESTRING | TOK_STRING(MappedInvBag, estrName, 0), NULL },
	{ "Icon",			TOK_ESTRING | TOK_STRING(MappedInvBag, estrIcon, 0), NULL },
	{ "Slots",			TOK_STRUCT(MappedInvBag, ppSlots, parse_MappedInvSlot) },
	{ "}",				TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_MappedInvBag()
{
	int iSize = sizeof(MappedInvBag);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_MappedInvBag, iSize, "MappedInvBag", NULL, "NNOGatewayCommonMappings.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
