//This file contains data and prototypes for latelinks. It is autogenerated by StructParser

//autogeneratednocheckin
#include "LateLinkSupport.h"

//Stuff relating to LATELINK_OVERRIDE_ContainerMappingInit(), defined in I:\Night\Night\src\Night\GameServer\Gateway\NNOGatewayContainerMapping.c
extern void OVERRIDE_LATELINK_ContainerMappingInit(void);
typedef void ContainerMappingInit_LATELINK_FPTYPE_INTERNAL(void);
extern ContainerMappingInit_LATELINK_FPTYPE_INTERNAL *ContainerMappingInit_LATELINK_FP;
extern char *ContainerMappingInit_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_ContainerMappingInit(void)
{
	ContainerMappingInit_LATELINK_FP = OVERRIDE_LATELINK_ContainerMappingInit;
	TestLateLinkArgString(&ContainerMappingInit_LATELINK_ARGSTRING, "void ", "ContainerMappingInit");
}

//Stuff relating to LATELINK declaration for GameSpecific_CaptainCostumeFixup(), defined in I:\Night\Night\src\Night\GameServer\..\..\CrossRoads\Common\Entity\Entity.h
extern char *GameSpecific_CaptainCostumeFixup_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__Entity_h_NNOGameServer_3_GameSpecific_CaptainCostumeFixup(void)
{
	TestLateLinkArgString(&GameSpecific_CaptainCostumeFixup_LATELINK_ARGSTRING, "void Entity * ", "GameSpecific_CaptainCostumeFixup");
}

//Stuff relating to LATELINK declaration for GameSpecific_CreateShieldFX(), defined in I:\Night\Night\src\Night\GameServer\..\..\CrossRoads\Common\Entity\Entity.h
extern char *GameSpecific_CreateShieldFX_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__Entity_h_NNOGameServer_2_GameSpecific_CreateShieldFX(void)
{
	TestLateLinkArgString(&GameSpecific_CreateShieldFX_LATELINK_ARGSTRING, "void Entity * ", "GameSpecific_CreateShieldFX");
}

//Stuff relating to LATELINK declaration for GameSpecific_HandleInventoryChangeNumeric(), defined in I:\Night\Night\src\Night\GameServer\..\..\CrossRoads\Common\item\itemCommon.h
extern char *GameSpecific_HandleInventoryChangeNumeric_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__itemCommon_h_NNOGameServer_0_GameSpecific_HandleInventoryChangeNumeric(void)
{
	TestLateLinkArgString(&GameSpecific_HandleInventoryChangeNumeric_LATELINK_ARGSTRING, "void Entity * const char * bool ", "GameSpecific_HandleInventoryChangeNumeric");
}

//Stuff relating to LATELINK declaration for GameSpecific_HolsterRequest(), defined in I:\Night\Night\src\Night\GameServer\..\..\CrossRoads\Common\Entity\Entity.h
extern char *GameSpecific_HolsterRequest_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__Entity_h_NNOGameServer_1_GameSpecific_HolsterRequest(void)
{
	TestLateLinkArgString(&GameSpecific_HolsterRequest_LATELINK_ARGSTRING, "void Entity * Entity * bool ", "GameSpecific_HolsterRequest");
}

//Stuff relating to LATELINK_OVERRIDE_GatewayEntityTick(), defined in I:\Night\Night\src\Night\GameServer\Gateway\NNOGatewayContainerMapping.c
extern void OVERRIDE_LATELINK_GatewayEntityTick(void* arg0);
typedef void GatewayEntityTick_LATELINK_FPTYPE_INTERNAL(void* arg0);
extern GatewayEntityTick_LATELINK_FPTYPE_INTERNAL *GatewayEntityTick_LATELINK_FP;
extern char *GatewayEntityTick_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_GatewayEntityTick(void)
{
	GatewayEntityTick_LATELINK_FP = OVERRIDE_LATELINK_GatewayEntityTick;
	TestLateLinkArgString(&GatewayEntityTick_LATELINK_ARGSTRING, "void Entity * ", "GatewayEntityTick");
}

//Stuff relating to LATELINK_OVERRIDE_GatewayVendor_GetContactDef(), defined in I:\Night\Night\src\Night\GameServer\Gateway\NNOGatewayVendor.c
extern void* OVERRIDE_LATELINK_GatewayVendor_GetContactDef(void* arg0);
typedef void* GatewayVendor_GetContactDef_LATELINK_FPTYPE_INTERNAL(void* arg0);
extern GatewayVendor_GetContactDef_LATELINK_FPTYPE_INTERNAL *GatewayVendor_GetContactDef_LATELINK_FP;
extern char *GatewayVendor_GetContactDef_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_GatewayVendor_GetContactDef(void)
{
	GatewayVendor_GetContactDef_LATELINK_FP = OVERRIDE_LATELINK_GatewayVendor_GetContactDef;
	TestLateLinkArgString(&GatewayVendor_GetContactDef_LATELINK_ARGSTRING, "ContactDef * const char * ", "GatewayVendor_GetContactDef");
}

//Stuff relating to LATELINK_OVERRIDE_GetContainerMappings(), defined in I:\Night\Night\src\Night\GameServer\Gateway\NNOGatewayContainerMapping.c
extern void* OVERRIDE_LATELINK_GetContainerMappings(void);
typedef void* GetContainerMappings_LATELINK_FPTYPE_INTERNAL(void);
extern GetContainerMappings_LATELINK_FPTYPE_INTERNAL *GetContainerMappings_LATELINK_FP;
extern char *GetContainerMappings_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_GetContainerMappings(void)
{
	GetContainerMappings_LATELINK_FP = OVERRIDE_LATELINK_GetContainerMappings;
	TestLateLinkArgString(&GetContainerMappings_LATELINK_ARGSTRING, "ContainerMapping * ", "GetContainerMappings");
}

//Stuff relating to LATELINK_OVERRIDE_GetItemInfoComparedSMF(), defined in I:\Night\Night\src\Night\GameServer\Gateway\NNOGatewayItemDescription.c
extern void OVERRIDE_LATELINK_GetItemInfoComparedSMF(void** arg0, Language arg1, void* arg2, void* arg3, S32 arg4);
typedef void GetItemInfoComparedSMF_LATELINK_FPTYPE_INTERNAL(void** arg0, Language arg1, void* arg2, void* arg3, S32 arg4);
extern GetItemInfoComparedSMF_LATELINK_FPTYPE_INTERNAL *GetItemInfoComparedSMF_LATELINK_FP;
extern char *GetItemInfoComparedSMF_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_GetItemInfoComparedSMF(void)
{
	GetItemInfoComparedSMF_LATELINK_FP = OVERRIDE_LATELINK_GetItemInfoComparedSMF;
	TestLateLinkArgString(&GetItemInfoComparedSMF_LATELINK_ARGSTRING, "void char * * Language Item * Entity * S32 ", "GetItemInfoComparedSMF");
}

//Stuff relating to LATELINK_OVERRIDE_GetStructMappings(), defined in I:\Night\Night\src\Night\GameServer\Gateway\NNOGatewayStructMapping.c
extern void* OVERRIDE_LATELINK_GetStructMappings(void);
typedef void* GetStructMappings_LATELINK_FPTYPE_INTERNAL(void);
extern GetStructMappings_LATELINK_FPTYPE_INTERNAL *GetStructMappings_LATELINK_FP;
extern char *GetStructMappings_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_GetStructMappings(void)
{
	GetStructMappings_LATELINK_FP = OVERRIDE_LATELINK_GetStructMappings;
	TestLateLinkArgString(&GetStructMappings_LATELINK_ARGSTRING, "StructMapping * ", "GetStructMappings");
}

//Stuff relating to LATELINK_OVERRIDE_ProdSpecificGlobalConfigSetup(), defined in I:\Night\Night\src\Night\GameServer\..\Common\NNOCommon.c
extern void OVERRIDE_LATELINK_ProdSpecificGlobalConfigSetup(void);
typedef void ProdSpecificGlobalConfigSetup_LATELINK_FPTYPE_INTERNAL(void);
extern ProdSpecificGlobalConfigSetup_LATELINK_FPTYPE_INTERNAL *ProdSpecificGlobalConfigSetup_LATELINK_FP;
extern char *ProdSpecificGlobalConfigSetup_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_ProdSpecificGlobalConfigSetup(void)
{
	ProdSpecificGlobalConfigSetup_LATELINK_FP = OVERRIDE_LATELINK_ProdSpecificGlobalConfigSetup;
	TestLateLinkArgString(&ProdSpecificGlobalConfigSetup_LATELINK_ARGSTRING, "void ", "ProdSpecificGlobalConfigSetup");
}

//Stuff relating to LATELINK_OVERRIDE_UserExp_ShouldLogThisUser(), defined in I:\Night\Night\src\Night\GameServer\NNOGameServer.c
extern bool OVERRIDE_LATELINK_UserExp_ShouldLogThisUser(void* arg0);
typedef bool UserExp_ShouldLogThisUser_LATELINK_FPTYPE_INTERNAL(void* arg0);
extern UserExp_ShouldLogThisUser_LATELINK_FPTYPE_INTERNAL *UserExp_ShouldLogThisUser_LATELINK_FP;
extern char *UserExp_ShouldLogThisUser_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_UserExp_ShouldLogThisUser(void)
{
	UserExp_ShouldLogThisUser_LATELINK_FP = OVERRIDE_LATELINK_UserExp_ShouldLogThisUser;
	TestLateLinkArgString(&UserExp_ShouldLogThisUser_LATELINK_ARGSTRING, "bool Entity * ", "UserExp_ShouldLogThisUser");
}

//Stuff relating to LATELINK_OVERRIDE_ent_FixupProjectSpecificPowers(), defined in I:\Night\Night\src\Night\GameServer\NNOFixup.c
extern void OVERRIDE_LATELINK_ent_FixupProjectSpecificPowers(void* arg0);
typedef void ent_FixupProjectSpecificPowers_LATELINK_FPTYPE_INTERNAL(void* arg0);
extern ent_FixupProjectSpecificPowers_LATELINK_FPTYPE_INTERNAL *ent_FixupProjectSpecificPowers_LATELINK_FP;
extern char *ent_FixupProjectSpecificPowers_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_ent_FixupProjectSpecificPowers(void)
{
	ent_FixupProjectSpecificPowers_LATELINK_FP = OVERRIDE_LATELINK_ent_FixupProjectSpecificPowers;
	TestLateLinkArgString(&ent_FixupProjectSpecificPowers_LATELINK_ARGSTRING, "void Entity * ", "ent_FixupProjectSpecificPowers");
}

//Stuff relating to LATELINK_OVERRIDE_ent_NeedsProjectSpecificPowersFixup(), defined in I:\Night\Night\src\Night\GameServer\NNOFixup.c
extern bool OVERRIDE_LATELINK_ent_NeedsProjectSpecificPowersFixup(void* arg0);
typedef bool ent_NeedsProjectSpecificPowersFixup_LATELINK_FPTYPE_INTERNAL(void* arg0);
extern ent_NeedsProjectSpecificPowersFixup_LATELINK_FPTYPE_INTERNAL *ent_NeedsProjectSpecificPowersFixup_LATELINK_FP;
extern char *ent_NeedsProjectSpecificPowersFixup_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_ent_NeedsProjectSpecificPowersFixup(void)
{
	ent_NeedsProjectSpecificPowersFixup_LATELINK_FP = OVERRIDE_LATELINK_ent_NeedsProjectSpecificPowersFixup;
	TestLateLinkArgString(&ent_NeedsProjectSpecificPowersFixup_LATELINK_ARGSTRING, "bool Entity * ", "ent_NeedsProjectSpecificPowersFixup");
}

//Stuff relating to LATELINK declaration for entity_CreateProjSpecificLogString(), defined in I:\Night\Night\src\Night\GameServer\..\..\CrossRoads\Common\Entity\Entity.h
extern char *entity_CreateProjSpecificLogString_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__Entity_h_NNOGameServer_0_entity_CreateProjSpecificLogString(void)
{
	TestLateLinkArgString(&entity_CreateProjSpecificLogString_LATELINK_ARGSTRING, "char * Entity * ", "entity_CreateProjSpecificLogString");
}

//Stuff relating to LATELINK_OVERRIDE_entity_CreateProjSpecificLogString(), defined in I:\Night\Night\src\Night\GameServer\NNOLogging.c
extern void* OVERRIDE_LATELINK_entity_CreateProjSpecificLogString(void* arg0);
typedef void* entity_CreateProjSpecificLogString_LATELINK_FPTYPE_INTERNAL(void* arg0);
extern entity_CreateProjSpecificLogString_LATELINK_FPTYPE_INTERNAL *entity_CreateProjSpecificLogString_LATELINK_FP;
extern char *entity_CreateProjSpecificLogString_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_entity_CreateProjSpecificLogString(void)
{
	entity_CreateProjSpecificLogString_LATELINK_FP = OVERRIDE_LATELINK_entity_CreateProjSpecificLogString;
	TestLateLinkArgString(&entity_CreateProjSpecificLogString_LATELINK_ARGSTRING, "char * Entity * ", "entity_CreateProjSpecificLogString");
}

//Stuff relating to LATELINK declaration for gameSpecificFixup(), defined in I:\Night\Night\src\Night\GameServer\..\..\CrossRoads\Common\Entity\Entity.h
extern char *gameSpecificFixup_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__Entity_h_NNOGameServer_4_gameSpecificFixup(void)
{
	TestLateLinkArgString(&gameSpecificFixup_LATELINK_ARGSTRING, "void Entity * ", "gameSpecificFixup");
}

//Stuff relating to LATELINK_OVERRIDE_gameSpecificFixup(), defined in I:\Night\Night\src\Night\GameServer\NNOFixup.c
extern void OVERRIDE_LATELINK_gameSpecificFixup(void* arg0);
typedef void gameSpecificFixup_LATELINK_FPTYPE_INTERNAL(void* arg0);
extern gameSpecificFixup_LATELINK_FPTYPE_INTERNAL *gameSpecificFixup_LATELINK_FP;
extern char *gameSpecificFixup_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_gameSpecificFixup(void)
{
	gameSpecificFixup_LATELINK_FP = OVERRIDE_LATELINK_gameSpecificFixup;
	TestLateLinkArgString(&gameSpecificFixup_LATELINK_ARGSTRING, "void Entity * ", "gameSpecificFixup");
}

//Stuff relating to LATELINK declaration for gameSpecificFixup_Version(), defined in I:\Night\Night\src\Night\GameServer\..\..\CrossRoads\Common\Entity\Entity.h
extern char *gameSpecificFixup_Version_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__Entity_h_NNOGameServer_5_gameSpecificFixup_Version(void)
{
	TestLateLinkArgString(&gameSpecificFixup_Version_LATELINK_ARGSTRING, "int ", "gameSpecificFixup_Version");
}

//Stuff relating to LATELINK_OVERRIDE_gameSpecificFixup_Version(), defined in I:\Night\Night\src\Night\GameServer\..\Common\NNOCommon.c
extern int OVERRIDE_LATELINK_gameSpecificFixup_Version(void);
typedef int gameSpecificFixup_Version_LATELINK_FPTYPE_INTERNAL(void);
extern gameSpecificFixup_Version_LATELINK_FPTYPE_INTERNAL *gameSpecificFixup_Version_LATELINK_FP;
extern char *gameSpecificFixup_Version_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_gameSpecificFixup_Version(void)
{
	gameSpecificFixup_Version_LATELINK_FP = OVERRIDE_LATELINK_gameSpecificFixup_Version;
	TestLateLinkArgString(&gameSpecificFixup_Version_LATELINK_ARGSTRING, "int ", "gameSpecificFixup_Version");
}

//Stuff relating to LATELINK declaration for gameSpecificPreLoginFixup_Version(), defined in I:\Night\Night\src\Night\GameServer\..\..\CrossRoads\Common\Entity\Entity.h
extern char *gameSpecificPreLoginFixup_Version_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__Entity_h_NNOGameServer_6_gameSpecificPreLoginFixup_Version(void)
{
	TestLateLinkArgString(&gameSpecificPreLoginFixup_Version_LATELINK_ARGSTRING, "int ", "gameSpecificPreLoginFixup_Version");
}

//Stuff relating to LATELINK declaration for getAccountServer(), defined in I:\Night\Night\src\Night\GameServer\..\..\libs\UtilitiesLib\net\accountnet.h
extern char *getAccountServer_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__accountnet_h_NNOGameServer_0_getAccountServer(void)
{
	TestLateLinkArgString(&getAccountServer_LATELINK_ARGSTRING, "char * ", "getAccountServer");
}

//Stuff relating to LATELINK declaration for inv_LevelNumericSet_GetNotifyString(), defined in I:\Night\Night\src\Night\GameServer\..\..\CrossRoads\Common\item\inventoryCommon.h
extern char *inv_LevelNumericSet_GetNotifyString_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__inventoryCommon_h_NNOGameServer_0_inv_LevelNumericSet_GetNotifyString(void)
{
	TestLateLinkArgString(&inv_LevelNumericSet_GetNotifyString_LATELINK_ARGSTRING, "void Entity * const char * S32 char * * ", "inv_LevelNumericSet_GetNotifyString");
}

//Stuff relating to LATELINK declaration for inv_ent_getEntityItemQuality(), defined in I:\Night\Night\src\Night\GameServer\..\..\CrossRoads\Common\item\inventoryCommon.h
extern char *inv_ent_getEntityItemQuality_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__inventoryCommon_h_NNOGameServer_1_inv_ent_getEntityItemQuality(void)
{
	TestLateLinkArgString(&inv_ent_getEntityItemQuality_LATELINK_ARGSTRING, "U32 Entity * ", "inv_ent_getEntityItemQuality");
}

//Stuff relating to LATELINK_OVERRIDE_isValidRegionTypeForGame(), defined in I:\Night\Night\src\Night\GameServer\..\Common\NNOCommon.c
extern bool OVERRIDE_LATELINK_isValidRegionTypeForGame(U32 arg0);
typedef bool isValidRegionTypeForGame_LATELINK_FPTYPE_INTERNAL(U32 arg0);
extern isValidRegionTypeForGame_LATELINK_FPTYPE_INTERNAL *isValidRegionTypeForGame_LATELINK_FP;
extern char *isValidRegionTypeForGame_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_isValidRegionTypeForGame(void)
{
	isValidRegionTypeForGame_LATELINK_FP = OVERRIDE_LATELINK_isValidRegionTypeForGame;
	TestLateLinkArgString(&isValidRegionTypeForGame_LATELINK_ARGSTRING, "bool U32 ", "isValidRegionTypeForGame");
}

//Stuff relating to LATELINK_OVERRIDE_store_VendorValidations(), defined in I:\Night\Night\src\Night\GameServer\..\Common\NNOCommon.c
extern bool OVERRIDE_LATELINK_store_VendorValidations(void* arg0);
typedef bool store_VendorValidations_LATELINK_FPTYPE_INTERNAL(void* arg0);
extern store_VendorValidations_LATELINK_FPTYPE_INTERNAL *store_VendorValidations_LATELINK_FP;
extern char *store_VendorValidations_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_store_VendorValidations(void)
{
	store_VendorValidations_LATELINK_FP = OVERRIDE_LATELINK_store_VendorValidations;
	TestLateLinkArgString(&store_VendorValidations_LATELINK_ARGSTRING, "bool StoreDef * ", "store_VendorValidations");
}


#ifdef THIS_SYMBOL_IS_NOT_DEFINED
PARSABLE
26
1 "ContainerMappingInit" "void"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\Night\GameServer\Gateway\NNOGatewayContainerMapping.c" 119 2 "void " 
2 "GameSpecific_CaptainCostumeFixup" "void"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\Night\GameServer\..\..\CrossRoads\Common\Entity\Entity.h" 1398 3 "void Entity * " 
2 "GameSpecific_CreateShieldFX" "void"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\Night\GameServer\..\..\CrossRoads\Common\Entity\Entity.h" 1394 2 "void Entity * " 
2 "GameSpecific_HandleInventoryChangeNumeric" "void"  "void*"  "void*"  "bool"  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\Night\GameServer\..\..\CrossRoads\Common\item\itemCommon.h" 1889 0 "void Entity * const char * bool " 
2 "GameSpecific_HolsterRequest" "void"  "void*"  "void*"  "bool"  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\Night\GameServer\..\..\CrossRoads\Common\Entity\Entity.h" 1391 1 "void Entity * Entity * bool " 
1 "GatewayEntityTick" "void"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\Night\GameServer\Gateway\NNOGatewayContainerMapping.c" 108 1 "void Entity * " 
1 "GatewayVendor_GetContactDef" "void*"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\Night\GameServer\Gateway\NNOGatewayVendor.c" 8 0 "ContactDef * const char * " 
1 "GetContainerMappings" "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\Night\GameServer\Gateway\NNOGatewayContainerMapping.c" 50 0 "ContainerMapping * " 
1 "GetItemInfoComparedSMF" "void"  "void**"  "Language"  "void*"  "void*"  "S32"  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\Night\GameServer\Gateway\NNOGatewayItemDescription.c" 21 0 "void char * * Language Item * Entity * S32 " 
1 "GetStructMappings" "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\Night\GameServer\Gateway\NNOGatewayStructMapping.c" 350 0 "StructMapping * " 
1 "ProdSpecificGlobalConfigSetup" "void"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\Night\GameServer\..\Common\NNOCommon.c" 34 0 "void " 
1 "UserExp_ShouldLogThisUser" "bool"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\Night\GameServer\NNOGameServer.c" 13 0 "bool Entity * " 
1 "ent_FixupProjectSpecificPowers" "void"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\Night\GameServer\NNOFixup.c" 715 2 "void Entity * " 
1 "ent_NeedsProjectSpecificPowersFixup" "bool"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\Night\GameServer\NNOFixup.c" 698 1 "bool Entity * " 
2 "entity_CreateProjSpecificLogString" "void*"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\Night\GameServer\..\..\CrossRoads\Common\Entity\Entity.h" 1387 0 "char * Entity * " 
1 "entity_CreateProjSpecificLogString" "void*"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\Night\GameServer\NNOLogging.c" 26 0 "char * Entity * " 
2 "gameSpecificFixup" "void"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\Night\GameServer\..\..\CrossRoads\Common\Entity\Entity.h" 1504 4 "void Entity * " 
1 "gameSpecificFixup" "void"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\Night\GameServer\NNOFixup.c" 99 0 "void Entity * " 
2 "gameSpecificFixup_Version" "int"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\Night\GameServer\..\..\CrossRoads\Common\Entity\Entity.h" 1507 5 "int " 
1 "gameSpecificFixup_Version" "int"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\Night\GameServer\..\Common\NNOCommon.c" 405 3 "int " 
2 "gameSpecificPreLoginFixup_Version" "int"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\Night\GameServer\..\..\CrossRoads\Common\Entity\Entity.h" 1510 6 "int " 
2 "getAccountServer" "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\Night\GameServer\..\..\libs\UtilitiesLib\net\accountnet.h" 30 0 "char * " 
2 "inv_LevelNumericSet_GetNotifyString" "void"  "void*"  "void*"  "S32"  "void**"  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\Night\GameServer\..\..\CrossRoads\Common\item\inventoryCommon.h" 1069 0 "void Entity * const char * S32 char * * " 
2 "inv_ent_getEntityItemQuality" "U32"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\Night\GameServer\..\..\CrossRoads\Common\item\inventoryCommon.h" 1279 1 "U32 Entity * " 
1 "isValidRegionTypeForGame" "bool"  "U32"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\Night\GameServer\..\Common\NNOCommon.c" 356 1 "bool U32 " 
1 "store_VendorValidations" "bool"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\Night\GameServer\..\Common\NNOCommon.c" 365 2 "bool StoreDef * " 
#endif
