#ifndef GAMECLIENT
//This file contains data and prototypes for auto transactions. It is autogenerated by StructParser

//autogeneratednocheckin
#include "autotransdefs.h"
#include "objtransactions.h"

//----------------Stuff relating to HELPER func entity_trh_UpdateFixupVersion -----------------------
static ATRStaticDereference ATR_entity_trh_UpdateFixupVersion_playerEnt_StaticDerefs[] = {
	{ "pSaved->uGameSpecificFixupVersion", ATR_LOCK_NORMAL, 130 },
	{NULL}
};
extern ParseTable parse_Entity[];
static ATRContainerArgDef ATR_entity_trh_UpdateFixupVersion_ContainerArgDefs[] = {
	{ "playerEnt", 0, 0, NULL, ATR_entity_trh_UpdateFixupVersion_playerEnt_StaticDerefs, false, NULL, NULL, parse_Entity},
	{NULL}
};
static ATR_FuncDef ATRFuncDef_entity_trh_UpdateFixupVersion = { "entity_trh_UpdateFixupVersion", "NNOFixup.c", "(null)", NULL, NULL, NULL, ATR_entity_trh_UpdateFixupVersion_ContainerArgDefs, NULL,  NULL, 0 };

//----------------Stuff relating to AUTO_TRANS func entity_tr_UpdateFixupVersion -----------------------
extern ParseTable parse_Entity[];
static ATRContainerArgDef ATR_entity_tr_UpdateFixupVersion_ContainerArgDefs[] = {
	{ "playerEnt", 0, 0, ".Psaved.Ugamespecificfixupversion", NULL, false, NULL, NULL, parse_Entity},
	{NULL}
};
static ATRFuncCallContainerArg ATR_entity_tr_UpdateFixupVersion_0_FuncCallContainerArgs[] = {
	{ 0, 0, "" },
	{ -1 }
};
static ATRFunctionCallDef ATR_entity_tr_UpdateFixupVersion_FuncCalls[] ={
	{ "entity_trh_UpdateFixupVersion", 147, NULL, ATR_entity_tr_UpdateFixupVersion_0_FuncCallContainerArgs },
	{NULL}
};
extern ParseTable parse_Entity[];
static ATRArgDef ATR_entity_tr_UpdateFixupVersion_ArgDefs[] ={
	{ ATR_ARG_CONTAINER, parse_Entity, "playerEnt" },
	{ ATR_ARG_NONE, NULL }
};
enumTransactionOutcome entity_tr_UpdateFixupVersion(ATR_ARGS, struct Entity *playerEnt);
static enumTransactionOutcome ATR_Wrapper_entity_tr_UpdateFixupVersion(char **pestrSuccess, char **pestrFail){
	struct Entity *arg0;
	enumTransactionOutcome eRetVal;
	PERFINFO_AUTO_START_FUNC();
	arg0 = GetATRArg_Container(0);

	eRetVal = entity_tr_UpdateFixupVersion(pestrSuccess, pestrFail, arg0);
	PERFINFO_AUTO_STOP_FUNC(); return eRetVal;
};

static ATR_FuncDef ATRFuncDef_entity_tr_UpdateFixupVersion = { "entity_tr_UpdateFixupVersion", "NNOFixup.c", "(null)", ATR_Wrapper_entity_tr_UpdateFixupVersion, ATR_entity_tr_UpdateFixupVersion_ArgDefs, NULL, ATR_entity_tr_UpdateFixupVersion_ContainerArgDefs, NULL, ATR_entity_tr_UpdateFixupVersion_FuncCalls, 0 };

//----------------Stuff relating to HELPER func RemoveFoundersPacksFromNPCEMail -----------------------
static ATRStaticDereference ATR_RemoveFoundersPacksFromNPCEMail_playerEnt_StaticDerefs[] = {
	{ "pPlayer->pEmailV2->mail", ATR_LOCK_NORMAL, 170 },
	{NULL}
};
extern ParseTable parse_Entity[];
static ATRContainerArgDef ATR_RemoveFoundersPacksFromNPCEMail_ContainerArgDefs[] = {
	{ "playerEnt", 0, 0, NULL, ATR_RemoveFoundersPacksFromNPCEMail_playerEnt_StaticDerefs, false, NULL, NULL, parse_Entity},
	{NULL}
};
static ATR_FuncDef ATRFuncDef_RemoveFoundersPacksFromNPCEMail = { "RemoveFoundersPacksFromNPCEMail", "NNOFixup.c", "StructDestroyNoConst", NULL, NULL, NULL, ATR_RemoveFoundersPacksFromNPCEMail_ContainerArgDefs, NULL,  NULL, 0 };

//----------------Stuff relating to HELPER func RemoveFoundersPackItemsFromInventory -----------------------
static ATRStaticDereference ATR_RemoveFoundersPackItemsFromInventory_playerEnt_StaticDerefs[] = {
	{ "pInventoryV2->ppInventoryBags", ATR_LOCK_NORMAL, 235 },
	{NULL}
};
extern ParseTable parse_Entity[];
static ATRContainerArgDef ATR_RemoveFoundersPackItemsFromInventory_ContainerArgDefs[] = {
	{ "playerEnt", 0, 0, NULL, ATR_RemoveFoundersPackItemsFromInventory_playerEnt_StaticDerefs, false, NULL, NULL, parse_Entity},
	{NULL}
};
static ATR_FuncDef ATRFuncDef_RemoveFoundersPackItemsFromInventory = { "RemoveFoundersPackItemsFromInventory", "NNOFixup.c", "StructDestroyNoConstSafe", NULL, NULL, NULL, ATR_RemoveFoundersPackItemsFromInventory_ContainerArgDefs, NULL,  NULL, 0 };

//----------------Stuff relating to HELPER func FixupMaleDrowWithAppearanceChangeToken -----------------------
static ATRSimpleArgDef ATR_FixupMaleDrowWithAppearanceChangeToken_SimpleArgDefs[] = {
	{ "pReason", 1 },
	{NULL}
};
extern ParseTable parse_Entity[];
static ATRContainerArgDef ATR_FixupMaleDrowWithAppearanceChangeToken_ContainerArgDefs[] = {
	{ "playerEnt", 0, 0, NULL, NULL, false, NULL, NULL, parse_Entity},
	{NULL}
};
static ATRFuncCallContainerArg ATR_FixupMaleDrowWithAppearanceChangeToken_0_FuncCallContainerArgs[] = {
	{ 0, 0, "pChar->hSpecies" },
	{ -1 }
};
static ATRFuncCallContainerArg ATR_FixupMaleDrowWithAppearanceChangeToken_1_FuncCallContainerArgs[] = {
	{ 0, 0, "" },
	{ -1 }
};
static ATRFuncCallSimpleArg ATR_FixupMaleDrowWithAppearanceChangeToken_1_FuncCallSimpleArgs[] = {
	{ 2, ATR_INDEX_LITERAL_STRING, 0, "Freecostumechange"},
	{ 3, ATR_INDEX_LITERAL_INT, 1, NULL},
	{ 4, ATR_INDEX_SIMPLE_ARG, 1, NULL},
	{ -1 }
};
static ATRFunctionCallDef ATR_FixupMaleDrowWithAppearanceChangeToken_FuncCalls[] ={
	{ "REF_STRING_FROM_HANDLE", 268, NULL, ATR_FixupMaleDrowWithAppearanceChangeToken_0_FuncCallContainerArgs },
	{ "inv_ent_trh_AddNumeric", 272, ATR_FixupMaleDrowWithAppearanceChangeToken_1_FuncCallSimpleArgs, ATR_FixupMaleDrowWithAppearanceChangeToken_1_FuncCallContainerArgs },
	{NULL}
};
static ATR_FuncDef ATRFuncDef_FixupMaleDrowWithAppearanceChangeToken = { "FixupMaleDrowWithAppearanceChangeToken", "NNOFixup.c", "inv_ent_trh_AddNumeric", NULL, NULL, ATR_FixupMaleDrowWithAppearanceChangeToken_SimpleArgDefs, ATR_FixupMaleDrowWithAppearanceChangeToken_ContainerArgDefs, NULL, ATR_FixupMaleDrowWithAppearanceChangeToken_FuncCalls, 0 };

//----------------Stuff relating to HELPER func ReplaceBrokenMTSkillKitItems -----------------------
static ATRSimpleArgDef ATR_ReplaceBrokenMTSkillKitItems_SimpleArgDefs[] = {
	{ "pReason", 1 },
	{ "pExtract", 2 },
	{NULL}
};
extern ParseTable parse_Entity[];
static ATRContainerArgDef ATR_ReplaceBrokenMTSkillKitItems_ContainerArgDefs[] = {
	{ "playerEnt", 0, 0, NULL, NULL, false, NULL, NULL, parse_Entity},
	{NULL}
};
static ATRFuncCallContainerArg ATR_ReplaceBrokenMTSkillKitItems_0_FuncCallContainerArgs[] = {
	{ 0, 0, "" },
	{ -1 }
};
static ATRFuncCallSimpleArg ATR_ReplaceBrokenMTSkillKitItems_0_FuncCallSimpleArgs[] = {
	{ 2, ATR_INDEX_SIMPLE_ARG, 1, NULL},
	{ 3, ATR_INDEX_SIMPLE_ARG, 2, NULL},
	{ -1 }
};
static ATRFuncCallContainerArg ATR_ReplaceBrokenMTSkillKitItems_1_FuncCallContainerArgs[] = {
	{ 0, 0, "" },
	{ -1 }
};
static ATRFuncCallSimpleArg ATR_ReplaceBrokenMTSkillKitItems_1_FuncCallSimpleArgs[] = {
	{ 3, ATR_INDEX_LITERAL_INT, -1, NULL},
	{ 6, ATR_INDEX_LITERAL_INT, 0, NULL},
	{ 9, ATR_INDEX_SIMPLE_ARG, 1, NULL},
	{ 10, ATR_INDEX_SIMPLE_ARG, 2, NULL},
	{ -1 }
};
static ATRFunctionCallDef ATR_ReplaceBrokenMTSkillKitItems_FuncCalls[] ={
	{ "inv_trh_RemoveAllItemByDefName", 302, ATR_ReplaceBrokenMTSkillKitItems_0_FuncCallSimpleArgs, ATR_ReplaceBrokenMTSkillKitItems_0_FuncCallContainerArgs },
	{ "inv_ent_trh_AddItemFromDef", 305, ATR_ReplaceBrokenMTSkillKitItems_1_FuncCallSimpleArgs, ATR_ReplaceBrokenMTSkillKitItems_1_FuncCallContainerArgs },
	{NULL}
};
static ATR_FuncDef ATRFuncDef_ReplaceBrokenMTSkillKitItems = { "ReplaceBrokenMTSkillKitItems", "NNOFixup.c", "inv_ent_trh_AddItemFromDef,inv_trh_RemoveAllItemByDefName", NULL, NULL, ATR_ReplaceBrokenMTSkillKitItems_SimpleArgDefs, ATR_ReplaceBrokenMTSkillKitItems_ContainerArgDefs, NULL, ATR_ReplaceBrokenMTSkillKitItems_FuncCalls, 0 };

//----------------Stuff relating to HELPER func RepairBrokenProfessionAssets -----------------------
static ATRSimpleArgDef ATR_RepairBrokenProfessionAssets_SimpleArgDefs[] = {
	{ "pExtract", 1 },
	{NULL}
};
static ATRStaticDereference ATR_RepairBrokenProfessionAssets_playerEnt_StaticDerefs[] = {
	{ "pPlayer->pItemAssignmentPersistedData->eaActiveAssignments", ATR_LOCK_NORMAL, 327 },
	{NULL}
};
extern ParseTable parse_Entity[];
static ATRContainerArgDef ATR_RepairBrokenProfessionAssets_ContainerArgDefs[] = {
	{ "playerEnt", 0, 0, NULL, ATR_RepairBrokenProfessionAssets_playerEnt_StaticDerefs, false, NULL, NULL, parse_Entity},
	{NULL}
};
static ATRFuncCallContainerArg ATR_RepairBrokenProfessionAssets_0_FuncCallContainerArgs[] = {
	{ 0, 0, "" },
	{ -1 }
};
static ATRFuncCallSimpleArg ATR_RepairBrokenProfessionAssets_0_FuncCallSimpleArgs[] = {
	{ 3, ATR_INDEX_SIMPLE_ARG, 1, NULL},
	{ -1 }
};
static ATRFunctionCallDef ATR_RepairBrokenProfessionAssets_FuncCalls[] ={
	{ "bagiterator_trh_SetBagByID", 323, ATR_RepairBrokenProfessionAssets_0_FuncCallSimpleArgs, ATR_RepairBrokenProfessionAssets_0_FuncCallContainerArgs },
	{NULL}
};
static ATR_FuncDef ATRFuncDef_RepairBrokenProfessionAssets = { "RepairBrokenProfessionAssets", "NNOFixup.c", "StaticDefineInt_FastStringToInt,bagiterator_Create,bagiterator_Destroy,bagiterator_GetItem,bagiterator_Next,bagiterator_trh_SetBagByID", NULL, NULL, ATR_RepairBrokenProfessionAssets_SimpleArgDefs, ATR_RepairBrokenProfessionAssets_ContainerArgDefs, NULL, ATR_RepairBrokenProfessionAssets_FuncCalls, 0 };

//----------------Stuff relating to HELPER func GiveCaturdayRewardPack -----------------------
static ATRSimpleArgDef ATR_GiveCaturdayRewardPack_SimpleArgDefs[] = {
	{ "pReason", 1 },
	{NULL}
};
extern ParseTable parse_Entity[];
static ATRContainerArgDef ATR_GiveCaturdayRewardPack_ContainerArgDefs[] = {
	{ "playerEnt", 0, 0, NULL, NULL, false, NULL, NULL, parse_Entity},
	{NULL}
};
static ATRFuncCallContainerArg ATR_GiveCaturdayRewardPack_0_FuncCallContainerArgs[] = {
	{ 0, 0, "pPlayer->langID" },
	{ -1 }
};
static ATRFuncCallSimpleArg ATR_GiveCaturdayRewardPack_0_FuncCallSimpleArgs[] = {
	{ 1, ATR_INDEX_LITERAL_STRING, 0, "NNO_Fixup_Caturday_Mail_Sender"},
	{ 2, ATR_INDEX_LITERAL_STRING, 0, "[UNTRANSLATED]Sender"},
	{ -1 }
};
static ATRFuncCallContainerArg ATR_GiveCaturdayRewardPack_1_FuncCallContainerArgs[] = {
	{ 0, 0, "pPlayer->langID" },
	{ -1 }
};
static ATRFuncCallSimpleArg ATR_GiveCaturdayRewardPack_1_FuncCallSimpleArgs[] = {
	{ 1, ATR_INDEX_LITERAL_STRING, 0, "NNO_Fixup_Caturday_Mail_Subject"},
	{ 2, ATR_INDEX_LITERAL_STRING, 0, "[UNTRANSLATED]Subject"},
	{ -1 }
};
static ATRFuncCallContainerArg ATR_GiveCaturdayRewardPack_2_FuncCallContainerArgs[] = {
	{ 0, 0, "pPlayer->langID" },
	{ -1 }
};
static ATRFuncCallSimpleArg ATR_GiveCaturdayRewardPack_2_FuncCallSimpleArgs[] = {
	{ 1, ATR_INDEX_LITERAL_STRING, 0, "NNO_Fixup_Caturday_Mail_Body"},
	{ 2, ATR_INDEX_LITERAL_STRING, 0, "[UNTRANSLATED]Body"},
	{ -1 }
};
static ATRFuncCallContainerArg ATR_GiveCaturdayRewardPack_3_FuncCallContainerArgs[] = {
	{ 0, 0, "" },
	{ -1 }
};
static ATRFuncCallSimpleArg ATR_GiveCaturdayRewardPack_3_FuncCallSimpleArgs[] = {
	{ 5, ATR_INDEX_LITERAL_INT, 0, NULL},
	{ 7, ATR_INDEX_SIMPLE_ARG, 1, NULL},
	{ -1 }
};
static ATRFunctionCallDef ATR_GiveCaturdayRewardPack_FuncCalls[] ={
	{ "langTranslateMessageKeyDefault", 390, ATR_GiveCaturdayRewardPack_0_FuncCallSimpleArgs, ATR_GiveCaturdayRewardPack_0_FuncCallContainerArgs },
	{ "langTranslateMessageKeyDefault", 391, ATR_GiveCaturdayRewardPack_1_FuncCallSimpleArgs, ATR_GiveCaturdayRewardPack_1_FuncCallContainerArgs },
	{ "langTranslateMessageKeyDefault", 392, ATR_GiveCaturdayRewardPack_2_FuncCallSimpleArgs, ATR_GiveCaturdayRewardPack_2_FuncCallContainerArgs },
	{ "EntityMail_trh_NPCAddMail", 395, ATR_GiveCaturdayRewardPack_3_FuncCallSimpleArgs, ATR_GiveCaturdayRewardPack_3_FuncCallContainerArgs },
	{NULL}
};
static ATR_FuncDef ATRFuncDef_GiveCaturdayRewardPack = { "GiveCaturdayRewardPack", "NNOFixup.c", "CharacterMailAddItem,EntityMail_trh_NPCAddMail,inv_ItemInstanceFromDefName,langTranslateMessageKeyDefault", NULL, NULL, ATR_GiveCaturdayRewardPack_SimpleArgDefs, ATR_GiveCaturdayRewardPack_ContainerArgDefs, NULL, ATR_GiveCaturdayRewardPack_FuncCalls, 0 };

//----------------Stuff relating to HELPER func GrantStickerBookItems_Fixup_8 -----------------------
extern ParseTable parse_Entity[];
static ATRContainerArgDef ATR_GrantStickerBookItems_Fixup_8_ContainerArgDefs[] = {
	{ "playerEnt", 0, 0, NULL, NULL, false, NULL, NULL, parse_Entity},
	{NULL}
};
static ATRFuncCallContainerArg ATR_GrantStickerBookItems_Fixup_8_0_FuncCallContainerArgs[] = {
	{ 0, 0, "pInventoryV2->ppInventoryBags" },
	{ -1 }
};
static ATRFuncCallContainerArg ATR_GrantStickerBookItems_Fixup_8_1_FuncCallContainerArgs[] = {
	{ 0, 0, "" },
	{ -1 }
};
static ATRFunctionCallDef ATR_GrantStickerBookItems_Fixup_8_FuncCalls[] ={
	{ "FOR_EACH_IN_EARRAY", 404, NULL, ATR_GrantStickerBookItems_Fixup_8_0_FuncCallContainerArgs },
	{ "StickerBook_trh_MaybeRecentlyAcquiredItem", 411, NULL, ATR_GrantStickerBookItems_Fixup_8_1_FuncCallContainerArgs },
	{NULL}
};
static ATR_FuncDef ATRFuncDef_GrantStickerBookItems_Fixup_8 = { "GrantStickerBookItems_Fixup_8", "NNOFixup.c", "StickerBook_trh_MaybeRecentlyAcquiredItem", NULL, NULL, NULL, ATR_GrantStickerBookItems_Fixup_8_ContainerArgDefs, NULL, ATR_GrantStickerBookItems_Fixup_8_FuncCalls, 0 };

//----------------Stuff relating to HELPER func RemoveOwlbearMountBoundFlag_Fixup_7 -----------------------
extern ParseTable parse_Entity[];
static ATRContainerArgDef ATR_RemoveOwlbearMountBoundFlag_Fixup_7_ContainerArgDefs[] = {
	{ "playerEnt", 0, 0, NULL, NULL, false, NULL, NULL, parse_Entity},
	{NULL}
};
static ATRFuncCallContainerArg ATR_RemoveOwlbearMountBoundFlag_Fixup_7_0_FuncCallContainerArgs[] = {
	{ 0, 0, "pInventoryV2->ppInventoryBags" },
	{ -1 }
};
static ATRFunctionCallDef ATR_RemoveOwlbearMountBoundFlag_Fixup_7_FuncCalls[] ={
	{ "FOR_EACH_IN_EARRAY", 433, NULL, ATR_RemoveOwlbearMountBoundFlag_Fixup_7_0_FuncCallContainerArgs },
	{NULL}
};
static ATR_FuncDef ATRFuncDef_RemoveOwlbearMountBoundFlag_Fixup_7 = { "RemoveOwlbearMountBoundFlag_Fixup_7", "NNOFixup.c", "", NULL, NULL, NULL, ATR_RemoveOwlbearMountBoundFlag_Fixup_7_ContainerArgDefs, NULL, ATR_RemoveOwlbearMountBoundFlag_Fixup_7_FuncCalls, 0 };

//----------------Stuff relating to HELPER func entity_trh_NNOFixupEntityVersionRecent -----------------------
static ATRSimpleArgDef ATR_entity_trh_NNOFixupEntityVersionRecent_SimpleArgDefs[] = {
	{ "pReason", 1 },
	{ "pExtract", 2 },
	{NULL}
};
static ATRStaticDereference ATR_entity_trh_NNOFixupEntityVersionRecent_playerEnt_StaticDerefs[] = {
	{ "pSaved->uGameSpecificFixupVersion", ATR_LOCK_NORMAL, 458 },
	{NULL}
};
extern ParseTable parse_Entity[];
static ATRContainerArgDef ATR_entity_trh_NNOFixupEntityVersionRecent_ContainerArgDefs[] = {
	{ "playerEnt", 0, 0, NULL, ATR_entity_trh_NNOFixupEntityVersionRecent_playerEnt_StaticDerefs, false, NULL, NULL, parse_Entity},
	{NULL}
};
static ATRFuncCallContainerArg ATR_entity_trh_NNOFixupEntityVersionRecent_0_FuncCallContainerArgs[] = {
	{ 0, 0, "" },
	{ -1 }
};
static ATRFuncCallContainerArg ATR_entity_trh_NNOFixupEntityVersionRecent_1_FuncCallContainerArgs[] = {
	{ 0, 0, "" },
	{ -1 }
};
static ATRFunctionCallDef ATR_entity_trh_NNOFixupEntityVersionRecent_FuncCalls[] ={
	{ "RemoveOwlbearMountBoundFlag_Fixup_7", 460, NULL, ATR_entity_trh_NNOFixupEntityVersionRecent_0_FuncCallContainerArgs },
	{ "GrantStickerBookItems_Fixup_8", 465, NULL, ATR_entity_trh_NNOFixupEntityVersionRecent_1_FuncCallContainerArgs },
	{NULL}
};
static ATR_FuncDef ATRFuncDef_entity_trh_NNOFixupEntityVersionRecent = { "entity_trh_NNOFixupEntityVersionRecent", "NNOFixup.c", "", NULL, NULL, ATR_entity_trh_NNOFixupEntityVersionRecent_SimpleArgDefs, ATR_entity_trh_NNOFixupEntityVersionRecent_ContainerArgDefs, NULL, ATR_entity_trh_NNOFixupEntityVersionRecent_FuncCalls, 0 };

//----------------Stuff relating to AUTO_TRANS func entity_tr_NNOFixupEntityVersionRecent -----------------------
static ATRStaticDereference ATR_entity_tr_NNOFixupEntityVersionRecent_playerEnt_StaticDerefs[] = {
	{ "myEntityType", ATR_LOCK_NORMAL, 489 },
	{ "pSaved->uGameSpecificFixupVersion", ATR_LOCK_NORMAL, 494 },
	{NULL}
};
extern ParseTable parse_Entity[];
static ATRContainerArgDef ATR_entity_tr_NNOFixupEntityVersionRecent_ContainerArgDefs[] = {
	{ "playerEnt", 0, 0, ".Psaved.Ugamespecificfixupversion, .Pinventoryv2.Ppinventorybags, .Pplayer.Eaastrrecentlyacquiredstickerbookitems", ATR_entity_tr_NNOFixupEntityVersionRecent_playerEnt_StaticDerefs, false, NULL, NULL, parse_Entity},
	{NULL}
};
static ATRFuncCallContainerArg ATR_entity_tr_NNOFixupEntityVersionRecent_0_FuncCallContainerArgs[] = {
	{ 0, 1, "debugName" },
	{ 0, 2, "pSaved->uGameSpecificFixupVersion" },
	{ -1 }
};
static ATRFuncCallSimpleArg ATR_entity_tr_NNOFixupEntityVersionRecent_0_FuncCallSimpleArgs[] = {
	{ 0, ATR_INDEX_LITERAL_STRING, 0, "debugName=%s, entFixupVersion=%d"},
	{ -1 }
};
static ATRFuncCallContainerArg ATR_entity_tr_NNOFixupEntityVersionRecent_1_FuncCallContainerArgs[] = {
	{ 0, 0, "" },
	{ -1 }
};
static ATRFuncCallContainerArg ATR_entity_tr_NNOFixupEntityVersionRecent_2_FuncCallContainerArgs[] = {
	{ 0, 0, "" },
	{ -1 }
};
static ATRFunctionCallDef ATR_entity_tr_NNOFixupEntityVersionRecent_FuncCalls[] ={
	{ "ErrorDetailsf", 497, ATR_entity_tr_NNOFixupEntityVersionRecent_0_FuncCallSimpleArgs, ATR_entity_tr_NNOFixupEntityVersionRecent_0_FuncCallContainerArgs },
	{ "entity_trh_NNOFixupEntityVersionRecent", 503, NULL, ATR_entity_tr_NNOFixupEntityVersionRecent_1_FuncCallContainerArgs },
	{ "entity_trh_UpdateFixupVersion", 509, NULL, ATR_entity_tr_NNOFixupEntityVersionRecent_2_FuncCallContainerArgs },
	{NULL}
};
extern ParseTable parse_Entity[];
extern ParseTable parse_ItemChangeReason[];
extern ParseTable parse_GameAccountDataExtract[];
static ATRArgDef ATR_entity_tr_NNOFixupEntityVersionRecent_ArgDefs[] ={
	{ ATR_ARG_CONTAINER, parse_Entity, "playerEnt" },
	{ ATR_ARG_CONST_STRUCT, parse_ItemChangeReason, "pReason" },
	{ ATR_ARG_STRUCT, parse_GameAccountDataExtract, "pExtract" },
	{ ATR_ARG_NONE, NULL }
};
enumTransactionOutcome entity_tr_NNOFixupEntityVersionRecent(ATR_ARGS, struct Entity *playerEnt, struct ItemChangeReason *pReason, struct GameAccountDataExtract *pExtract);
static enumTransactionOutcome ATR_Wrapper_entity_tr_NNOFixupEntityVersionRecent(char **pestrSuccess, char **pestrFail){
	struct Entity *arg0;
	struct ItemChangeReason *arg1;
	struct GameAccountDataExtract *arg2;
	enumTransactionOutcome eRetVal;
	PERFINFO_AUTO_START_FUNC();
	arg0 = GetATRArg_Container(0);
	arg1 = GetATRArg_Struct(1);
	arg2 = GetATRArg_Struct(2);

	eRetVal = entity_tr_NNOFixupEntityVersionRecent(pestrSuccess, pestrFail, arg0, arg1, arg2);
	PERFINFO_AUTO_STOP_FUNC(); return eRetVal;
};

static ATR_FuncDef ATRFuncDef_entity_tr_NNOFixupEntityVersionRecent = { "entity_tr_NNOFixupEntityVersionRecent", "NNOFixup.c", "", ATR_Wrapper_entity_tr_NNOFixupEntityVersionRecent, ATR_entity_tr_NNOFixupEntityVersionRecent_ArgDefs, NULL, ATR_entity_tr_NNOFixupEntityVersionRecent_ContainerArgDefs, NULL, ATR_entity_tr_NNOFixupEntityVersionRecent_FuncCalls, 0 };

//----------------Stuff relating to HELPER func entity_trh_NNOFixupEntityVersionFull -----------------------
static ATRSimpleArgDef ATR_entity_trh_NNOFixupEntityVersionFull_SimpleArgDefs[] = {
	{ "pReason", 1 },
	{ "pExtract", 2 },
	{NULL}
};
static ATRStaticDereference ATR_entity_trh_NNOFixupEntityVersionFull_playerEnt_StaticDerefs[] = {
	{ "pSaved->uGameSpecificFixupVersion", ATR_LOCK_NORMAL, 518 },
	{NULL}
};
extern ParseTable parse_Entity[];
static ATRContainerArgDef ATR_entity_trh_NNOFixupEntityVersionFull_ContainerArgDefs[] = {
	{ "playerEnt", 0, 0, NULL, ATR_entity_trh_NNOFixupEntityVersionFull_playerEnt_StaticDerefs, false, NULL, NULL, parse_Entity},
	{NULL}
};
static ATRFuncCallContainerArg ATR_entity_trh_NNOFixupEntityVersionFull_0_FuncCallContainerArgs[] = {
	{ 0, 0, "" },
	{ -1 }
};
static ATRFuncCallContainerArg ATR_entity_trh_NNOFixupEntityVersionFull_1_FuncCallContainerArgs[] = {
	{ 0, 0, "" },
	{ -1 }
};
static ATRFuncCallContainerArg ATR_entity_trh_NNOFixupEntityVersionFull_2_FuncCallContainerArgs[] = {
	{ 0, 0, "" },
	{ -1 }
};
static ATRFuncCallSimpleArg ATR_entity_trh_NNOFixupEntityVersionFull_2_FuncCallSimpleArgs[] = {
	{ 1, ATR_INDEX_SIMPLE_ARG, 1, NULL},
	{ -1 }
};
static ATRFuncCallContainerArg ATR_entity_trh_NNOFixupEntityVersionFull_3_FuncCallContainerArgs[] = {
	{ 0, 0, "" },
	{ -1 }
};
static ATRFuncCallSimpleArg ATR_entity_trh_NNOFixupEntityVersionFull_3_FuncCallSimpleArgs[] = {
	{ 1, ATR_INDEX_SIMPLE_ARG, 1, NULL},
	{ 2, ATR_INDEX_SIMPLE_ARG, 2, NULL},
	{ -1 }
};
static ATRFuncCallContainerArg ATR_entity_trh_NNOFixupEntityVersionFull_4_FuncCallContainerArgs[] = {
	{ 0, 0, "" },
	{ -1 }
};
static ATRFuncCallSimpleArg ATR_entity_trh_NNOFixupEntityVersionFull_4_FuncCallSimpleArgs[] = {
	{ 1, ATR_INDEX_SIMPLE_ARG, 1, NULL},
	{ -1 }
};
static ATRFuncCallContainerArg ATR_entity_trh_NNOFixupEntityVersionFull_5_FuncCallContainerArgs[] = {
	{ 0, 0, "" },
	{ -1 }
};
static ATRFuncCallSimpleArg ATR_entity_trh_NNOFixupEntityVersionFull_5_FuncCallSimpleArgs[] = {
	{ 1, ATR_INDEX_SIMPLE_ARG, 2, NULL},
	{ -1 }
};
static ATRFuncCallContainerArg ATR_entity_trh_NNOFixupEntityVersionFull_6_FuncCallContainerArgs[] = {
	{ 0, 0, "" },
	{ -1 }
};
static ATRFuncCallSimpleArg ATR_entity_trh_NNOFixupEntityVersionFull_6_FuncCallSimpleArgs[] = {
	{ 1, ATR_INDEX_SIMPLE_ARG, 1, NULL},
	{ 2, ATR_INDEX_SIMPLE_ARG, 2, NULL},
	{ -1 }
};
static ATRFunctionCallDef ATR_entity_trh_NNOFixupEntityVersionFull_FuncCalls[] ={
	{ "RemoveFoundersPacksFromNPCEMail", 520, NULL, ATR_entity_trh_NNOFixupEntityVersionFull_0_FuncCallContainerArgs },
	{ "RemoveFoundersPackItemsFromInventory", 521, NULL, ATR_entity_trh_NNOFixupEntityVersionFull_1_FuncCallContainerArgs },
	{ "FixupMaleDrowWithAppearanceChangeToken", 526, ATR_entity_trh_NNOFixupEntityVersionFull_2_FuncCallSimpleArgs, ATR_entity_trh_NNOFixupEntityVersionFull_2_FuncCallContainerArgs },
	{ "ReplaceBrokenMTSkillKitItems", 533, ATR_entity_trh_NNOFixupEntityVersionFull_3_FuncCallSimpleArgs, ATR_entity_trh_NNOFixupEntityVersionFull_3_FuncCallContainerArgs },
	{ "GiveCaturdayRewardPack", 541, ATR_entity_trh_NNOFixupEntityVersionFull_4_FuncCallSimpleArgs, ATR_entity_trh_NNOFixupEntityVersionFull_4_FuncCallContainerArgs },
	{ "RepairBrokenProfessionAssets", 550, ATR_entity_trh_NNOFixupEntityVersionFull_5_FuncCallSimpleArgs, ATR_entity_trh_NNOFixupEntityVersionFull_5_FuncCallContainerArgs },
	{ "entity_trh_NNOFixupEntityVersionRecent", 557, ATR_entity_trh_NNOFixupEntityVersionFull_6_FuncCallSimpleArgs, ATR_entity_trh_NNOFixupEntityVersionFull_6_FuncCallContainerArgs },
	{NULL}
};
static ATR_FuncDef ATRFuncDef_entity_trh_NNOFixupEntityVersionFull = { "entity_trh_NNOFixupEntityVersionFull", "NNOFixup.c", "", NULL, NULL, ATR_entity_trh_NNOFixupEntityVersionFull_SimpleArgDefs, ATR_entity_trh_NNOFixupEntityVersionFull_ContainerArgDefs, NULL, ATR_entity_trh_NNOFixupEntityVersionFull_FuncCalls, 0 };

//----------------Stuff relating to AUTO_TRANS func entity_tr_NNOFixupEntityVersionFull -----------------------
extern ParseTable parse_Entity[];
static ATRContainerArgDef ATR_entity_tr_NNOFixupEntityVersionFull_ContainerArgDefs[] = {
	{ "playerEnt", 0, 0, ".Pplayer.Pitemassignmentpersisteddata.Eaactiveassignments, .Pplayer.Pemailv2.Unextfuturedelivery, .Pplayer.Pemailv2.Bunreadmail, .Psaved.Ugamespecificfixupversion, .Pplayer.Pemailv2.Mail, .Pinventoryv2.Ppinventorybags, .Pchar.Hspecies, .Psaved.Ppallowedcritterpets, .Pplayer.Langid, .Psaved.Pscpdata.Isummonedscp, .Psaved.Pscpdata.Fcachedpetbonusxppct, .Psaved.Pscpdata.Erscp, .Hallegiance, .Hsuballegiance, .Pplayer.Pplayeraccountdata.Eagamepermissionmaxvaluenumerics, .Pchar.Ilevelexp, .Pinventoryv2.Pplitebags, .Pplayer.Pemailv2.Ilastusedid, .Psaved.Uiindexbuild, .Psaved.Ppbuilds, .Psaved.Conowner.Containerid, .Psaved.Conowner.Containertype, .Pinventoryv2.Peaowneduniqueitems, .Pplayer.Playertype, .Psaved.Ppownedcontainers, .Itemidmax, .Pchar.Uipoweridmax, .Psaved.Ipetid, .Psaved.Ppuppetmaster.Curid, .Psaved.Ppuppetmaster.Curtype, .Psaved.Ppuppetmaster.Curtempid, .Pplayer.Eaplayernumericthresholds, .Pplayer.Eaastrrecentlyacquiredstickerbookitems", NULL, false, NULL, NULL, parse_Entity},
	{NULL}
};
static ATRFuncCallContainerArg ATR_entity_tr_NNOFixupEntityVersionFull_0_FuncCallContainerArgs[] = {
	{ 0, 0, "" },
	{ -1 }
};
static ATRFuncCallContainerArg ATR_entity_tr_NNOFixupEntityVersionFull_1_FuncCallContainerArgs[] = {
	{ 0, 0, "" },
	{ -1 }
};
static ATRFunctionCallDef ATR_entity_tr_NNOFixupEntityVersionFull_FuncCalls[] ={
	{ "entity_trh_NNOFixupEntityVersionFull", 580, NULL, ATR_entity_tr_NNOFixupEntityVersionFull_0_FuncCallContainerArgs },
	{ "entity_trh_UpdateFixupVersion", 586, NULL, ATR_entity_tr_NNOFixupEntityVersionFull_1_FuncCallContainerArgs },
	{NULL}
};
extern ParseTable parse_Entity[];
extern ParseTable parse_ItemChangeReason[];
extern ParseTable parse_GameAccountDataExtract[];
static ATRArgDef ATR_entity_tr_NNOFixupEntityVersionFull_ArgDefs[] ={
	{ ATR_ARG_CONTAINER, parse_Entity, "playerEnt" },
	{ ATR_ARG_CONST_STRUCT, parse_ItemChangeReason, "pReason" },
	{ ATR_ARG_STRUCT, parse_GameAccountDataExtract, "pExtract" },
	{ ATR_ARG_NONE, NULL }
};
enumTransactionOutcome entity_tr_NNOFixupEntityVersionFull(ATR_ARGS, struct Entity *playerEnt, struct ItemChangeReason *pReason, struct GameAccountDataExtract *pExtract);
static enumTransactionOutcome ATR_Wrapper_entity_tr_NNOFixupEntityVersionFull(char **pestrSuccess, char **pestrFail){
	struct Entity *arg0;
	struct ItemChangeReason *arg1;
	struct GameAccountDataExtract *arg2;
	enumTransactionOutcome eRetVal;
	PERFINFO_AUTO_START_FUNC();
	arg0 = GetATRArg_Container(0);
	arg1 = GetATRArg_Struct(1);
	arg2 = GetATRArg_Struct(2);

	eRetVal = entity_tr_NNOFixupEntityVersionFull(pestrSuccess, pestrFail, arg0, arg1, arg2);
	PERFINFO_AUTO_STOP_FUNC(); return eRetVal;
};

static ATR_FuncDef ATRFuncDef_entity_tr_NNOFixupEntityVersionFull = { "entity_tr_NNOFixupEntityVersionFull", "NNOFixup.c", "", ATR_Wrapper_entity_tr_NNOFixupEntityVersionFull, ATR_entity_tr_NNOFixupEntityVersionFull_ArgDefs, NULL, ATR_entity_tr_NNOFixupEntityVersionFull_ContainerArgDefs, NULL, ATR_entity_tr_NNOFixupEntityVersionFull_FuncCalls, 0 };
void ATR_NNOGameServer_RegisterAllFuncs_AutoRun(void)
{
	RegisterATRFuncDef(&ATRFuncDef_entity_trh_UpdateFixupVersion);
	RegisterATRFuncDef(&ATRFuncDef_entity_tr_UpdateFixupVersion);
	RegisterATRFuncDef(&ATRFuncDef_RemoveFoundersPacksFromNPCEMail);
	RegisterATRFuncDef(&ATRFuncDef_RemoveFoundersPackItemsFromInventory);
	RegisterATRFuncDef(&ATRFuncDef_FixupMaleDrowWithAppearanceChangeToken);
	RegisterATRFuncDef(&ATRFuncDef_ReplaceBrokenMTSkillKitItems);
	RegisterATRFuncDef(&ATRFuncDef_RepairBrokenProfessionAssets);
	RegisterATRFuncDef(&ATRFuncDef_GiveCaturdayRewardPack);
	RegisterATRFuncDef(&ATRFuncDef_GrantStickerBookItems_Fixup_8);
	RegisterATRFuncDef(&ATRFuncDef_RemoveOwlbearMountBoundFlag_Fixup_7);
	RegisterATRFuncDef(&ATRFuncDef_entity_trh_NNOFixupEntityVersionRecent);
	RegisterATRFuncDef(&ATRFuncDef_entity_tr_NNOFixupEntityVersionRecent);
	RegisterATRFuncDef(&ATRFuncDef_entity_trh_NNOFixupEntityVersionFull);
	RegisterATRFuncDef(&ATRFuncDef_entity_tr_NNOFixupEntityVersionFull);
};
#else
void ATR_NNOGameServer_RegisterAllFuncs_AutoRun(void){}

#endif
#ifdef THIS_SYMBOL_IS_NOT_DEFINED
PARSABLE
14
1 "entity_trh_UpdateFixupVersion" "I:\Night\Night\src\Night\GameServer\NNOFixup.c" 127 "(null)" 0 0 1 "playerEnt" "Entity" 0 0 "" 1 130 "pSaved->uGameSpecificFixupVersion" 0 0 0 
0 "entity_tr_UpdateFixupVersion" "I:\Night\Night\src\Night\GameServer\NNOFixup.c" 140 "(null)" 1 4 1 "Entity" "playerEnt" 0 1 "playerEnt" "Entity" 0 1 ".Psaved.Ugamespecificfixupversion" 0 0 1 4972 147 "entity_trh_UpdateFixupVersion" 0 1 0 0 "" 
1 "RemoveFoundersPacksFromNPCEMail" "I:\Night\Night\src\Night\GameServer\NNOFixup.c" 153 "(null)" 0 0 1 "playerEnt" "Entity" 0 0 "" 1 170 "pPlayer->pEmailV2->mail" 0 0 0 
1 "RemoveFoundersPackItemsFromInventory" "I:\Night\Night\src\Night\GameServer\NNOFixup.c" 215 "(null)" 0 0 1 "playerEnt" "Entity" 0 0 "" 1 235 "pInventoryV2->ppInventoryBags" 0 0 0 
1 "FixupMaleDrowWithAppearanceChangeToken" "I:\Night\Night\src\Night\GameServer\NNOFixup.c" 261 "(null)" 0 1 "pReason" 1 1 "playerEnt" "Entity" 0 0 "" 0 0 2 9610 268 "REF_STRING_FROM_HANDLE" 0 1 0 0 "pChar->hSpecies" 9815 272 "inv_ent_trh_AddNumeric" 3 1 0 "Freecostumechange" 2 0 1 "" 3 2 1 "" 4 1 0 0 "" 
1 "ReplaceBrokenMTSkillKitItems" "I:\Night\Night\src\Night\GameServer\NNOFixup.c" 283 "(null)" 0 2 "pReason" 1 "pExtract" 2 1 "playerEnt" "Entity" 0 0 "" 0 0 2 10861 302 "inv_trh_RemoveAllItemByDefName" 2 2 1 "" 2 2 2 "" 3 1 0 0 "" 10996 305 "inv_ent_trh_AddItemFromDef" 4 0 -1 "" 3 0 0 "" 6 2 1 "" 9 2 2 "" 10 1 0 0 "" 
1 "RepairBrokenProfessionAssets" "I:\Night\Night\src\Night\GameServer\NNOFixup.c" 315 "(null)" 0 1 "pExtract" 1 1 "playerEnt" "Entity" 0 0 "" 1 327 "pPlayer->pItemAssignmentPersistedData->eaActiveAssignments" 0 0 1 11710 323 "bagiterator_trh_SetBagByID" 1 2 1 "" 3 1 0 0 "" 
1 "GiveCaturdayRewardPack" "I:\Night\Night\src\Night\GameServer\NNOFixup.c" 367 "(null)" 0 1 "pReason" 1 1 "playerEnt" "Entity" 0 0 "" 0 0 4 13560 390 "langTranslateMessageKeyDefault" 2 1 0 "NNO__Fixup__Caturday__Mail__Sender" 1 1 0 "[UNTRANSLATED]Sender" 2 1 0 0 "pPlayer->langID" 13693 391 "langTranslateMessageKeyDefault" 2 1 0 "NNO__Fixup__Caturday__Mail__Subject" 1 1 0 "[UNTRANSLATED]Subject" 2 1 0 0 "pPlayer->langID" 13825 392 "langTranslateMessageKeyDefault" 2 1 0 "NNO__Fixup__Caturday__Mail__Body" 1 1 0 "[UNTRANSLATED]Body" 2 1 0 0 "pPlayer->langID" 13985 395 "EntityMail_trh_NPCAddMail" 2 0 0 "" 5 2 1 "" 7 1 0 0 "" 
1 "GrantStickerBookItems_Fixup_8" "I:\Night\Night\src\Night\GameServer\NNOFixup.c" 399 "(null)" 0 0 1 "playerEnt" "Entity" 0 0 "" 0 0 2 14357 404 "FOR_EACH_IN_EARRAY" 0 1 0 0 "pInventoryV2->ppInventoryBags" 14711 411 "StickerBook_trh_MaybeRecentlyAcquiredItem" 0 1 0 0 "" 
1 "RemoveOwlbearMountBoundFlag_Fixup_7" "I:\Night\Night\src\Night\GameServer\NNOFixup.c" 424 "(null)" 0 0 1 "playerEnt" "Entity" 0 0 "" 0 0 1 15456 433 "FOR_EACH_IN_EARRAY" 0 1 0 0 "pInventoryV2->ppInventoryBags" 
1 "entity_trh_NNOFixupEntityVersionRecent" "I:\Night\Night\src\Night\GameServer\NNOFixup.c" 453 "(null)" 0 2 "pReason" 1 "pExtract" 2 1 "playerEnt" "Entity" 0 0 "" 1 458 "pSaved->uGameSpecificFixupVersion" 0 0 2 16515 460 "RemoveOwlbearMountBoundFlag_Fixup_7" 0 1 0 0 "" 16634 465 "GrantStickerBookItems_Fixup_8" 0 1 0 0 "" 
0 "entity_tr_NNOFixupEntityVersionRecent" "I:\Night\Night\src\Night\GameServer\NNOFixup.c" 475 "(null)" 3 4 1 "Entity" "playerEnt" 5 17 "ItemChangeReason" "pReason" 5 1 "GameAccountDataExtract" "pExtract" 0 1 "playerEnt" "Entity" 0 1 ".Psaved.Ugamespecificfixupversion, .Pinventoryv2.Ppinventorybags, .Pplayer.Eaastrrecentlyacquiredstickerbookitems" 2 489 "myEntityType" 0 494 "pSaved->uGameSpecificFixupVersion" 0 0 3 18092 497 "ErrorDetailsf" 1 1 0 "debugName=_ps, entFixupVersion=_pd" 0 2 0 1 "debugName" 0 2 "pSaved->uGameSpecificFixupVersion" 18389 503 "entity_trh_NNOFixupEntityVersionRecent" 0 1 0 0 "" 18544 509 "entity_trh_UpdateFixupVersion" 0 1 0 0 "" 
1 "entity_trh_NNOFixupEntityVersionFull" "I:\Night\Night\src\Night\GameServer\NNOFixup.c" 514 "(null)" 0 2 "pReason" 1 "pExtract" 2 1 "playerEnt" "Entity" 0 0 "" 1 518 "pSaved->uGameSpecificFixupVersion" 0 0 7 18934 520 "RemoveFoundersPacksFromNPCEMail" 0 1 0 0 "" 19007 521 "RemoveFoundersPackItemsFromInventory" 0 1 0 0 "" 19162 526 "FixupMaleDrowWithAppearanceChangeToken" 1 2 1 "" 1 1 0 0 "" 19386 533 "ReplaceBrokenMTSkillKitItems" 2 2 1 "" 1 2 2 "" 2 1 0 0 "" 19601 541 "GiveCaturdayRewardPack" 1 2 1 "" 1 1 0 0 "" 19793 550 "RepairBrokenProfessionAssets" 1 2 2 "" 1 1 0 0 "" 19969 557 "entity_trh_NNOFixupEntityVersionRecent" 2 2 1 "" 1 2 2 "" 2 1 0 0 "" 
0 "entity_tr_NNOFixupEntityVersionFull" "I:\Night\Night\src\Night\GameServer\NNOFixup.c" 562 "(null)" 3 4 1 "Entity" "playerEnt" 5 17 "ItemChangeReason" "pReason" 5 1 "GameAccountDataExtract" "pExtract" 0 1 "playerEnt" "Entity" 0 1 ".Pplayer.Pitemassignmentpersisteddata.Eaactiveassignments, .Pplayer.Pemailv2.Unextfuturedelivery, .Pplayer.Pemailv2.Bunreadmail, .Psaved.Ugamespecificfixupversion, .Pplayer.Pemailv2.Mail, .Pinventoryv2.Ppinventorybags, .Pchar.Hspecies, .Psaved.Ppallowedcritterpets, .Pplayer.Langid, .Psaved.Pscpdata.Isummonedscp, .Psaved.Pscpdata.Fcachedpetbonusxppct, .Psaved.Pscpdata.Erscp, .Hallegiance, .Hsuballegiance, .Pplayer.Pplayeraccountdata.Eagamepermissionmaxvaluenumerics, .Pchar.Ilevelexp, .Pinventoryv2.Pplitebags, .Pplayer.Pemailv2.Ilastusedid, .Psaved.Uiindexbuild, .Psaved.Ppbuilds, .Psaved.Conowner.Containerid, .Psaved.Conowner.Containertype, .Pinventoryv2.Peaowneduniqueitems, .Pplayer.Playertype, .Psaved.Ppownedcontainers, .Itemidmax, .Pchar.Uipoweridmax, .Psaved.Ipetid, .Psaved.Ppuppetmaster.Curid, .Psaved.Ppuppetmaster.Curtype, .Psaved.Ppuppetmaster.Curtempid, .Pplayer.Eaplayernumericthresholds, .Pplayer.Eaastrrecentlyacquiredstickerbookitems" 0 0 2 21893 580 "entity_trh_NNOFixupEntityVersionFull" 0 1 0 0 "" 22048 586 "entity_trh_UpdateFixupVersion" 0 1 0 0 "" 
#endif
