#include "textparser.h"
//autogeneratednocheckin
extern ParseTable parse_Item[];
#define TYPE_parse_Item Item
extern ParseTable parse_ItemDef[];
#define TYPE_parse_ItemDef ItemDef
//Structparser.exe autogenerated ParseTable for struct NNOItemInfo
#define TYPE_parse_NNOItemInfo NNOItemInfo
ParseTable parse_NNOItemInfo[] =
{
	{ "NNOItemInfo", 				TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(NNOItemInfo), 0, NULL, 0, NULL },
	{ "{",							TOK_START, 0 },
	{ "Item",						TOK_UNOWNED | TOK_OPTIONALSTRUCT(NNOItemInfo, pItem, parse_Item) },
	{ "ItemDef",					TOK_NO_NETSEND | TOK_UNOWNED | TOK_OPTIONALSTRUCT(NNOItemInfo, pItemDef, parse_ItemDef) },
	{ "MinDamage",					TOK_AUTOINT(NNOItemInfo, iMinDamage, 0), NULL },
	{ "MaxDamage",					TOK_AUTOINT(NNOItemInfo, iMaxDamage, 0), NULL },
	{ "PowerRechargeTime",			TOK_F32(NNOItemInfo, fPowerRechargeTime, 0), NULL },
	{ "MinLevel",					TOK_AUTOINT(NNOItemInfo, iMinLevel, 0), NULL },
	{ "MaxLevel",					TOK_AUTOINT(NNOItemInfo, iMaxLevel, 0), NULL },
	{ "ItemQualityIndex",			TOK_AUTOINT(NNOItemInfo, iItemQualityIndex, 0), NULL },
	{ "ItemPowerFactor",			TOK_AUTOINT(NNOItemInfo, iItemPowerFactor, 0), NULL },
	{ "ItemCount",					TOK_AUTOINT(NNOItemInfo, iItemCount, 0), NULL },
	{ "ChargesLeft",				TOK_AUTOINT(NNOItemInfo, iChargesLeft, 0), NULL },
	{ "PowerMaxCharges",			TOK_AUTOINT(NNOItemInfo, iPowerMaxCharges, 0), NULL },
	{ "uItemProgressionTier",		TOK_AUTOINT(NNOItemInfo, uItemProgressionTier, 0), NULL },
	{ "uItemProgressionLevel",		TOK_AUTOINT(NNOItemInfo, uItemProgressionLevel, 0), NULL },
	{ "uItemProgressionXP",			TOK_AUTOINT(NNOItemInfo, uItemProgressionXP, 0), NULL },
	{ "uItemProgressionXPRequired",	TOK_AUTOINT(NNOItemInfo, uItemProgressionXPRequired, 0), NULL },
	{ "EntUsableExpr",				TOK_AUTOINT(NNOItemInfo, bEntUsableExpr, 0), NULL },
	{ "ItemIsRecommended",			TOK_AUTOINT(NNOItemInfo, bItemIsRecommended, 0), NULL },
	{ "EntHasClass",				TOK_AUTOINT(NNOItemInfo, bEntHasClass, 0), NULL },
	{ "EntHasPath",					TOK_AUTOINT(NNOItemInfo, bEntHasPath, 0), NULL },
	{ "IsOwnedByPlayer",			TOK_AUTOINT(NNOItemInfo, bIsOwnedByPlayer, 0), NULL },
	{ "IsMount",					TOK_AUTOINT(NNOItemInfo, bIsMount, 0), NULL },
	{ "EntMeetsLevelRequirements",	TOK_AUTOINT(NNOItemInfo, bEntMeetsLevelRequirements, 0), NULL },
	{ "BindsOnEquip",				TOK_AUTOINT(NNOItemInfo, bBindsOnEquip, 0), NULL },
	{ "BindsOnPickup",				TOK_AUTOINT(NNOItemInfo, bBindsOnPickup, 0), NULL },
	{ "BindsToAccount",				TOK_AUTOINT(NNOItemInfo, bBindsToAccount, 0), NULL },
	{ "IsBound",					TOK_AUTOINT(NNOItemInfo, bIsBound, 0), NULL },
	{ "IsGem",						TOK_AUTOINT(NNOItemInfo, bIsGem, 0), NULL },
	{ "IsItemEnchant",				TOK_AUTOINT(NNOItemInfo, bIsItemEnchant, 0), NULL },
	{ "IsPetEnchant",				TOK_AUTOINT(NNOItemInfo, bIsPetEnchant, 0), NULL },
	{ "ItemIdentified",				TOK_AUTOINT(NNOItemInfo, bItemIdentified, 0), NULL },
	{ "ItemHasBeenDyed",			TOK_AUTOINT(NNOItemInfo, bItemHasBeenDyed, 0), NULL },
	{ "IsTransmutated",				TOK_AUTOINT(NNOItemInfo, bIsTransmutated, 0), NULL },
	{ "CantDiscard",				TOK_AUTOINT(NNOItemInfo, bCantDiscard, 0), NULL },
	{ "ItemProgressionReadyToEvo",	TOK_AUTOINT(NNOItemInfo, bItemProgressionReadyToEvo, 0), NULL },
	{ "ItemProgressionIsMaxLevel",	TOK_AUTOINT(NNOItemInfo, bItemProgressionIsMaxLevel, 0), NULL },
	{ "ItemQuality",				TOK_UNOWNED | TOK_STRING(NNOItemInfo, pchItemQuality, 0), NULL },
	{ "ItemName",					TOK_UNOWNED | TOK_STRING(NNOItemInfo, pchItemName, 0), NULL },
	{ "ItemUsable",					TOK_UNOWNED | TOK_STRING(NNOItemInfo, pchItemUsable, 0), NULL },
	{ "ItemPrompt",					TOK_UNOWNED | TOK_STRING(NNOItemInfo, pchItemPrompt, 0), NULL },
	{ "ItemMission",				TOK_UNOWNED | TOK_STRING(NNOItemInfo, pchItemMission, 0), NULL },
	{ "ItemRequiresExprPower",		TOK_UNOWNED | TOK_STRING(NNOItemInfo, pchItemRequiresExprPower, 0), NULL },
	{ "ItemValue",					TOK_ESTRING | TOK_STRING(NNOItemInfo, estrItemValue, 0), NULL },
	{ "FormattedItemValue",			TOK_ESTRING | TOK_STRING(NNOItemInfo, estrFormattedItemValue, 0), NULL },
	{ "ItemUsagePrompt",			TOK_ESTRING | TOK_STRING(NNOItemInfo, estrItemUsagePrompt, 0), NULL },
	{ "ItemEventTooltip",			TOK_ESTRING | TOK_STRING(NNOItemInfo, estrItemEventTooltip, 0), NULL },
	{ "ItemInnatePowerAutoDesc",	TOK_ESTRING | TOK_STRING(NNOItemInfo, estrItemInnatePowerAutoDesc, 0), NULL },
	{ "ItemPowerAutoDesc",			TOK_ESTRING | TOK_STRING(NNOItemInfo, estrItemPowerAutoDesc, 0), NULL },
	{ "ItemFlavorDesc",				TOK_ESTRING | TOK_STRING(NNOItemInfo, estrItemFlavorDesc, 0), NULL },
	{ "ItemCategories",				TOK_ESTRING | TOK_STRING(NNOItemInfo, estrItemCategories, 0), NULL },
	{ "Itemweapondamage",			TOK_ESTRING | TOK_STRING(NNOItemInfo, estrItemWeaponDamage, 0), NULL },
	{ "ItemDifferences",			TOK_ESTRING | TOK_STRING(NNOItemInfo, estrItemDifferences, 0), NULL },
	{ "ItemWeaponDamageDiff",		TOK_ESTRING | TOK_STRING(NNOItemInfo, estrItemWeaponDamageDiff, 0), NULL },
	{ "ItemSetDesc",				TOK_ESTRING | TOK_STRING(NNOItemInfo, estrItemSetDesc, 0), NULL },
	{ "GemSlots",					TOK_ESTRING | TOK_STRING(NNOItemInfo, estrGemSlots, 0), NULL },
	{ "CharClassRequires",			TOK_ESTRING | TOK_STRING(NNOItemInfo, estrCharClassRequires, 0), NULL },
	{ "CharPathRequires",			TOK_ESTRING | TOK_STRING(NNOItemInfo, estrCharPathRequires, 0), NULL },
	{ "rTransmutatedTo",			TOK_ESTRING | TOK_STRING(NNOItemInfo, estrTransmutatedTo, 0), NULL },
	{ "GameLifetimeLeft",			TOK_ESTRING | TOK_STRING(NNOItemInfo, estrGameLifetimeLeft, 0), NULL },
	{ "RealLifetimeLeft",			TOK_ESTRING | TOK_STRING(NNOItemInfo, estrRealLifetimeLeft, 0), NULL },
	{ "}",							TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_NNOItemInfo()
{
	int iSize = sizeof(NNOItemInfo);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_NNOItemInfo, iSize, "NNOItemInfo", NULL, "NNOItemDescription.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
