#ifndef __NNOITEMDESCRIPTION_H_AST_H_
#define __NNOITEMDESCRIPTION_H_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \NNOItemDescription.h
//autogeneratednocheckin

extern ParseTable parse_NNOItemInfo[];
#define TYPE_parse_NNOItemInfo NNOItemInfo

#endif
