#include "textparser.h"
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct UGCMapTransitionInfo
#define TYPE_parse_UGCMapTransitionInfo UGCMapTransitionInfo
ParseTable parse_UGCMapTransitionInfo[] =
{
	{ "UGCMapTransitionInfo", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCMapTransitionInfo), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "ObjectiveID",			TOK_AUTOINT(UGCMapTransitionInfo, objectiveID, 0), NULL },
	{ "PrevMapName",			TOK_STRING(UGCMapTransitionInfo, prevMapName, 0), NULL },
	{ "PrevIsInternal",			TOK_AUTOINT(UGCMapTransitionInfo, prevIsInternal, 0), NULL },
	{ "MapObjectiveIDs",		TOK_INTARRAY(UGCMapTransitionInfo, mapObjectiveIDs),  NULL},
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCMapTransitionInfo()
{
	int iSize = sizeof(UGCMapTransitionInfo);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCMapTransitionInfo, iSize, "UGCMapTransitionInfo", NULL, "NNOUGCMissionCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct UGCMapInfo
#define TYPE_parse_UGCMapInfo UGCMapInfo
ParseTable parse_UGCMapInfo[] =
{
	{ "UGCMapInfo", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCMapInfo), 0, NULL, 0, NULL },
	{ "{",			TOK_START, 0 },
	{ "MapName",	TOK_STRING(UGCMapInfo, mapName, 0), NULL },
	{ "IsInternal",	TOK_AUTOINT(UGCMapInfo, isInternal, 0), NULL },
	{ "}",			TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCMapInfo()
{
	int iSize = sizeof(UGCMapInfo);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCMapInfo, iSize, "UGCMapInfo", NULL, "NNOUGCMissionCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
