#include "textparser.h"

//auto-generated staticdefine for enum UGCInteractDuration
//autogeneratednocheckin
StaticDefineInt UGCInteractDurationEnum[] =
{
	DEFINE_INT
	{ "UGC.DurationInstant", UGCDURATION_INSTANT},
	{ "UGC.DurationShort", UGCDURATION_SHORT},
	{ "UGC.DurationMedium", UGCDURATION_MEDIUM},
	{ "UGC.DurationLong", UGCDURATION_LONG},
	DEFINE_END
};
void autoEnum_fixup_UGCInteractDuration(void)
{
	static bool bOnce = false; if (bOnce) return; bOnce = true;
	RegisterNamedStaticDefine(UGCInteractDurationEnum, "UGCInteractDuration");
}

//auto-generated staticdefine for enum UGCZOrderSort
//autogeneratednocheckin
StaticDefineInt UGCZOrderSortEnum[] =
{
	DEFINE_INT
	{ "UGC.ZOrderSortLowest", UGCZORDERSORT_LOWEST},
	{ "UGC.ZOrderSortLow", UGCZORDERSORT_LOW},
	{ "UGC.ZOrderSortNormal", UGCZORDERSORT_NORMAL},
	{ "UGC.ZOrderSortHigh", UGCZORDERSORT_HIGH},
	{ "UGC.ZOrderSortHighest", UGCZORDERSORT_HIGHEST},
	DEFINE_END
};
void autoEnum_fixup_UGCZOrderSort(void)
{
	static bool bOnce = false; if (bOnce) return; bOnce = true;
	RegisterNamedStaticDefine(UGCZOrderSortEnum, "UGCZOrderSort");
}

//auto-generated staticdefine for enum UGCComponentType
//autogeneratednocheckin
StaticDefineInt UGCComponentTypeEnum[] =
{
	DEFINE_INT
	{ "SPAWN", UGC_COMPONENT_TYPE_SPAWN},
	{ "RESPAWN", UGC_COMPONENT_TYPE_RESPAWN},
	{ "WHOLE_MAP", UGC_COMPONENT_TYPE_WHOLE_MAP},
	{ "CONTACT", UGC_COMPONENT_TYPE_CONTACT},
	{ "KILL", UGC_COMPONENT_TYPE_KILL},
	{ "ACTOR", UGC_COMPONENT_TYPE_ACTOR},
	{ "COMBAT_JOB", UGC_COMPONENT_TYPE_COMBAT_JOB},
	{ "DESTRUCTIBLE", UGC_COMPONENT_TYPE_DESTRUCTIBLE},
	{ "PATROL_POINT", UGC_COMPONENT_TYPE_PATROL_POINT},
	{ "TRAP", UGC_COMPONENT_TYPE_TRAP},
	{ "TRAP_TARGET", UGC_COMPONENT_TYPE_TRAP_TARGET},
	{ "TRAP_TRIGGER", UGC_COMPONENT_TYPE_TRAP_TRIGGER},
	{ "TRAP_EMITTER", UGC_COMPONENT_TYPE_TRAP_EMITTER},
	{ "TELEPORTER", UGC_COMPONENT_TYPE_TELEPORTER},
	{ "TELEPORTER_PART", UGC_COMPONENT_TYPE_TELEPORTER_PART},
	{ "CLUSTER", UGC_COMPONENT_TYPE_CLUSTER},
	{ "CLUSTER_PART", UGC_COMPONENT_TYPE_CLUSTER_PART},
	{ "REWARD_BOX", UGC_COMPONENT_TYPE_REWARD_BOX},
	{ "SOUND", UGC_COMPONENT_TYPE_SOUND},
	{ "ROOM", UGC_COMPONENT_TYPE_ROOM},
	{ "ROOM_DOOR", UGC_COMPONENT_TYPE_ROOM_DOOR},
	{ "ROOM_OPEN_DOOR", UGC_COMPONENT_TYPE_ROOM_DOOR},
	{ "FAKE_DOOR", UGC_COMPONENT_TYPE_FAKE_DOOR},
	{ "ROOM_CLOSED_DOOR", UGC_COMPONENT_TYPE_FAKE_DOOR},
	{ "BUILDING_DEPRECATED", UGC_COMPONENT_TYPE_BUILDING_DEPRECATED},
	{ "PLANET", UGC_COMPONENT_TYPE_PLANET},
	{ "EXTERNAL_DOOR", UGC_COMPONENT_TYPE_EXTERNAL_DOOR},
	{ "ROOM_MARKER", UGC_COMPONENT_TYPE_ROOM_MARKER},
	{ "DIALOG_TREE", UGC_COMPONENT_TYPE_DIALOG_TREE},
	{ "OBJECT", UGC_COMPONENT_TYPE_OBJECT},
	{ "BUILDING", UGC_COMPONENT_TYPE_OBJECT},
	DEFINE_END
};
void autoEnum_fixup_UGCComponentType(void)
{
	static bool bOnce = false; if (bOnce) return; bOnce = true;
	RegisterNamedStaticDefine(UGCComponentTypeEnum, "UGCComponentType");
}

//auto-generated staticdefine for enum UGCDialogTreePromptActionStyle
//autogeneratednocheckin
StaticDefineInt UGCDialogTreePromptActionStyleEnum[] =
{
	DEFINE_INT
	{ "UGC.DialogStyleNormal", UGCDIALOG_STYLE_NORMAL},
	{ "Normal", UGCDIALOG_STYLE_NORMAL},
	{ "UGC.DialogStyleMissionInfo", UGCDIALOG_STYLE_MISSION_INFO},
	{ "MissionInfo", UGCDIALOG_STYLE_MISSION_INFO},
	{ "UGC.DialogStyleMissionObjective", UGCDIALOG_STYLE_MISSION_OBJECTIVE},
	{ "AcceptMission", UGCDIALOG_STYLE_MISSION_OBJECTIVE},
	DEFINE_END
};
void autoEnum_fixup_UGCDialogTreePromptActionStyle(void)
{
	static bool bOnce = false; if (bOnce) return; bOnce = true;
	RegisterNamedStaticDefine(UGCDialogTreePromptActionStyleEnum, "UGCDialogTreePromptActionStyle");
}

//auto-generated staticdefine for enum UGCDialogTreePromptType
//autogeneratednocheckin
StaticDefineInt UGCDialogTreePromptTypeEnum[] =
{
	DEFINE_INT
	{ "UGC.PromptTypeMisc", UGCPROMPT_MISC},
	DEFINE_END
};
void autoEnum_fixup_UGCDialogTreePromptType(void)
{
	static bool bOnce = false; if (bOnce) return; bOnce = true;
	RegisterNamedStaticDefine(UGCDialogTreePromptTypeEnum, "UGCDialogTreePromptType");
}

//auto-generated staticdefine for enum UGCMissionObjectiveType
//autogeneratednocheckin
StaticDefineInt UGCMissionObjectiveTypeEnum[] =
{
	DEFINE_INT
	{ "COMPLETE_COMPONENT", UGCOBJ_COMPLETE_COMPONENT},
	{ "UNLOCK_DOOR", UGCOBJ_UNLOCK_DOOR},
	{ "ALL_OF", UGCOBJ_ALL_OF},
	{ "IN_ORDER", UGCOBJ_IN_ORDER},
	DEFINE_END
};
void autoEnum_fixup_UGCMissionObjectiveType(void)
{
	static bool bOnce = false; if (bOnce) return; bOnce = true;
	RegisterNamedStaticDefine(UGCMissionObjectiveTypeEnum, "UGCMissionObjectiveType");
}

//auto-generated staticdefine for enum UGCWaypointMode
//autogeneratednocheckin
StaticDefineInt UGCWaypointModeEnum[] =
{
	DEFINE_INT
	{ "UGC.WaypointNone", UGC_WAYPOINT_NONE},
	{ "None", UGC_WAYPOINT_NONE},
	{ "UGC.WaypointArea", UGC_WAYPOINT_AREA},
	{ "Area", UGC_WAYPOINT_AREA},
	{ "Automatic", UGC_WAYPOINT_AREA},
	{ "UGC.WaypointPoints", UGC_WAYPOINT_POINTS},
	{ "Points", UGC_WAYPOINT_POINTS},
	DEFINE_END
};
void autoEnum_fixup_UGCWaypointMode(void)
{
	static bool bOnce = false; if (bOnce) return; bOnce = true;
	RegisterNamedStaticDefine(UGCWaypointModeEnum, "UGCWaypointMode");
}

//auto-generated staticdefine for enum UGCComponentHeightSnap
//autogeneratednocheckin
StaticDefineInt UGCComponentHeightSnapEnum[] =
{
	DEFINE_INT
	{ "LEGACY", COMPONENT_HEIGHT_SNAP_LEGACY},
	{ "DEFAULT", COMPONENT_HEIGHT_SNAP_LEGACY},
	{ "ABSOLUTE", COMPONENT_HEIGHT_SNAP_ABSOLUTE},
	{ "GEOMETRY", COMPONENT_HEIGHT_SNAP_GEOMETRY},
	{ "ROOM_ABSOLUTE", COMPONENT_HEIGHT_SNAP_ROOM_ABSOLUTE},
	{ "ROOM_PARENTED", COMPONENT_HEIGHT_SNAP_ROOM_PARENTED},
	{ "TERRAIN", COMPONENT_HEIGHT_SNAP_TERRAIN},
	{ "WORLDGEO", COMPONENT_HEIGHT_SNAP_WORLDGEO},
	{ "UNSPECIFIED", COMPONENT_HEIGHT_SNAP_UNSPECIFIED},
	DEFINE_END
};
void autoEnum_fixup_UGCComponentHeightSnap(void)
{
	static bool bOnce = false; if (bOnce) return; bOnce = true;
	RegisterNamedStaticDefine(UGCComponentHeightSnapEnum, "UGCComponentHeightSnap");
}

//auto-generated staticdefine for enum UGCWhenType
//autogeneratednocheckin
StaticDefineInt UGCWhenTypeEnum[] =
{
	DEFINE_INT
	{ "OBJECTIVE_IN_PROGRESS", UGCWHEN_OBJECTIVE_IN_PROGRESS},
	{ "IN_PROGRESS", UGCWHEN_OBJECTIVE_IN_PROGRESS},
	{ "OBJECTIVE_COMPLETE", UGCWHEN_OBJECTIVE_COMPLETE},
	{ "COMPLETE", UGCWHEN_OBJECTIVE_COMPLETE},
	{ "OBJECTIVE_START", UGCWHEN_OBJECTIVE_START},
	{ "START", UGCWHEN_OBJECTIVE_START},
	{ "MISSION_START", UGCWHEN_MISSION_START},
	{ "MAP_START", UGCWHEN_MAP_START},
	{ "COMPONENT_COMPLETE", UGCWHEN_COMPONENT_COMPLETE},
	{ "COMPONENT_REACHED", UGCWHEN_COMPONENT_REACHED},
	{ "CURRENT_COMPONENT_COMPLETE", UGCWHEN_CURRENT_COMPONENT_COMPLETE},
	{ "DIALOG_PROMPT_REACHED", UGCWHEN_DIALOG_PROMPT_REACHED},
	{ "PLAYER_HAS_ITEM", UGCWHEN_PLAYER_HAS_ITEM},
	{ "MANUAL", UGCWHEN_MANUAL},
	DEFINE_END
};
void autoEnum_fixup_UGCWhenType(void)
{
	static bool bOnce = false; if (bOnce) return; bOnce = true;
	RegisterNamedStaticDefine(UGCWhenTypeEnum, "UGCWhenType");
}
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct UGCCheckedAttrib
#define TYPE_parse_UGCCheckedAttrib UGCCheckedAttrib
ParseTable parse_UGCCheckedAttrib[] =
{
	{ "UGCCheckedAttrib", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCCheckedAttrib), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "Not",				TOK_AUTOINT(UGCCheckedAttrib, bNot, 0), NULL },
	{ "SkillName",			TOK_POOL_STRING | TOK_STRING(UGCCheckedAttrib, astrSkillName, 0), NULL },
	{ "Name",				TOK_REDUNDANTNAME | TOK_POOL_STRING | TOK_STRING(UGCCheckedAttrib, astrSkillName, 0), NULL },
	{ "ItemName",			TOK_POOL_STRING | TOK_STRING(UGCCheckedAttrib, astrItemName, 0), NULL },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCCheckedAttrib()
{
	int iSize = sizeof(UGCCheckedAttrib);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCCheckedAttrib, iSize, "UGCCheckedAttrib", NULL, "NNOUGCResource.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_UGCCheckedAttrib[];
#define TYPE_parse_UGCCheckedAttrib UGCCheckedAttrib
//Structparser.exe autogenerated ParseTable for struct UGCInteractProperties
#define TYPE_parse_UGCInteractProperties UGCInteractProperties
ParseTable parse_UGCInteractProperties[] =
{
	{ "UGCInteractProperties", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCInteractProperties), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "InteractText",			TOK_STRING(UGCInteractProperties, pcInteractText, 0), NULL },
	{ "InteractFailureText",	TOK_STRING(UGCInteractProperties, pcInteractFailureText, 0), NULL },
	{ "InteractAnim",			TOK_REFERENCE(UGCInteractProperties, hInteractAnim, 0, "AIAnimList") },
	{ "InteractDuration",		TOK_AUTOINT(UGCInteractProperties, eInteractDuration, UGCDURATION_MEDIUM), UGCInteractDurationEnum },
	{ "SucceedCheckedAttrib",	TOK_OPTIONALSTRUCT(UGCInteractProperties, succeedCheckedAttrib, parse_UGCCheckedAttrib) },
	{ "InteractTakesItem",		TOK_AUTOINT(UGCInteractProperties, bTakesItem, 0), NULL },
	{ "DropItem",				TOK_STRING(UGCInteractProperties, pcDropItemName, 0), NULL },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCInteractProperties()
{
	int iSize = sizeof(UGCInteractProperties);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCInteractProperties, iSize, "UGCInteractProperties", NULL, "NNOUGCResource.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct UGCGenesisBackdropSkyOverride
#define TYPE_parse_UGCGenesisBackdropSkyOverride UGCGenesisBackdropSkyOverride
ParseTable parse_UGCGenesisBackdropSkyOverride[] =
{
	{ "UGCGenesisBackdropSkyOverride", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCGenesisBackdropSkyOverride), 0, NULL, 0, NULL },
	{ "{",								TOK_START, 0 },
	{ "SkyOverride",					TOK_REFERENCE(UGCGenesisBackdropSkyOverride, hSkyOverride, 0, "SkyInfo") },
	{ "}",								TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCGenesisBackdropSkyOverride()
{
	int iSize = sizeof(UGCGenesisBackdropSkyOverride);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCGenesisBackdropSkyOverride, iSize, "UGCGenesisBackdropSkyOverride", NULL, "NNOUGCResource.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_UGCGenesisBackdropSkyOverride[];
#define TYPE_parse_UGCGenesisBackdropSkyOverride UGCGenesisBackdropSkyOverride
//Structparser.exe autogenerated ParseTable for struct UGCGenesisBackdrop
#define TYPE_parse_UGCGenesisBackdrop UGCGenesisBackdrop
ParseTable parse_UGCGenesisBackdrop[] =
{
	{ "UGCGenesisBackdrop", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCGenesisBackdrop), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "SkyBase",			TOK_REFERENCE(UGCGenesisBackdrop, hSkyBase, 0, "SkyInfo") },
	{ "Backdrop",			TOK_REDUNDANTNAME | TOK_REFERENCE(UGCGenesisBackdrop, hSkyBase, 0, "SkyInfo") },
	{ "SkyOverride",		TOK_STRUCT(UGCGenesisBackdrop, eaSkyOverrides, parse_UGCGenesisBackdropSkyOverride) },
	{ "AmbSoundOverride",	TOK_STRING(UGCGenesisBackdrop, strAmbientSoundOverride, 0), NULL },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCGenesisBackdrop()
{
	int iSize = sizeof(UGCGenesisBackdrop);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCGenesisBackdrop, iSize, "UGCGenesisBackdrop", NULL, "NNOUGCResource.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_UGCGenesisBackdropSkyOverride[];
#define TYPE_parse_UGCGenesisBackdropSkyOverride UGCGenesisBackdropSkyOverride
//Structparser.exe autogenerated ParseTable for struct UGCGenesisSpace
#define TYPE_parse_UGCGenesisSpace UGCGenesisSpace
ParseTable parse_UGCGenesisSpace[] =
{
	{ "UGCGenesisSpace", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCGenesisSpace), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "Backdrop", 			TOK_IGNORE | TOK_FLATEMBED },
	{ "SkyBase",			TOK_REFERENCE(UGCGenesisSpace, backdrop.hSkyBase, 0, "SkyInfo") },
	{ "Backdrop",			TOK_REDUNDANTNAME | TOK_REFERENCE(UGCGenesisSpace, backdrop.hSkyBase, 0, "SkyInfo") },
	{ "SkyOverride",		TOK_STRUCT(UGCGenesisSpace, backdrop.eaSkyOverrides, parse_UGCGenesisBackdropSkyOverride) },
	{ "AmbSoundOverride",	TOK_STRING(UGCGenesisSpace, backdrop.strAmbientSoundOverride, 0), NULL },
	{ "UGCBackdrop",		TOK_IGNORE | TOK_IGNORE_STRUCT , 0 },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCGenesisSpace()
{
	int iSize = sizeof(UGCGenesisSpace);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCGenesisSpace, iSize, "UGCGenesisSpace", NULL, "NNOUGCResource.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_UGCGenesisBackdropSkyOverride[];
#define TYPE_parse_UGCGenesisBackdropSkyOverride UGCGenesisBackdropSkyOverride
//Structparser.exe autogenerated ParseTable for struct UGCGenesisPrefab
#define TYPE_parse_UGCGenesisPrefab UGCGenesisPrefab
ParseTable parse_UGCGenesisPrefab[] =
{
	{ "UGCGenesisPrefab", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCGenesisPrefab), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "Backdrop", 			TOK_IGNORE | TOK_FLATEMBED },
	{ "SkyBase",			TOK_REFERENCE(UGCGenesisPrefab, backdrop.hSkyBase, 0, "SkyInfo") },
	{ "Backdrop",			TOK_REDUNDANTNAME | TOK_REFERENCE(UGCGenesisPrefab, backdrop.hSkyBase, 0, "SkyInfo") },
	{ "SkyOverride",		TOK_STRUCT(UGCGenesisPrefab, backdrop.eaSkyOverrides, parse_UGCGenesisBackdropSkyOverride) },
	{ "AmbSoundOverride",	TOK_STRING(UGCGenesisPrefab, backdrop.strAmbientSoundOverride, 0), NULL },
	{ "MapName",			TOK_POOL_STRING | TOK_STRING(UGCGenesisPrefab, map_name, 0), NULL },
	{ "Customizable",		TOK_AUTOINT(UGCGenesisPrefab, customizable, 0), NULL },
	{ "UGCBackdrop",		TOK_IGNORE | TOK_IGNORE_STRUCT , 0 },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCGenesisPrefab()
{
	int iSize = sizeof(UGCGenesisPrefab);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCGenesisPrefab, iSize, "UGCGenesisPrefab", NULL, "NNOUGCResource.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct UGCUnitializedMap
#define TYPE_parse_UGCUnitializedMap UGCUnitializedMap
ParseTable parse_UGCUnitializedMap[] =
{
	{ "UGCUnitializedMap", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCUnitializedMap), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "Type",				TOK_AUTOINT(UGCUnitializedMap, eType, 0), UGCMapTypeEnum },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCUnitializedMap()
{
	int iSize = sizeof(UGCUnitializedMap);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCUnitializedMap, iSize, "UGCUnitializedMap", NULL, "NNOUGCResource.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_UGCGenesisSpace[];
#define TYPE_parse_UGCGenesisSpace UGCGenesisSpace
extern ParseTable parse_UGCGenesisPrefab[];
#define TYPE_parse_UGCGenesisPrefab UGCGenesisPrefab
extern ParseTable parse_UGCUnitializedMap[];
#define TYPE_parse_UGCUnitializedMap UGCUnitializedMap
//Structparser.exe autogenerated ParseTable for struct UGCMap
#define TYPE_parse_UGCMap UGCMap
ParseTable parse_UGCMap[] =
{
	{ "UGCMap", 			TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCMap), 0, NULL, 0, NULL },
	{ "{",				TOK_START, 0 },
	{ "Name",			TOK_POOL_STRING | TOK_KEY | TOK_STRING(UGCMap, pcName, 0), NULL },
	{ "Filename",		TOK_NO_NETSEND | TOK_POOL_STRING | TOK_CURRENTFILE(UGCMap, pcFilename), NULL},
	{ "DisplayName",	TOK_STRING(UGCMap, pcDisplayName, 0), NULL },
	{ "Notes",			TOK_STRING(UGCMap, strNotes, 0), NULL },
	{ "Space",			TOK_OPTIONALSTRUCT(UGCMap, pSpace, parse_UGCGenesisSpace) },
	{ "Prefab",			TOK_OPTIONALSTRUCT(UGCMap, pPrefab, parse_UGCGenesisPrefab) },
	{ "UnitializedMap",	TOK_OPTIONALSTRUCT(UGCMap, pUnitializedMap, parse_UGCUnitializedMap) },
	{ "Created",		TOK_IGNORE | TOK_IGNORE_STRUCT , 0 },
	{ "Saved",			TOK_IGNORE | TOK_IGNORE_STRUCT , 0 },
	{ "}",				TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCMap()
{
	int iSize = sizeof(UGCMap);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCMap, iSize, "UGCMap", NULL, "NNOUGCResource.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_UGCWhen[];
#define TYPE_parse_UGCWhen UGCWhen
extern ParseTable parse_UGCWhen[];
#define TYPE_parse_UGCWhen UGCWhen
extern ParseTable parse_UGCCheckedAttrib[];
#define TYPE_parse_UGCCheckedAttrib UGCCheckedAttrib
//Structparser.exe autogenerated ParseTable for struct UGCDialogTreePromptAction
#define TYPE_parse_UGCDialogTreePromptAction UGCDialogTreePromptAction
ParseTable parse_UGCDialogTreePromptAction[] =
{
	{ "UGCDialogTreePromptAction", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCDialogTreePromptAction), 0, NULL, 0, NULL },
	{ "{",							TOK_START, 0 },
	{ "Text",						TOK_STRUCTPARAM | TOK_STRING(UGCDialogTreePromptAction, pcText, 0), NULL },
	{ "NextPromptID",				TOK_AUTOINT(UGCDialogTreePromptAction, nextPromptID, 0), NULL },
	{ "DismissAction",				TOK_AUTOINT(UGCDialogTreePromptAction, bDismissAction, 0), NULL },
	{ "Style",						TOK_AUTOINT(UGCDialogTreePromptAction, style, 0), UGCDialogTreePromptActionStyleEnum },
	{ "ShowWhen",					TOK_OPTIONALSTRUCT(UGCDialogTreePromptAction, pShowWhen, parse_UGCWhen) },
	{ "HideWhen",					TOK_OPTIONALSTRUCT(UGCDialogTreePromptAction, pHideWhen, parse_UGCWhen) },
	{ "EnabledCheckedAttrib",		TOK_OPTIONALSTRUCT(UGCDialogTreePromptAction, enabledCheckedAttrib, parse_UGCCheckedAttrib) },
	{ "}",							TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCDialogTreePromptAction()
{
	int iSize = sizeof(UGCDialogTreePromptAction);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCDialogTreePromptAction, iSize, "UGCDialogTreePromptAction", NULL, "NNOUGCResource.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_UGCDialogTreePromptAction[];
#define TYPE_parse_UGCDialogTreePromptAction UGCDialogTreePromptAction
//Structparser.exe autogenerated ParseTable for struct UGCDialogTreePrompt
#define TYPE_parse_UGCDialogTreePrompt UGCDialogTreePrompt
ParseTable parse_UGCDialogTreePrompt[] =
{
	{ "UGCDialogTreePrompt", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCDialogTreePrompt), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "uid",					TOK_STRUCTPARAM | TOK_AUTOINT(UGCDialogTreePrompt, uid, 0), NULL },
	{ "PromptTitle",			TOK_STRING(UGCDialogTreePrompt, pcPromptTitle, 0), NULL },
	{ "PromptBody",				TOK_STRING(UGCDialogTreePrompt, pcPromptBody, 0), NULL },
	{ "Action",					TOK_STRUCT(UGCDialogTreePrompt, eaActions, parse_UGCDialogTreePromptAction) },
	{ "PromptButton",			TOK_REDUNDANTNAME | TOK_STRUCT(UGCDialogTreePrompt, eaActions, parse_UGCDialogTreePromptAction) },
	{ "PromptCostume",			TOK_STRING(UGCDialogTreePrompt, pcPromptCostume, 0), NULL },
	{ "PromptPetCostume",		TOK_REFERENCE(UGCDialogTreePrompt, hPromptPetCostume, 0, "PetContactList") },
	{ "PromptStyle",			TOK_STRING(UGCDialogTreePrompt, pcPromptStyle, 0), NULL },
	{ "CameraPos",				TOK_IGNORE, 0 },
	{ "PromptType",				TOK_IGNORE, 0 },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCDialogTreePrompt()
{
	int iSize = sizeof(UGCDialogTreePrompt);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCDialogTreePrompt, iSize, "UGCDialogTreePrompt", NULL, "NNOUGCResource.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_UGCDialogTreePromptAction[];
#define TYPE_parse_UGCDialogTreePromptAction UGCDialogTreePromptAction
extern ParseTable parse_UGCDialogTreePrompt[];
#define TYPE_parse_UGCDialogTreePrompt UGCDialogTreePrompt
//Structparser.exe autogenerated ParseTable for struct UGCDialogTreeBlock
#define TYPE_parse_UGCDialogTreeBlock UGCDialogTreeBlock
ParseTable parse_UGCDialogTreeBlock[] =
{
	{ "UGCDialogTreeBlock", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCDialogTreeBlock), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "BlockIndex",			TOK_AUTOINT(UGCDialogTreeBlock, blockIndex, 0), NULL },
	{ "initialPrompt", 		TOK_IGNORE | TOK_FLATEMBED },
	{ "uid",				TOK_STRUCTPARAM | TOK_AUTOINT(UGCDialogTreeBlock, initialPrompt.uid, 0), NULL },
	{ "PromptTitle",		TOK_STRING(UGCDialogTreeBlock, initialPrompt.pcPromptTitle, 0), NULL },
	{ "PromptBody",			TOK_STRING(UGCDialogTreeBlock, initialPrompt.pcPromptBody, 0), NULL },
	{ "Action",				TOK_STRUCT(UGCDialogTreeBlock, initialPrompt.eaActions, parse_UGCDialogTreePromptAction) },
	{ "PromptButton",		TOK_REDUNDANTNAME | TOK_STRUCT(UGCDialogTreeBlock, initialPrompt.eaActions, parse_UGCDialogTreePromptAction) },
	{ "PromptCostume",		TOK_STRING(UGCDialogTreeBlock, initialPrompt.pcPromptCostume, 0), NULL },
	{ "PromptPetCostume",	TOK_REFERENCE(UGCDialogTreeBlock, initialPrompt.hPromptPetCostume, 0, "PetContactList") },
	{ "PromptStyle",		TOK_STRING(UGCDialogTreeBlock, initialPrompt.pcPromptStyle, 0), NULL },
	{ "Prompt",				TOK_STRUCT(UGCDialogTreeBlock, prompts, parse_UGCDialogTreePrompt) },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCDialogTreeBlock()
{
	int iSize = sizeof(UGCDialogTreeBlock);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCDialogTreeBlock, iSize, "UGCDialogTreeBlock", NULL, "NNOUGCResource.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_UGCMapLocation[];
#define TYPE_parse_UGCMapLocation UGCMapLocation
extern ParseTable parse_UGCDialogTreePrompt[];
#define TYPE_parse_UGCDialogTreePrompt UGCDialogTreePrompt
//Structparser.exe autogenerated ParseTable for struct UGCMissionMapLink
#define TYPE_parse_UGCMissionMapLink UGCMissionMapLink
ParseTable parse_UGCMissionMapLink[] =
{
	{ "UGCMissionMapLink", 		TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCMissionMapLink), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "DoorComponent",			TOK_AUTOINT(UGCMissionMapLink, uDoorComponentID, 0), NULL },
	{ "DoorUsesMapLocation",	TOK_AUTOINT(UGCMissionMapLink, bDoorUsesMapLocation, 0), NULL },
	{ "DoorMapLocation",		TOK_OPTIONALSTRUCT(UGCMissionMapLink, pDoorMapLocation, parse_UGCMapLocation) },
	{ "SpawnComponent",			TOK_AUTOINT(UGCMissionMapLink, uSpawnComponentID, 0), NULL },
	{ "SpawnInternalMapName",	TOK_STRING(UGCMissionMapLink, strSpawnInternalMapName, 0), NULL },
	{ "DialogBlock",			TOK_OPTIONALSTRUCT(UGCMissionMapLink, pDialogPrompt, parse_UGCDialogTreePrompt) },
	{ "InteractText",			TOK_STRING(UGCMissionMapLink, strInteractText, 0), NULL },
	{ "ReturnText",				TOK_STRING(UGCMissionMapLink, strReturnText, 0), NULL },
	{ "OpenMissionName",		TOK_STRING(UGCMissionMapLink, strOpenMissionName, 0), NULL },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCMissionMapLink()
{
	int iSize = sizeof(UGCMissionMapLink);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCMissionMapLink, iSize, "UGCMissionMapLink", NULL, "NNOUGCResource.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_UGCDialogTreePrompt[];
#define TYPE_parse_UGCDialogTreePrompt UGCDialogTreePrompt
extern ParseTable parse_UGCMissionObjective[];
#define TYPE_parse_UGCMissionObjective UGCMissionObjective
extern ParseTable parse_UGCMissionMapLink[];
#define TYPE_parse_UGCMissionMapLink UGCMissionMapLink
extern ParseTable parse_UGCMissionMapLink[];
#define TYPE_parse_UGCMissionMapLink UGCMissionMapLink
//Structparser.exe autogenerated ParseTable for struct UGCMission
#define TYPE_parse_UGCMission UGCMission
ParseTable parse_UGCMission[] =
{
	{ "UGCMission", 			TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCMission), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "FN",					TOK_NO_NETSEND | TOK_POOL_STRING | TOK_CURRENTFILE(UGCMission, filename), NULL},
	{ "Name",				TOK_POOL_STRING | TOK_KEY | TOK_STRING(UGCMission, name, 0), NULL },
	{ "GrantBlock",			TOK_EMBEDDEDSTRUCT(UGCMission, sGrantPrompt, parse_UGCDialogTreePrompt)},
	{ "InitialMapName",		TOK_STRING(UGCMission, strInitialMapName, 0), NULL },
	{ "InitialSpawnPoint",	TOK_STRING(UGCMission, strInitialSpawnPoint, 0), NULL },
	{ "Objective",			TOK_STRUCT(UGCMission, objectives, parse_UGCMissionObjective) },
	{ "MapLink",			TOK_STRUCT(UGCMission, map_links, parse_UGCMissionMapLink) },
	{ "ReturnMapLink",		TOK_OPTIONALSTRUCT(UGCMission, return_map_link, parse_UGCMissionMapLink) },
	{ "DisplayName",		TOK_IGNORE, 0 },
	{ "JournalText",		TOK_IGNORE, 0 },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCMission()
{
	int iSize = sizeof(UGCMission);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCMission, iSize, "UGCMission", NULL, "NNOUGCResource.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_UGCMissionObjective[];
#define TYPE_parse_UGCMissionObjective UGCMissionObjective
extern ParseTable parse_UGCCheckedAttrib[];
#define TYPE_parse_UGCCheckedAttrib UGCCheckedAttrib
//Structparser.exe autogenerated ParseTable for struct UGCMissionObjective
#define TYPE_parse_UGCMissionObjective UGCMissionObjective
ParseTable parse_UGCMissionObjective[] =
{
	{ "UGCMissionObjective", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCMissionObjective), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "ID",						TOK_STRUCTPARAM | TOK_AUTOINT(UGCMissionObjective, id, 0), NULL },
	{ "Type",					TOK_AUTOINT(UGCMissionObjective, type, 0), UGCMissionObjectiveTypeEnum },
	{ "UIString",				TOK_STRING(UGCMissionObjective, uiString, 0), NULL },
	{ "WaypointMode",			TOK_AUTOINT(UGCMissionObjective, waypointMode, 0), UGCWaypointModeEnum },
	{ "ComponentMapName",		TOK_STRING(UGCMissionObjective, strComponentInternalMapName, 0), NULL },
	{ "ComponentIsExternal",	TOK_AUTOINT(UGCMissionObjective, bComponentIsExternal, 0), NULL },
	{ "ComponentID",			TOK_AUTOINT(UGCMissionObjective, componentID, 0), NULL },
	{ "ExtraComponentID",		TOK_INTARRAY(UGCMissionObjective, extraComponentIDs),  NULL},
	{ "Children",				TOK_STRUCT(UGCMissionObjective, eaChildren, parse_UGCMissionObjective) },
	{ "SuccessFloaterText",		TOK_STRING(UGCMissionObjective, successFloaterText, 0), NULL },
	{ "sInteractProps", 			TOK_IGNORE | TOK_FLATEMBED },
	{ "InteractText",			TOK_STRING(UGCMissionObjective, sInteractProps.pcInteractText, 0), NULL },
	{ "InteractFailureText",	TOK_STRING(UGCMissionObjective, sInteractProps.pcInteractFailureText, 0), NULL },
	{ "InteractAnim",			TOK_REFERENCE(UGCMissionObjective, sInteractProps.hInteractAnim, 0, "AIAnimList") },
	{ "InteractDuration",		TOK_AUTOINT(UGCMissionObjective, sInteractProps.eInteractDuration, UGCDURATION_MEDIUM), UGCInteractDurationEnum },
	{ "SucceedCheckedAttrib",	TOK_OPTIONALSTRUCT(UGCMissionObjective, sInteractProps.succeedCheckedAttrib, parse_UGCCheckedAttrib) },
	{ "InteractTakesItem",		TOK_AUTOINT(UGCMissionObjective, sInteractProps.bTakesItem, 0), NULL },
	{ "DropItem",				TOK_STRING(UGCMissionObjective, sInteractProps.pcDropItemName, 0), NULL },
	{ "ParentID",				TOK_IGNORE, 0 },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCMissionObjective()
{
	int iSize = sizeof(UGCMissionObjective);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCMissionObjective, iSize, "UGCMissionObjective", NULL, "NNOUGCResource.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_UGCComponent[];
#define TYPE_parse_UGCComponent UGCComponent
//Structparser.exe autogenerated ParseTable for struct UGCComponentList
#define TYPE_parse_UGCComponentList UGCComponentList
ParseTable parse_UGCComponentList[] =
{
	{ "UGCComponentList", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCComponentList), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "Name",				TOK_POOL_STRING | TOK_KEY | TOK_STRING(UGCComponentList, pcName, 0), NULL },
	{ "Filename",			TOK_NO_NETSEND | TOK_POOL_STRING | TOK_CURRENTFILE(UGCComponentList, pcFilename), NULL},
	{ "Component",			TOK_STRUCT(UGCComponentList, eaComponents, parse_UGCComponent) },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
TextParserResult fixupUGCComponentList(UGCComponentList *pStruct, enumTextParserFixupType eFixupType, void *pExtraData);
int autoStruct_fixup_UGCComponentList()
{
	int iSize = sizeof(UGCComponentList);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCComponentList, iSize, "UGCComponentList", fixupUGCComponentList, "NNOUGCResource.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct UGCComponentPlacement
#define TYPE_parse_UGCComponentPlacement UGCComponentPlacement
ParseTable parse_UGCComponentPlacement[] =
{
	{ "UGCComponentPlacement", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCComponentPlacement), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "ExternalPlacement",		TOK_AUTOINT(UGCComponentPlacement, bIsExternalPlacement, 0), NULL },
	{ "MapName",				TOK_STRING(UGCComponentPlacement, pcMapName, 0), NULL },
	{ "RoomID",					TOK_AUTOINT(UGCComponentPlacement, uRoomID, 0), NULL },
	{ "Position",				TOK_VEC3(UGCComponentPlacement, vPos), NULL },
	{ "RotationPYR",			TOK_VEC3(UGCComponentPlacement, vRotPYR), NULL },
	{ "Pitch",					TOK_REDUNDANTNAME | TOK_F32(UGCComponentPlacement, fRotLegacy[0], 0), NULL },
	{ "Rotation",				TOK_REDUNDANTNAME | TOK_F32(UGCComponentPlacement, fRotLegacy[1], 0), NULL },
	{ "Roll",					TOK_REDUNDANTNAME | TOK_F32(UGCComponentPlacement, fRotLegacy[2], 0), NULL },
	{ "Snap",					TOK_AUTOINT(UGCComponentPlacement, eSnap, 0), UGCComponentHeightSnapEnum },
	{ "SnapNormal",				TOK_AUTOINT(UGCComponentPlacement, bSnapNormal, 0), NULL },
	{ "RoomLevel",				TOK_AUTOINT(UGCComponentPlacement, iRoomLevel, 0), NULL },
	{ "ZOrderSort",				TOK_AUTOINT(UGCComponentPlacement, eZOrderSort, 0), UGCZOrderSortEnum },
	{ "ExternalMap",			TOK_STRING(UGCComponentPlacement, pcExternalMapName, 0), NULL },
	{ "ExternalObject",			TOK_STRING(UGCComponentPlacement, pcExternalObjectName, 0), NULL },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCComponentPlacement()
{
	int iSize = sizeof(UGCComponentPlacement);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCComponentPlacement, iSize, "UGCComponentPlacement", NULL, "NNOUGCResource.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct UGCWhenDialogPrompt
#define TYPE_parse_UGCWhenDialogPrompt UGCWhenDialogPrompt
ParseTable parse_UGCWhenDialogPrompt[] =
{
	{ "UGCWhenDialogPrompt", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCWhenDialogPrompt), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "DialogID",				TOK_AUTOINT(UGCWhenDialogPrompt, uDialogID, -1), NULL },
	{ "PromptID",				TOK_AUTOINT(UGCWhenDialogPrompt, iPromptID, -1), NULL },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCWhenDialogPrompt()
{
	int iSize = sizeof(UGCWhenDialogPrompt);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCWhenDialogPrompt, iSize, "UGCWhenDialogPrompt", NULL, "NNOUGCResource.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_UGCWhenDialogPrompt[];
#define TYPE_parse_UGCWhenDialogPrompt UGCWhenDialogPrompt
//Structparser.exe autogenerated ParseTable for struct UGCWhen
#define TYPE_parse_UGCWhen UGCWhen
ParseTable parse_UGCWhen[] =
{
	{ "UGCWhen", 		TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCWhen), 0, NULL, 0, NULL },
	{ "{",				TOK_START, 0 },
	{ "Type",			TOK_STRUCTPARAM | TOK_AUTOINT(UGCWhen, eType, 0), UGCWhenTypeEnum },
	{ "ComponentID",	TOK_INTARRAY(UGCWhen, eauComponentIDs),  NULL},
	{ "ObjectiveID",	TOK_INTARRAY(UGCWhen, eauObjectiveIDs),  NULL},
	{ "ItemName",		TOK_STRING(UGCWhen, strItemName, 0), NULL },
	{ "DialogPrompt",	TOK_STRUCT(UGCWhen, eaDialogPrompts, parse_UGCWhenDialogPrompt) },
	{ "}",				TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCWhen()
{
	int iSize = sizeof(UGCWhen);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCWhen, iSize, "UGCWhen", NULL, "NNOUGCResource.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_UGCWhen[];
#define TYPE_parse_UGCWhen UGCWhen
//Structparser.exe autogenerated ParseTable for struct UGCFSMVar
#define TYPE_parse_UGCFSMVar UGCFSMVar
ParseTable parse_UGCFSMVar[] =
{
	{ "UGCFSMVar", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCFSMVar), 0, NULL, 0, NULL },
	{ "{",			TOK_START, 0 },
	{ "Name",		TOK_POOL_STRING | TOK_STRING(UGCFSMVar, astrName, 0), NULL },
	{ "FloatVal",	TOK_F32(UGCFSMVar, floatVal, 0), NULL },
	{ "StringVal",	TOK_STRING(UGCFSMVar, strStringVal, 0), NULL },
	{ "WhenVal",	TOK_OPTIONALSTRUCT(UGCFSMVar, pWhenVal, parse_UGCWhen) },
	{ "}",			TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCFSMVar()
{
	int iSize = sizeof(UGCFSMVar);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCFSMVar, iSize, "UGCFSMVar", NULL, "NNOUGCResource.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_UGCFSMVar[];
#define TYPE_parse_UGCFSMVar UGCFSMVar
extern ParseTable parse_WorldVariableDef[];
#define TYPE_parse_WorldVariableDef WorldVariableDef
//Structparser.exe autogenerated ParseTable for struct UGCFSMProperties
#define TYPE_parse_UGCFSMProperties UGCFSMProperties
ParseTable parse_UGCFSMProperties[] =
{
	{ "UGCFSMProperties", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCFSMProperties), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "FSMRef",				TOK_STRING(UGCFSMProperties, pcFSMNameRef, 0), NULL },
	{ "ExternVarV1",		TOK_STRUCT(UGCFSMProperties, eaExternVarsV1, parse_UGCFSMVar) },
	{ "ExternVar",			TOK_NO_INDEX | TOK_STRUCT(UGCFSMProperties, eaExternVarsV0, parse_WorldVariableDef) },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCFSMProperties()
{
	int iSize = sizeof(UGCFSMProperties);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCFSMProperties, iSize, "UGCFSMProperties", NULL, "NNOUGCResource.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct UGCRoomDetailData
#define TYPE_parse_UGCRoomDetailData UGCRoomDetailData
ParseTable parse_UGCRoomDetailData[] =
{
	{ "UGCRoomDetailData", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCRoomDetailData), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "Index",				TOK_AUTOINT(UGCRoomDetailData, iIndex, 0), NULL },
	{ "Choice",				TOK_AUTOINT(UGCRoomDetailData, iChoice, 0), NULL },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCRoomDetailData()
{
	int iSize = sizeof(UGCRoomDetailData);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCRoomDetailData, iSize, "UGCRoomDetailData", NULL, "NNOUGCResource.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_UGCComponentPlacement[];
#define TYPE_parse_UGCComponentPlacement UGCComponentPlacement
extern ParseTable parse_UGCWhen[];
#define TYPE_parse_UGCWhen UGCWhen
extern ParseTable parse_UGCWhen[];
#define TYPE_parse_UGCWhen UGCWhen
extern ParseTable parse_UGCCheckedAttrib[];
#define TYPE_parse_UGCCheckedAttrib UGCCheckedAttrib
extern ParseTable parse_UGCInteractProperties[];
#define TYPE_parse_UGCInteractProperties UGCInteractProperties
extern ParseTable parse_UGCDialogTreePromptAction[];
#define TYPE_parse_UGCDialogTreePromptAction UGCDialogTreePromptAction
extern ParseTable parse_UGCDialogTreePrompt[];
#define TYPE_parse_UGCDialogTreePrompt UGCDialogTreePrompt
extern ParseTable parse_UGCDialogTreeBlock[];
#define TYPE_parse_UGCDialogTreeBlock UGCDialogTreeBlock
extern ParseTable parse_UGCFSMVar[];
#define TYPE_parse_UGCFSMVar UGCFSMVar
extern ParseTable parse_WorldVariableDef[];
#define TYPE_parse_WorldVariableDef WorldVariableDef
extern ParseTable parse_UGCRoomDetailData[];
#define TYPE_parse_UGCRoomDetailData UGCRoomDetailData
//Structparser.exe autogenerated ParseTable for struct UGCComponent
#define TYPE_parse_UGCComponent UGCComponent
ParseTable parse_UGCComponent[] =
{
	{ "UGCComponent", 								TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCComponent), 0, NULL, 0, NULL },
	{ "{",											TOK_START, 0 },
	{ "ID",											TOK_STRUCTPARAM | TOK_KEY | TOK_AUTOINT(UGCComponent, uID, 0), NULL },
	{ "ParentID",									TOK_AUTOINT(UGCComponent, uParentID, 0), NULL },
	{ "ChildIDs",									TOK_INTARRAY(UGCComponent, uChildIDs),  NULL},
	{ "VisibleName",								TOK_STRING(UGCComponent, pcVisibleName, 0), NULL },
	{ "Type",										TOK_AUTOINT(UGCComponent, eType, 0), UGCComponentTypeEnum },
	{ "Placement",									TOK_EMBEDDEDSTRUCT(UGCComponent, sPlacement, parse_UGCComponentPlacement)},
	{ "MapType",									TOK_AUTOINT(UGCComponent, eMapType, 0), UGCMapTypeEnum },
	{ "ObjectName",									TOK_STRING(UGCComponent, pcOldObjectLibraryName, 0), NULL },
	{ "ObjectID",									TOK_AUTOINT(UGCComponent, iObjectLibraryId, 0), NULL },
	{ "When",										TOK_OPTIONALSTRUCT(UGCComponent, pStartWhen, parse_UGCWhen) },
	{ "PromptWhen",									TOK_REDUNDANTNAME | TOK_OPTIONALSTRUCT(UGCComponent, pStartWhen, parse_UGCWhen) },
	{ "PromptIsPopup",								TOK_REDUNDANTNAME | TOK_OPTIONALSTRUCT(UGCComponent, pStartWhen, parse_UGCWhen) },
	{ "HideWhen",									TOK_OPTIONALSTRUCT(UGCComponent, pHideWhen, parse_UGCWhen) },
	{ "VisibleCheckedAttrib",						TOK_EMBEDDEDSTRUCT(UGCComponent, visibleCheckedAttrib, parse_UGCCheckedAttrib)},
	{ "SoundEvent",									TOK_POOL_STRING | TOK_STRING(UGCComponent, strSoundEvent, 0), NULL },
	{ "IsRoomVolume",								TOK_AUTOINT(UGCComponent, bIsRoomVolume, 0), NULL },
	{ "VolumeRadius",								TOK_F32(UGCComponent, fVolumeRadius, 0), NULL },
	{ "Ring",										TOK_STRING(UGCComponent, pcOldPlanetRingName, 0), NULL },
	{ "RingID",										TOK_AUTOINT(UGCComponent, iPlanetRingId, 0), NULL },
	{ "InteractText",								TOK_STRING(UGCComponent, pcOldInteractText, 0), NULL },
	{ "InteractAnim",								TOK_REFERENCE(UGCComponent, hOldInteractAnim, 0, "AIAnimList") },
	{ "InteractDuration",							TOK_AUTOINT(UGCComponent, eOldInteractDuration, UGCDURATION_MEDIUM), UGCInteractDurationEnum },
	{ "InteractTriggerGroup",						TOK_STRUCT(UGCComponent, eaTriggerGroups, parse_UGCInteractProperties) },
	{ "InteractIsMissionReturn",					TOK_AUTOINT(UGCComponent, bInteractIsMissionReturn, 0), NULL },
	{ "Interact",									TOK_AUTOINT(UGCComponent, bInteractForce, 0), NULL },
	{ "PromptCostumeName",							TOK_STRING(UGCComponent, pcPromptCostumeName, 0), NULL },
	{ "dialogBlock", 								TOK_IGNORE | TOK_FLATEMBED },
	{ "BlockIndex",									TOK_AUTOINT(UGCComponent, dialogBlock.blockIndex, 0), NULL },
	{ "initialPrompt", 								TOK_IGNORE | TOK_FLATEMBED },
	{ "uid",										TOK_STRUCTPARAM | TOK_AUTOINT(UGCComponent, dialogBlock.initialPrompt.uid, 0), NULL },
	{ "PromptTitle",								TOK_STRING(UGCComponent, dialogBlock.initialPrompt.pcPromptTitle, 0), NULL },
	{ "PromptBody",									TOK_STRING(UGCComponent, dialogBlock.initialPrompt.pcPromptBody, 0), NULL },
	{ "Action",										TOK_STRUCT(UGCComponent, dialogBlock.initialPrompt.eaActions, parse_UGCDialogTreePromptAction) },
	{ "PromptButton",								TOK_REDUNDANTNAME | TOK_STRUCT(UGCComponent, dialogBlock.initialPrompt.eaActions, parse_UGCDialogTreePromptAction) },
	{ "PromptCostume",								TOK_STRING(UGCComponent, dialogBlock.initialPrompt.pcPromptCostume, 0), NULL },
	{ "PromptPetCostume",							TOK_REFERENCE(UGCComponent, dialogBlock.initialPrompt.hPromptPetCostume, 0, "PetContactList") },
	{ "PromptStyle",								TOK_STRING(UGCComponent, dialogBlock.initialPrompt.pcPromptStyle, 0), NULL },
	{ "Prompt",										TOK_STRUCT(UGCComponent, dialogBlock.prompts, parse_UGCDialogTreePrompt) },
	{ "Block",										TOK_STRUCT(UGCComponent, blocksV1, parse_UGCDialogTreeBlock) },
	{ "Prompt",										TOK_REDUNDANTNAME | TOK_STRUCT(UGCComponent, blocksV1, parse_UGCDialogTreeBlock) },
	{ "ActorID",									TOK_AUTOINT(UGCComponent, uActorID, 0), NULL },
	{ "PromptContactID",							TOK_REDUNDANTNAME | TOK_AUTOINT(UGCComponent, uActorID, 0), NULL },
	{ "ObjectiveID",								TOK_INTARRAY(UGCComponent, eaObjectiveIDs),  NULL},
	{ "PromptWhenObjectiveID",						TOK_REDUNDANTNAME | TOK_INTARRAY(UGCComponent, eaObjectiveIDs),  NULL},
	{ "IsDefault",									TOK_AUTOINT(UGCComponent, bIsDefault, 0), NULL },
	{ "DisplayNameWasFixed",						TOK_AUTOINT(UGCComponent, bDisplayNameWasFixed, 0), NULL },
	{ "DisplayName",								TOK_STRING(UGCComponent, pcDisplayName_DEPRECATED, 0), NULL },
	{ "ContactName",								TOK_REDUNDANTNAME | TOK_STRING(UGCComponent, pcDisplayName_DEPRECATED, 0), NULL },
	{ "CostumeName",								TOK_STRING(UGCComponent, pcCostumeName, 0), NULL },
	{ "fsmProperties", 								TOK_IGNORE | TOK_FLATEMBED },
	{ "FSMRef",										TOK_STRING(UGCComponent, fsmProperties.pcFSMNameRef, 0), NULL },
	{ "ExternVarV1",								TOK_STRUCT(UGCComponent, fsmProperties.eaExternVarsV1, parse_UGCFSMVar) },
	{ "ExternVar",									TOK_NO_INDEX | TOK_STRUCT(UGCComponent, fsmProperties.eaExternVarsV0, parse_WorldVariableDef) },
	{ "PatrolPoint",								TOK_INTARRAY(UGCComponent, eaPatrolPoints),  NULL},
	{ "DropItem",									TOK_STRING(UGCComponent, pcDropItemName, 0), NULL },
	{ "PatrolPointsFixed_FromComponentPosition",	TOK_AUTOINT(UGCComponent, bPatrolPointsFixed_FromComponentPosition, 0), NULL },
	{ "Detail",										TOK_STRUCT(UGCComponent, eaRoomDetails, parse_UGCRoomDetailData) },
	{ "SoundDSP",									TOK_STRING(UGCComponent, strSoundDSP, 0), NULL },
	{ "RoomDoor",									TOK_AUTOINT(UGCComponent, iRoomDoorID, 0), NULL },
	{ "IsDoorExplicitDefault",						TOK_AUTOINT(UGCComponent, bIsDoorExplicitDefault, 0), NULL },
	{ "TrapPower",									TOK_STRING(UGCComponent, pcTrapPower, 0), NULL },
	{ "EmitterIndex",								TOK_AUTOINT(UGCComponent, iTrapEmitterIndex, 0), NULL },
	{ "PatrolParentID",								TOK_AUTOINT(UGCComponent, uPatrolParentID, 0), NULL },
	{ "ActorCritterGroupName",						TOK_STRING(UGCComponent, pcActorCritterGroupName, 0), NULL },
	{ "Count",										TOK_IGNORE, 0 },
	{ "InteractDef",								TOK_IGNORE, 0 },
	{ "PromptTitle",								TOK_IGNORE, 0 },
	{ "PromptInteractionText",						TOK_IGNORE, 0 },
	{ "}",											TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCComponent()
{
	int iSize = sizeof(UGCComponent);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCComponent, iSize, "UGCComponent", NULL, "NNOUGCResource.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct UGCCostumeSlot
#define TYPE_parse_UGCCostumeSlot UGCCostumeSlot
ParseTable parse_UGCCostumeSlot[] =
{
	{ "UGCCostumeSlot", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCCostumeSlot), 0, NULL, 0, NULL },
	{ "{",				TOK_START, 0 },
	{ "Slot",			TOK_POOL_STRING | TOK_STRING(UGCCostumeSlot, astrSlot, 0), NULL },
	{ "Costume",		TOK_POOL_STRING | TOK_STRING(UGCCostumeSlot, astrCostume, 0), NULL },
	{ "Color",			TOK_INTARRAY(UGCCostumeSlot, eaColors),  NULL},
	{ "}",				TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCCostumeSlot()
{
	int iSize = sizeof(UGCCostumeSlot);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCCostumeSlot, iSize, "UGCCostumeSlot", NULL, "NNOUGCResource.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct UGCCostumeScale
#define TYPE_parse_UGCCostumeScale UGCCostumeScale
ParseTable parse_UGCCostumeScale[] =
{
	{ "UGCCostumeScale", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCCostumeScale), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "Name",				TOK_POOL_STRING | TOK_STRING(UGCCostumeScale, astrName, 0), NULL },
	{ "Value",				TOK_F32(UGCCostumeScale, value, 0), NULL },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCCostumeScale()
{
	int iSize = sizeof(UGCCostumeScale);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCCostumeScale, iSize, "UGCCostumeScale", NULL, "NNOUGCResource.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct UGCCostumePart
#define TYPE_parse_UGCCostumePart UGCCostumePart
ParseTable parse_UGCCostumePart[] =
{
	{ "UGCCostumePart", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCCostumePart), 0, NULL, 0, NULL },
	{ "{",				TOK_START, 0 },
	{ "Bone",			TOK_POOL_STRING | TOK_STRING(UGCCostumePart, astrBoneName, 0), NULL },
	{ "Geometry",		TOK_POOL_STRING | TOK_STRING(UGCCostumePart, astrGeometryName, 0), NULL },
	{ "Material",		TOK_POOL_STRING | TOK_STRING(UGCCostumePart, astrMaterialName, 0), NULL },
	{ "Texture0",		TOK_POOL_STRING | TOK_STRING(UGCCostumePart, astrTexture0Name, 0), NULL },
	{ "Texture1",		TOK_POOL_STRING | TOK_STRING(UGCCostumePart, astrTexture1Name, 0), NULL },
	{ "Texture2",		TOK_POOL_STRING | TOK_STRING(UGCCostumePart, astrTexture2Name, 0), NULL },
	{ "Texture3",		TOK_POOL_STRING | TOK_STRING(UGCCostumePart, astrTexture3Name, 0), NULL },
	{ "Color",			TOK_FIXED_ARRAY | TOK_AUTOINTARRAY(UGCCostumePart, colors), NULL },
	{ "}",				TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCCostumePart()
{
	int iSize = sizeof(UGCCostumePart);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCCostumePart, iSize, "UGCCostumePart", NULL, "NNOUGCResource.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_UGCCostumeSlot[];
#define TYPE_parse_UGCCostumeSlot UGCCostumeSlot
extern ParseTable parse_UGCCostumeScale[];
#define TYPE_parse_UGCCostumeScale UGCCostumeScale
extern ParseTable parse_UGCCostumeScale[];
#define TYPE_parse_UGCCostumeScale UGCCostumeScale
extern ParseTable parse_UGCCostumePart[];
#define TYPE_parse_UGCCostumePart UGCCostumePart
//Structparser.exe autogenerated ParseTable for struct UGCCostumeData
#define TYPE_parse_UGCCostumeData UGCCostumeData
ParseTable parse_UGCCostumeData[] =
{
	{ "UGCCostumeData", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCCostumeData), 0, NULL, 0, NULL },
	{ "{",				TOK_START, 0 },
	{ "PresetCostume",	TOK_POOL_STRING | TOK_STRING(UGCCostumeData, astrPresetCostumeName, 0), NULL },
	{ "Slot",			TOK_STRUCT(UGCCostumeData, eaSlots, parse_UGCCostumeSlot) },
	{ "BodyScale",		TOK_STRUCT(UGCCostumeData, eaBodyScales, parse_UGCCostumeScale) },
	{ "Scale",			TOK_STRUCT(UGCCostumeData, eaScales, parse_UGCCostumeScale) },
	{ "Part",			TOK_STRUCT(UGCCostumeData, eaParts, parse_UGCCostumePart) },
	{ "Stance",			TOK_POOL_STRING | TOK_STRING(UGCCostumeData, astrStance, 0), NULL },
	{ "Height",			TOK_F32(UGCCostumeData, fHeight, 0), NULL },
	{ "SkinColor",		TOK_AUTOINT(UGCCostumeData, skinColor, 0), NULL },
	{ "IsAdvanced",		TOK_AUTOINT(UGCCostumeData, isAdvanced, 0), NULL },
	{ "}",				TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCCostumeData()
{
	int iSize = sizeof(UGCCostumeData);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCCostumeData, iSize, "UGCCostumeData", NULL, "NNOUGCResource.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_UGCCostumeData[];
#define TYPE_parse_UGCCostumeData UGCCostumeData
extern ParseTable parse_PlayerCostume[];
#define TYPE_parse_PlayerCostume PlayerCostume
extern ParseTable parse_PlayerCostume[];
#define TYPE_parse_PlayerCostume PlayerCostume
//Structparser.exe autogenerated ParseTable for struct UGCCostume
#define TYPE_parse_UGCCostume UGCCostume
ParseTable parse_UGCCostume[] =
{
	{ "UGCCostume", 				TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCCostume), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "Name",					TOK_POOL_STRING | TOK_KEY | TOK_STRING(UGCCostume, astrName, 0), NULL },
	{ "fstrFilename",			TOK_NO_NETSEND | TOK_POOL_STRING | TOK_CURRENTFILE(UGCCostume, fstrFilename), NULL},
	{ "DisplayName",			TOK_STRING(UGCCostume, pcDisplayName, 0), NULL },
	{ "Description",			TOK_STRING(UGCCostume, pcDescription, 0), NULL },
	{ "Data",					TOK_EMBEDDEDSTRUCT(UGCCostume, data, parse_UGCCostumeData)},
	{ "CachedPlayerCostume",	TOK_NO_WRITE | TOK_NO_NETSEND | TOK_OPTIONALSTRUCT(UGCCostume, pCachedPlayerCostume, parse_PlayerCostume) },
	{ "PlayerCostume",			TOK_OPTIONALSTRUCT(UGCCostume, pPlayerCostume, parse_PlayerCostume) },
	{ "Region",					TOK_AUTOINT(UGCCostume, eRegion, 0), NULL },
	{ "Allegiance",				TOK_REFERENCE(UGCCostume, hAllegiance, 0, "AllegianceDef") },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCCostume()
{
	int iSize = sizeof(UGCCostume);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCCostume, iSize, "UGCCostume", NULL, "NNOUGCResource.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct UGCItem
#define TYPE_parse_UGCItem UGCItem
ParseTable parse_UGCItem[] =
{
	{ "UGCItem", 		TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCItem), 0, NULL, 0, NULL },
	{ "{",				TOK_START, 0 },
	{ "Name",			TOK_POOL_STRING | TOK_KEY | TOK_STRING(UGCItem, astrName, 0), NULL },
	{ "fstrFilename",	TOK_NO_NETSEND | TOK_POOL_STRING | TOK_CURRENTFILE(UGCItem, fstrFilename), NULL},
	{ "DisplayName",	TOK_STRING(UGCItem, strDisplayName, 0), NULL },
	{ "Description",	TOK_STRING(UGCItem, strDescription, 0), NULL },
	{ "Icon",			TOK_STRING(UGCItem, strIcon, 0), NULL },
	{ "}",				TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCItem()
{
	int iSize = sizeof(UGCItem);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCItem, iSize, "UGCItem", NULL, "NNOUGCResource.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct UGCSound
#define TYPE_parse_UGCSound UGCSound
ParseTable parse_UGCSound[] =
{
	{ "UGCSound", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCSound), 0, NULL, 0, NULL },
	{ "{",			TOK_START, 0 },
	{ "Name",		TOK_STRUCTPARAM | TOK_POOL_STRING | TOK_KEY | TOK_STRING(UGCSound, astrName, 0), NULL },
	{ "Tags",		TOK_STRING(UGCSound, strTags, 0), NULL },
	{ "SoundName",	TOK_STRING(UGCSound, strSoundName, 0), NULL },
	{ "AmbSound",	TOK_REDUNDANTNAME | TOK_STRING(UGCSound, strSoundName, 0), NULL },
	{ "}",			TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCSound()
{
	int iSize = sizeof(UGCSound);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCSound, iSize, "UGCSound", NULL, "NNOUGCResource.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct UGCSoundDSP
#define TYPE_parse_UGCSoundDSP UGCSoundDSP
ParseTable parse_UGCSoundDSP[] =
{
	{ "UGCSoundDSP", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCSoundDSP), 0, NULL, 0, NULL },
	{ "{",				TOK_START, 0 },
	{ "Name",			TOK_STRUCTPARAM | TOK_POOL_STRING | TOK_KEY | TOK_STRING(UGCSoundDSP, astrName, 0), NULL },
	{ "SoundDSPName",	TOK_STRING(UGCSoundDSP, strSoundDSPName, 0), NULL },
	{ "}",				TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCSoundDSP()
{
	int iSize = sizeof(UGCSoundDSP);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCSoundDSP, iSize, "UGCSoundDSP", NULL, "NNOUGCResource.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct UGCTrapPowerGroup
#define TYPE_parse_UGCTrapPowerGroup UGCTrapPowerGroup
ParseTable parse_UGCTrapPowerGroup[] =
{
	{ "UGCTrapPowerGroup", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCTrapPowerGroup), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "Name",				TOK_STRUCTPARAM | TOK_POOL_STRING | TOK_KEY | TOK_STRING(UGCTrapPowerGroup, astrName, 0), NULL },
	{ "PowerDef",			TOK_STRINGARRAY(UGCTrapPowerGroup, eaPowerNames), NULL },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCTrapPowerGroup()
{
	int iSize = sizeof(UGCTrapPowerGroup);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCTrapPowerGroup, iSize, "UGCTrapPowerGroup", NULL, "NNOUGCResource.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_UGCProjectInfo[];
#define TYPE_parse_UGCProjectInfo UGCProjectInfo
extern ParseTable parse_UGCMap[];
#define TYPE_parse_UGCMap UGCMap
extern ParseTable parse_UGCMission[];
#define TYPE_parse_UGCMission UGCMission
extern ParseTable parse_UGCComponentList[];
#define TYPE_parse_UGCComponentList UGCComponentList
extern ParseTable parse_UGCCostume[];
#define TYPE_parse_UGCCostume UGCCostume
extern ParseTable parse_UGCItem[];
#define TYPE_parse_UGCItem UGCItem
//Structparser.exe autogenerated ParseTable for struct UGCProjectData
#define TYPE_parse_UGCProjectData UGCProjectData
ParseTable parse_UGCProjectData[] =
{
	{ "UGCProjectData", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCProjectData), 0, NULL, 0, NULL },
	{ "{",				TOK_START, 0 },
	{ "Namespace",		TOK_STRING(UGCProjectData, ns_name, 0), NULL },
	{ "ProjectPrefix",	TOK_STRING(UGCProjectData, project_prefix, 0), NULL },
	{ "Project",		TOK_OPTIONALSTRUCT(UGCProjectData, project, parse_UGCProjectInfo) },
	{ "Map",			TOK_STRUCT(UGCProjectData, maps, parse_UGCMap) },
	{ "Mission",		TOK_OPTIONALSTRUCT(UGCProjectData, mission, parse_UGCMission) },
	{ "Components",		TOK_OPTIONALSTRUCT(UGCProjectData, components, parse_UGCComponentList) },
	{ "Costume",		TOK_STRUCT(UGCProjectData, costumes, parse_UGCCostume) },
	{ "Item",			TOK_STRUCT(UGCProjectData, items, parse_UGCItem) },
	{ "DeleteRes",		TOK_IGNORE | TOK_IGNORE_STRUCT , 0 },
	{ "}",				TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCProjectData()
{
	int iSize = sizeof(UGCProjectData);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCProjectData, iSize, "UGCProjectData", NULL, "NNOUGCResource.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
