#ifndef __NNOUGCCOMMON_H_AST_H_
#define __NNOUGCCOMMON_H_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \NNOUGCCommon.h
//autogeneratednocheckin

//auto-generated staticdefine for enum UGCBudgetType
//autogeneratednocheckin
extern StaticDefineInt UGCBudgetTypeEnum[];

//auto-generated staticdefine for enum UGCCostumeOverrideType
//autogeneratednocheckin
extern StaticDefineInt UGCCostumeOverrideTypeEnum[];

extern ParseTable parse_UGCFSMMetadata[];
#define TYPE_parse_UGCFSMMetadata UGCFSMMetadata

extern ParseTable parse_UGCFSMExternVarDef[];
#define TYPE_parse_UGCFSMExternVarDef UGCFSMExternVarDef

extern ParseTable parse_UGCFSMExternVar[];
#define TYPE_parse_UGCFSMExternVar UGCFSMExternVar

extern ParseTable parse_UGCCostumeMetadata[];
#define TYPE_parse_UGCCostumeMetadata UGCCostumeMetadata

extern ParseTable parse_UGCGroupDefMetadata[];
#define TYPE_parse_UGCGroupDefMetadata UGCGroupDefMetadata

extern ParseTable parse_UGCDefChildMetadata[];
#define TYPE_parse_UGCDefChildMetadata UGCDefChildMetadata

extern ParseTable parse_UGCProjectBudget[];
#define TYPE_parse_UGCProjectBudget UGCProjectBudget

extern ParseTable parse_UGCPerProjectEncounterRank[];
#define TYPE_parse_UGCPerProjectEncounterRank UGCPerProjectEncounterRank

extern ParseTable parse_UGCCostumeNWPartDef[];
#define TYPE_parse_UGCCostumeNWPartDef UGCCostumeNWPartDef

extern ParseTable parse_UGCCostumeNWRegionModeDef[];
#define TYPE_parse_UGCCostumeNWRegionModeDef UGCCostumeNWRegionModeDef

extern ParseTable parse_UGCCostumeRegionDef[];
#define TYPE_parse_UGCCostumeRegionDef UGCCostumeRegionDef

extern ParseTable parse_UGCCostumeSlotDef[];
#define TYPE_parse_UGCCostumeSlotDef UGCCostumeSlotDef

extern ParseTable parse_UGCCostumeSkeletonSlotDef[];
#define TYPE_parse_UGCCostumeSkeletonSlotDef UGCCostumeSkeletonSlotDef

extern ParseTable parse_UGCSpecialComponentDef[];
#define TYPE_parse_UGCSpecialComponentDef UGCSpecialComponentDef

extern ParseTable parse_UGCCostumeNamingConventionField[];
#define TYPE_parse_UGCCostumeNamingConventionField UGCCostumeNamingConventionField

extern ParseTable parse_UGCRect[];
#define TYPE_parse_UGCRect UGCRect

extern ParseTable parse_UGCOverworldMapRegion[];
#define TYPE_parse_UGCOverworldMapRegion UGCOverworldMapRegion

extern ParseTable parse_UGCCheckedAttribDef[];
#define TYPE_parse_UGCCheckedAttribDef UGCCheckedAttribDef

extern ParseTable parse_UGCPerProjectDefaults[];
#define TYPE_parse_UGCPerProjectDefaults UGCPerProjectDefaults

extern ParseTable parse_UGCPetContactListMap[];
#define TYPE_parse_UGCPetContactListMap UGCPetContactListMap

extern ParseTable parse_UGCAllegianceRelation[];
#define TYPE_parse_UGCAllegianceRelation UGCAllegianceRelation

extern ParseTable parse_UGCRespecClassLevel[];
#define TYPE_parse_UGCRespecClassLevel UGCRespecClassLevel

extern ParseTable parse_UGCRespecClass[];
#define TYPE_parse_UGCRespecClass UGCRespecClass

extern ParseTable parse_UGCPerAllegianceDefaults[];
#define TYPE_parse_UGCPerAllegianceDefaults UGCPerAllegianceDefaults

extern ParseTable parse_UGCPortalClickableInfo[];
#define TYPE_parse_UGCPortalClickableInfo UGCPortalClickableInfo

extern ParseTable parse_UGCComponentPatrolPoint[];
#define TYPE_parse_UGCComponentPatrolPoint UGCComponentPatrolPoint

extern ParseTable parse_UGCComponentPatrolPath[];
#define TYPE_parse_UGCComponentPatrolPath UGCComponentPatrolPath

extern ParseTable parse_UGCTrapPointData[];
#define TYPE_parse_UGCTrapPointData UGCTrapPointData

extern ParseTable parse_UGCTrapSelfContained[];
#define TYPE_parse_UGCTrapSelfContained UGCTrapSelfContained

extern ParseTable parse_UGCTrapProperties[];
#define TYPE_parse_UGCTrapProperties UGCTrapProperties

extern ParseTable parse_UGCFreezeProjectMapInfo[];
#define TYPE_parse_UGCFreezeProjectMapInfo UGCFreezeProjectMapInfo

extern ParseTable parse_UGCFreezeProjectCostumeInfo[];
#define TYPE_parse_UGCFreezeProjectCostumeInfo UGCFreezeProjectCostumeInfo

extern ParseTable parse_UGCFreezeProjectInfo[];
#define TYPE_parse_UGCFreezeProjectInfo UGCFreezeProjectInfo

extern ParseTable parse_UGCComponentValidPosition[];
#define TYPE_parse_UGCComponentValidPosition UGCComponentValidPosition

extern ParseTable parse_UGCCostumeOverride[];
#define TYPE_parse_UGCCostumeOverride UGCCostumeOverride

extern ParseTable parse_UGCInteriorLightingProps[];
#define TYPE_parse_UGCInteriorLightingProps UGCInteriorLightingProps

extern ParseTable parse_WorldUGCActorCostumeProperties[];
#define TYPE_parse_WorldUGCActorCostumeProperties WorldUGCActorCostumeProperties

extern ParseTable parse_WorldUGCActorProperties[];
#define TYPE_parse_WorldUGCActorProperties WorldUGCActorProperties

extern ParseTable parse_WorldUGCGroupDefProperties[];
#define TYPE_parse_WorldUGCGroupDefProperties WorldUGCGroupDefProperties

extern ParseTable parse_WorldUGCFSMProperties[];
#define TYPE_parse_WorldUGCFSMProperties WorldUGCFSMProperties

extern ParseTable parse_WorldUGCProperties[];
#define TYPE_parse_WorldUGCProperties WorldUGCProperties

extern ParseTable parse_UGCResourceInfo[];
#define TYPE_parse_UGCResourceInfo UGCResourceInfo

extern ParseTable parse_UGCAssetTag[];
#define TYPE_parse_UGCAssetTag UGCAssetTag

extern ParseTable parse_UGCAssetTagCategory[];
#define TYPE_parse_UGCAssetTagCategory UGCAssetTagCategory

extern ParseTable parse_UGCAssetTagType[];
#define TYPE_parse_UGCAssetTagType UGCAssetTagType

#endif
