#include "textparser.h"

//auto-generated staticdefine for enum UGCBudgetType
//autogeneratednocheckin
StaticDefineInt UGCBudgetTypeEnum[] =
{
	DEFINE_INT
	{ "MAP", UGC_BUDGET_TYPE_MAP},
	{ "COMPONENT", UGC_BUDGET_TYPE_COMPONENT},
	{ "COSTUME", UGC_BUDGET_TYPE_COSTUME},
	{ "OBJECTIVE", UGC_BUDGET_TYPE_OBJECTIVE},
	{ "LIGHT", UGC_BUDGET_TYPE_LIGHT},
	{ "ITEM", UGC_BUDGET_TYPE_ITEM},
	{ "DIALOG_TREE_PROMPT", UGC_BUDGET_TYPE_DIALOG_TREE_PROMPT},
	DEFINE_END
};
void autoEnum_fixup_UGCBudgetType(void)
{
	static bool bOnce = false; if (bOnce) return; bOnce = true;
	RegisterNamedStaticDefine(UGCBudgetTypeEnum, "UGCBudgetType");
}

//auto-generated staticdefine for enum UGCCostumeOverrideType
//autogeneratednocheckin
StaticDefineInt UGCCostumeOverrideTypeEnum[] =
{
	DEFINE_INT
	{ "NONE", UGC_COSTUME_OVERRIDE_NONE},
	{ "SKIN_COLOR", UGC_COSTUME_OVERRIDE_SKIN_COLOR},
	{ "SLOT", UGC_COSTUME_OVERRIDE_SLOT},
	{ "SLOT_COLOR", UGC_COSTUME_OVERRIDE_SLOT_COLOR},
	{ "PART_GEOMETRY", UGC_COSTUME_OVERRIDE_PART_GEOMETRY},
	{ "PART_MATERIAL", UGC_COSTUME_OVERRIDE_PART_MATERIAL},
	{ "PART_TEXTURE0", UGC_COSTUME_OVERRIDE_PART_TEXTURE0},
	{ "PART_TEXTURE1", UGC_COSTUME_OVERRIDE_PART_TEXTURE1},
	{ "PART_TEXTURE2", UGC_COSTUME_OVERRIDE_PART_TEXTURE2},
	{ "PART_TEXTURE3", UGC_COSTUME_OVERRIDE_PART_TEXTURE3},
	{ "PART_COLOR", UGC_COSTUME_OVERRIDE_PART_COLOR},
	{ "ENTIRE_COSTUME", UGC_COSTUME_OVERRIDE_ENTIRE_COSTUME},
	DEFINE_END
};
void autoEnum_fixup_UGCCostumeOverrideType(void)
{
	static bool bOnce = false; if (bOnce) return; bOnce = true;
	RegisterNamedStaticDefine(UGCCostumeOverrideTypeEnum, "UGCCostumeOverrideType");
}
//autogeneratednocheckin
extern ParseTable parse_UGCFSMExternVar[];
#define TYPE_parse_UGCFSMExternVar UGCFSMExternVar
//Structparser.exe autogenerated ParseTable for struct UGCFSMMetadata
#define TYPE_parse_UGCFSMMetadata UGCFSMMetadata
ParseTable parse_UGCFSMMetadata[] =
{
	{ "UGCFSMMetadata", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCFSMMetadata), 0, NULL, 0, NULL },
	{ "{",				TOK_START, 0 },
	{ "ExternVar",		TOK_STRUCT(UGCFSMMetadata, eaExternVars, parse_UGCFSMExternVar) },
	{ "}",				TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCFSMMetadata()
{
	int iSize = sizeof(UGCFSMMetadata);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCFSMMetadata, iSize, "UGCFSMMetadata", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct UGCFSMExternVarDef
#define TYPE_parse_UGCFSMExternVarDef UGCFSMExternVarDef
ParseTable parse_UGCFSMExternVarDef[] =
{
	{ "UGCFSMExternVarDef", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCFSMExternVarDef), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "name",				TOK_STRUCTPARAM | TOK_STRING(UGCFSMExternVarDef, name, 0), NULL },
	{ "DisplayName",		TOK_REFERENCE(UGCFSMExternVarDef, hDisplayName, 0, "Message") },
	{ "Tooltip",			TOK_REFERENCE(UGCFSMExternVarDef, hTooltip, 0, "Message") },
	{ "MinValue",			TOK_F32(UGCFSMExternVarDef, minValue, 0), NULL },
	{ "MaxValue",			TOK_F32(UGCFSMExternVarDef, maxValue, 0), NULL },
	{ "DefaultValue",		TOK_F32(UGCFSMExternVarDef, defaultValue, 0), NULL },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCFSMExternVarDef()
{
	int iSize = sizeof(UGCFSMExternVarDef);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCFSMExternVarDef, iSize, "UGCFSMExternVarDef", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_UGCFSMExternVarDef[];
#define TYPE_parse_UGCFSMExternVarDef UGCFSMExternVarDef
//Structparser.exe autogenerated ParseTable for struct UGCFSMExternVar
#define TYPE_parse_UGCFSMExternVar UGCFSMExternVar
ParseTable parse_UGCFSMExternVar[] =
{
	{ "UGCFSMExternVar", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCFSMExternVar), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "Name",				TOK_POOL_STRING | TOK_STRING(UGCFSMExternVar, astrName, 0), NULL },
	{ "Type",				TOK_AUTOINT(UGCFSMExternVar, type, 0), NULL },
	{ "scType",				TOK_STRING(UGCFSMExternVar, scType, 0), NULL },
	{ "DefProps",			TOK_EMBEDDEDSTRUCT(UGCFSMExternVar, defProps, parse_UGCFSMExternVarDef)},
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCFSMExternVar()
{
	int iSize = sizeof(UGCFSMExternVar);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCFSMExternVar, iSize, "UGCFSMExternVar", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_PlayerCostume[];
#define TYPE_parse_PlayerCostume PlayerCostume
extern ParseTable parse_PCPart[];
#define TYPE_parse_PCPart PCPart
//Structparser.exe autogenerated ParseTable for struct UGCCostumeMetadata
#define TYPE_parse_UGCCostumeMetadata UGCCostumeMetadata
ParseTable parse_UGCCostumeMetadata[] =
{
	{ "UGCCostumeMetadata", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCCostumeMetadata), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "FullCostume",		TOK_OPTIONALSTRUCT(UGCCostumeMetadata, pFullCostume, parse_PlayerCostume) },
	{ "ItemPart",			TOK_STRUCT(UGCCostumeMetadata, eaItemParts, parse_PCPart) },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCCostumeMetadata()
{
	int iSize = sizeof(UGCCostumeMetadata);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCCostumeMetadata, iSize, "UGCCostumeMetadata", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_UGCDefChildMetadata[];
#define TYPE_parse_UGCDefChildMetadata UGCDefChildMetadata
extern ParseTable parse_ZoneMapMetadataPathNode[];
#define TYPE_parse_ZoneMapMetadataPathNode ZoneMapMetadataPathNode
//Structparser.exe autogenerated ParseTable for struct UGCGroupDefMetadata
#define TYPE_parse_UGCGroupDefMetadata UGCGroupDefMetadata
ParseTable parse_UGCGroupDefMetadata[] =
{
	{ "UGCGroupDefMetadata", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCGroupDefMetadata), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "UGCClusterChild",		TOK_STRUCT(UGCGroupDefMetadata, eaClusterChildren, parse_UGCDefChildMetadata) },
	{ "UGCPathNode",			TOK_STRUCT(UGCGroupDefMetadata, eaPathNodes, parse_ZoneMapMetadataPathNode) },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCGroupDefMetadata()
{
	int iSize = sizeof(UGCGroupDefMetadata);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCGroupDefMetadata, iSize, "UGCGroupDefMetadata", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct UGCDefChildMetadata
#define TYPE_parse_UGCDefChildMetadata UGCDefChildMetadata
ParseTable parse_UGCDefChildMetadata[] =
{
	{ "UGCDefChildMetadata", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCDefChildMetadata), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "DefUID",					TOK_AUTOINT(UGCDefChildMetadata, defUID, 0), NULL },
	{ "DefDebugName",			TOK_STRING(UGCDefChildMetadata, astrDefDebugName, 0), NULL },
	{ "Pos",					TOK_VEC3(UGCDefChildMetadata, pos), NULL },
	{ "Rot",					TOK_F32(UGCDefChildMetadata, rot, 0), NULL },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCDefChildMetadata()
{
	int iSize = sizeof(UGCDefChildMetadata);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCDefChildMetadata, iSize, "UGCDefChildMetadata", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct UGCProjectBudget
#define TYPE_parse_UGCProjectBudget UGCProjectBudget
ParseTable parse_UGCProjectBudget[] =
{
	{ "UGCProjectBudget", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCProjectBudget), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "Type",				TOK_AUTOINT(UGCProjectBudget, eType, 0), UGCBudgetTypeEnum },
	{ "ComponentType",		TOK_AUTOINT(UGCProjectBudget, eComponentType, 0), UGCComponentTypeEnum },
	{ "SoftLimit",			TOK_AUTOINT(UGCProjectBudget, iSoftLimit, 0), NULL },
	{ "HardLimit",			TOK_AUTOINT(UGCProjectBudget, iHardLimit, 0), NULL },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCProjectBudget()
{
	int iSize = sizeof(UGCProjectBudget);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCProjectBudget, iSize, "UGCProjectBudget", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct UGCPerProjectEncounterRank
#define TYPE_parse_UGCPerProjectEncounterRank UGCPerProjectEncounterRank
ParseTable parse_UGCPerProjectEncounterRank[] =
{
	{ "UGCPerProjectEncounterRank", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCPerProjectEncounterRank), 0, NULL, 0, NULL },
	{ "{",							TOK_START, 0 },
	{ "RankName",					TOK_STRUCTPARAM | TOK_POOL_STRING | TOK_STRING(UGCPerProjectEncounterRank, pcRankName, 0), NULL },
	{ "MarkerImage",				TOK_STRING(UGCPerProjectEncounterRank, pcMarkerTex, 0), NULL },
	{ "}",							TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCPerProjectEncounterRank()
{
	int iSize = sizeof(UGCPerProjectEncounterRank);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCPerProjectEncounterRank, iSize, "UGCPerProjectEncounterRank", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct UGCCostumeNWPartDef
#define TYPE_parse_UGCCostumeNWPartDef UGCCostumeNWPartDef
ParseTable parse_UGCCostumeNWPartDef[] =
{
	{ "UGCCostumeNWPartDef", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCCostumeNWPartDef), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "Name",					TOK_POOL_STRING | TOK_STRING(UGCCostumeNWPartDef, astrName, 0), NULL },
	{ "EnableGeometry",			TOK_AUTOINT(UGCCostumeNWPartDef, enableGeometry, 0), NULL },
	{ "EnableMaterial",			TOK_AUTOINT(UGCCostumeNWPartDef, enableMaterial, 0), NULL },
	{ "EnableTextures",			TOK_AUTOINT(UGCCostumeNWPartDef, enableTextures, 0), NULL },
	{ "EnableColors",			TOK_AUTOINT(UGCCostumeNWPartDef, enableColors, 0), NULL },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCCostumeNWPartDef()
{
	int iSize = sizeof(UGCCostumeNWPartDef);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCCostumeNWPartDef, iSize, "UGCCostumeNWPartDef", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_UGCCostumeNWPartDef[];
#define TYPE_parse_UGCCostumeNWPartDef UGCCostumeNWPartDef
//Structparser.exe autogenerated ParseTable for struct UGCCostumeNWRegionModeDef
#define TYPE_parse_UGCCostumeNWRegionModeDef UGCCostumeNWRegionModeDef
ParseTable parse_UGCCostumeNWRegionModeDef[] =
{
	{ "UGCCostumeNWRegionModeDef", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCCostumeNWRegionModeDef), 0, NULL, 0, NULL },
	{ "{",							TOK_START, 0 },
	{ "Part",						TOK_STRUCT(UGCCostumeNWRegionModeDef, eaParts, parse_UGCCostumeNWPartDef) },
	{ "BodyScale",					TOK_POOL_STRING | TOK_STRINGARRAY(UGCCostumeNWRegionModeDef, eaBodyScales), NULL },
	{ "ScaleInfo",					TOK_POOL_STRING | TOK_STRINGARRAY(UGCCostumeNWRegionModeDef, eaScaleInfos), NULL },
	{ "}",							TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCCostumeNWRegionModeDef()
{
	int iSize = sizeof(UGCCostumeNWRegionModeDef);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCCostumeNWRegionModeDef, iSize, "UGCCostumeNWRegionModeDef", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_UGCCostumeNWRegionModeDef[];
#define TYPE_parse_UGCCostumeNWRegionModeDef UGCCostumeNWRegionModeDef
extern ParseTable parse_UGCCostumeNWRegionModeDef[];
#define TYPE_parse_UGCCostumeNWRegionModeDef UGCCostumeNWRegionModeDef
//Structparser.exe autogenerated ParseTable for struct UGCCostumeRegionDef
#define TYPE_parse_UGCCostumeRegionDef UGCCostumeRegionDef
ParseTable parse_UGCCostumeRegionDef[] =
{
	{ "UGCCostumeRegionDef", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCCostumeRegionDef), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "astrName",				TOK_STRUCTPARAM | TOK_POOL_STRING | TOK_STRING(UGCCostumeRegionDef, astrName, 0), NULL },
	{ "BoneInclude",			TOK_POOL_STRING | TOK_STRINGARRAY(UGCCostumeRegionDef, eaBonesInclude), NULL },
	{ "BoneExclude",			TOK_POOL_STRING | TOK_STRINGARRAY(UGCCostumeRegionDef, eaBonesExclude), NULL },
	{ "BodyScaleInclude",		TOK_POOL_STRING | TOK_STRINGARRAY(UGCCostumeRegionDef, eaBodyScalesInclude), NULL },
	{ "BodyScaleExclude",		TOK_POOL_STRING | TOK_STRINGARRAY(UGCCostumeRegionDef, eaBodyScalesExclude), NULL },
	{ "ScaleGroup",				TOK_POOL_STRING | TOK_STRINGARRAY(UGCCostumeRegionDef, eaScaleGroups), NULL },
	{ "NWBasic",				TOK_EMBEDDEDSTRUCT(UGCCostumeRegionDef, nwBasic, parse_UGCCostumeNWRegionModeDef)},
	{ "NWAdvanced",				TOK_EMBEDDEDSTRUCT(UGCCostumeRegionDef, nwAdvanced, parse_UGCCostumeNWRegionModeDef)},
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCCostumeRegionDef()
{
	int iSize = sizeof(UGCCostumeRegionDef);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCCostumeRegionDef, iSize, "UGCCostumeRegionDef", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct UGCCostumeSlotDef
#define TYPE_parse_UGCCostumeSlotDef UGCCostumeSlotDef
ParseTable parse_UGCCostumeSlotDef[] =
{
	{ "UGCCostumeSlotDef", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCCostumeSlotDef), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "Name",				TOK_POOL_STRING | TOK_STRING(UGCCostumeSlotDef, astrName, 0), NULL },
	{ "DisplayName",		TOK_POOL_STRING | TOK_REFERENCE(UGCCostumeSlotDef, hDisplayName, 0, "Message") },
	{ "Tooltip",			TOK_POOL_STRING | TOK_REFERENCE(UGCCostumeSlotDef, hTooltip, 0, "Message") },
	{ "Bone",				TOK_POOL_STRING | TOK_STRINGARRAY(UGCCostumeSlotDef, eaBones), NULL },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCCostumeSlotDef()
{
	int iSize = sizeof(UGCCostumeSlotDef);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCCostumeSlotDef, iSize, "UGCCostumeSlotDef", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_UGCCostumeSlotDef[];
#define TYPE_parse_UGCCostumeSlotDef UGCCostumeSlotDef
//Structparser.exe autogenerated ParseTable for struct UGCCostumeSkeletonSlotDef
#define TYPE_parse_UGCCostumeSkeletonSlotDef UGCCostumeSkeletonSlotDef
ParseTable parse_UGCCostumeSkeletonSlotDef[] =
{
	{ "UGCCostumeSkeletonSlotDef", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCCostumeSkeletonSlotDef), 0, NULL, 0, NULL },
	{ "{",							TOK_START, 0 },
	{ "Name",						TOK_POOL_STRING | TOK_STRING(UGCCostumeSkeletonSlotDef, astrName, 0), NULL },
	{ "SlotDef",					TOK_STRUCT(UGCCostumeSkeletonSlotDef, eaSlotDef, parse_UGCCostumeSlotDef) },
	{ "}",							TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCCostumeSkeletonSlotDef()
{
	int iSize = sizeof(UGCCostumeSkeletonSlotDef);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCCostumeSkeletonSlotDef, iSize, "UGCCostumeSkeletonSlotDef", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct UGCSpecialComponentDef
#define TYPE_parse_UGCSpecialComponentDef UGCSpecialComponentDef
ParseTable parse_UGCSpecialComponentDef[] =
{
	{ "UGCSpecialComponentDef", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCSpecialComponentDef), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "Label",					TOK_STRUCTPARAM | TOK_STRING(UGCSpecialComponentDef, pcLabel, 0), NULL },
	{ "MessageKey",				TOK_POOL_STRING | TOK_STRING(UGCSpecialComponentDef, astrMessageKey, 0), NULL },
	{ "DescriptionMessageKey",	TOK_POOL_STRING | TOK_STRING(UGCSpecialComponentDef, astrDescriptionMessageKey, 0), NULL },
	{ "Type",					TOK_AUTOINT(UGCSpecialComponentDef, eType, 0), UGCComponentTypeEnum },
	{ "ObjectName",				TOK_POOL_STRING | TOK_STRING(UGCSpecialComponentDef, astrObjectName, 0), NULL },
	{ "TextureOverride",		TOK_STRING(UGCSpecialComponentDef, astrTextureOverride, 0), NULL },
	{ "RestrictToMapType",		TOK_AUTOINT(UGCSpecialComponentDef, eRestrictToMapType, 0), UGCMapTypeEnum },
	{ "SpaceOnly",				TOK_AUTOINT(UGCSpecialComponentDef, bSpaceOnly, 0), NULL },
	{ "GroundOnly",				TOK_AUTOINT(UGCSpecialComponentDef, bGroundOnly, 0), NULL },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCSpecialComponentDef()
{
	int iSize = sizeof(UGCSpecialComponentDef);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCSpecialComponentDef, iSize, "UGCSpecialComponentDef", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct UGCCostumeNamingConventionField
#define TYPE_parse_UGCCostumeNamingConventionField UGCCostumeNamingConventionField
ParseTable parse_UGCCostumeNamingConventionField[] =
{
	{ "UGCCostumeNamingConventionField", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCCostumeNamingConventionField), 0, NULL, 0, NULL },
	{ "{",									TOK_START, 0 },
	{ "FieldName",							TOK_STRUCTPARAM | TOK_STRING(UGCCostumeNamingConventionField, pcFieldName, 0), NULL },
	{ "Optional",							TOK_AUTOINT(UGCCostumeNamingConventionField, bOptional, 0), NULL },
	{ "Tooltip",							TOK_STRING(UGCCostumeNamingConventionField, pcTooltip, 0), NULL },
	{ "}",									TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCCostumeNamingConventionField()
{
	int iSize = sizeof(UGCCostumeNamingConventionField);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCCostumeNamingConventionField, iSize, "UGCCostumeNamingConventionField", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct UGCRect
#define TYPE_parse_UGCRect UGCRect
ParseTable parse_UGCRect[] =
{
	{ "UGCRect", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCRect), 0, NULL, 0, NULL },
	{ "x",			TOK_STRUCTPARAM | TOK_F32(UGCRect, x, 0), NULL },
	{ "y",			TOK_STRUCTPARAM | TOK_F32(UGCRect, y, 0), NULL },
	{ "w",			TOK_STRUCTPARAM | TOK_F32(UGCRect, w, 0), NULL },
	{ "h",			TOK_STRUCTPARAM | TOK_F32(UGCRect, h, 0), NULL },
	{ "\n",			TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCRect()
{
	int iSize = sizeof(UGCRect);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCRect, iSize, "UGCRect", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_UGCMapLocation[];
#define TYPE_parse_UGCMapLocation UGCMapLocation
extern ParseTable parse_UGCRect[];
#define TYPE_parse_UGCRect UGCRect
//Structparser.exe autogenerated ParseTable for struct UGCOverworldMapRegion
#define TYPE_parse_UGCOverworldMapRegion UGCOverworldMapRegion
ParseTable parse_UGCOverworldMapRegion[] =
{
	{ "UGCOverworldMapRegion", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCOverworldMapRegion), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "MapName",				TOK_POOL_STRING | TOK_STRING(UGCOverworldMapRegion, astrMapName, 0), NULL },
	{ "MapLocation",			TOK_OPTIONALSTRUCT(UGCOverworldMapRegion, pMapLocation, parse_UGCMapLocation) },
	{ "Rect",					TOK_STRUCT(UGCOverworldMapRegion, eaRects, parse_UGCRect) },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCOverworldMapRegion()
{
	int iSize = sizeof(UGCOverworldMapRegion);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCOverworldMapRegion, iSize, "UGCOverworldMapRegion", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct UGCCheckedAttribDef
#define TYPE_parse_UGCCheckedAttribDef UGCCheckedAttribDef
ParseTable parse_UGCCheckedAttribDef[] =
{
	{ "UGCCheckedAttribDef", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCCheckedAttribDef), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "Name",					TOK_POOL_STRING | TOK_STRING(UGCCheckedAttribDef, name, 0), NULL },
	{ "DisplayName",			TOK_STRING(UGCCheckedAttribDef, displayName, 0), NULL },
	{ "PlayerExprText",			TOK_STRING(UGCCheckedAttribDef, playerExprText, 0), NULL },
	{ "TeamExprText",			TOK_STRING(UGCCheckedAttribDef, teamExprText, 0), NULL },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCCheckedAttribDef()
{
	int iSize = sizeof(UGCCheckedAttribDef);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCCheckedAttribDef, iSize, "UGCCheckedAttribDef", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_UGCDialogTreePrompt[];
#define TYPE_parse_UGCDialogTreePrompt UGCDialogTreePrompt
extern ParseTable parse_UGCPerAllegianceDefaults[];
#define TYPE_parse_UGCPerAllegianceDefaults UGCPerAllegianceDefaults
extern ParseTable parse_UGCPerProjectEncounterRank[];
#define TYPE_parse_UGCPerProjectEncounterRank UGCPerProjectEncounterRank
extern ParseTable parse_WorldVariableDef[];
#define TYPE_parse_WorldVariableDef WorldVariableDef
extern ParseTable parse_UGCCostumeSkeletonSlotDef[];
#define TYPE_parse_UGCCostumeSkeletonSlotDef UGCCostumeSkeletonSlotDef
extern ParseTable parse_UGCCostumeRegionDef[];
#define TYPE_parse_UGCCostumeRegionDef UGCCostumeRegionDef
extern ParseTable parse_UGCSpecialComponentDef[];
#define TYPE_parse_UGCSpecialComponentDef UGCSpecialComponentDef
extern ParseTable parse_UGCProjectBudget[];
#define TYPE_parse_UGCProjectBudget UGCProjectBudget
extern ParseTable parse_UGCCostumeNamingConventionField[];
#define TYPE_parse_UGCCostumeNamingConventionField UGCCostumeNamingConventionField
extern ParseTable parse_UGCOverworldMapRegion[];
#define TYPE_parse_UGCOverworldMapRegion UGCOverworldMapRegion
extern ParseTable parse_UGCCheckedAttribDef[];
#define TYPE_parse_UGCCheckedAttribDef UGCCheckedAttribDef
extern ParseTable parse_WorldSkyVolumeProperties[];
#define TYPE_parse_WorldSkyVolumeProperties WorldSkyVolumeProperties
//Structparser.exe autogenerated ParseTable for struct UGCPerProjectDefaults
#define TYPE_parse_UGCPerProjectDefaults UGCPerProjectDefaults
ParseTable parse_UGCPerProjectDefaults[] =
{
	{ "UGCPerProjectDefaults", 			TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCPerProjectDefaults), 0, NULL, 0, NULL },
	{ "{",								TOK_START, 0 },
	{ "AllegianceRestriction",			TOK_POOL_STRING | TOK_STRING(UGCPerProjectDefaults, pcAllegianceRestriction, 0), NULL },
	{ "DefaultTransitionPrompt",		TOK_OPTIONALSTRUCT(UGCPerProjectDefaults, pDefaultTransitionPrompt, parse_UGCDialogTreePrompt) },
	{ "NonCombatType",					TOK_AUTOINT(UGCPerProjectDefaults, nonCombatType, 0), MissionPlayTypeEnum },
	{ "CombatType",						TOK_AUTOINT(UGCPerProjectDefaults, combatType, 0), MissionPlayTypeEnum },
	{ "OverrideCategoryName",			TOK_STRING(UGCPerProjectDefaults, pcOverrideCategoryName, 0), NULL },
	{ "Allegiance",						TOK_STRUCT(UGCPerProjectDefaults, allegiance, parse_UGCPerAllegianceDefaults) },
	{ "Rank",							TOK_STRUCT(UGCPerProjectDefaults, ranks, parse_UGCPerProjectEncounterRank) },
	{ "MaxActorsInAggroDist",			TOK_AUTOINT(UGCPerProjectDefaults, iMaxActorsInAggroDist, 0), NULL },
	{ "MaxEnemyActorsInAggroDist",		TOK_AUTOINT(UGCPerProjectDefaults, iMaxEnemyActorsInAggroDist, 0), NULL },
	{ "MaxFriendlyActorsInAggroDist",	TOK_AUTOINT(UGCPerProjectDefaults, iMaxFriendlyActorsInAggroDist, 0), NULL },
	{ "VariableDef",					TOK_STRUCT(UGCPerProjectDefaults, variableDefs, parse_WorldVariableDef) },
	{ "Behavior",						TOK_STRING(UGCPerProjectDefaults, pcBehavior, 0), NULL },
	{ "NoCombatBehavior",				TOK_STRING(UGCPerProjectDefaults, pcNoCombatBehavior, 0), NULL },
	{ "TrapObject",						TOK_STRING(UGCPerProjectDefaults, pcTrapObject, 0), NULL },
	{ "CustomInteriorMap",				TOK_STRING(UGCPerProjectDefaults, pcCustomInteriorMap, 0), NULL },
	{ "InteriorSky",					TOK_REFERENCE(UGCPerProjectDefaults, hInteriorSky, 0, "SkyInfo") },
	{ "hInteriorClickyInteractionDef",	TOK_REFERENCE(UGCPerProjectDefaults, hInteriorClickyInteractionDef, 0, "InteractionDef") },
	{ "InteriorKillObject",				TOK_STRING(UGCPerProjectDefaults, pcInteriorKillObject, 0), NULL },
	{ "InteriorDetailObject",			TOK_STRING(UGCPerProjectDefaults, pcInteriorDetailObject, 0), NULL },
	{ "InteriorDestructibleObject",		TOK_STRING(UGCPerProjectDefaults, pcInteriorDestructibleObject, 0), NULL },
	{ "InteriorDoorObject",				TOK_STRING(UGCPerProjectDefaults, pcInteriorDoorObject, 0), NULL },
	{ "MaxRoomSize",					TOK_AUTOINT(UGCPerProjectDefaults, iMaxRoomSize, 0), NULL },
	{ "SpaceSky",						TOK_REFERENCE(UGCPerProjectDefaults, hSpaceSky, 0, "SkyInfo") },
	{ "hSpaceClickyInteractionDef",		TOK_REFERENCE(UGCPerProjectDefaults, hSpaceClickyInteractionDef, 0, "InteractionDef") },
	{ "SpaceKillObject",				TOK_STRING(UGCPerProjectDefaults, pcSpaceKillObject, 0), NULL },
	{ "SpaceDetailObject",				TOK_STRING(UGCPerProjectDefaults, pcSpaceDetailObject, 0), NULL },
	{ "SpaceDestructibleObject",		TOK_STRING(UGCPerProjectDefaults, pcSpaceDestructibleObject, 0), NULL },
	{ "SpacePlanetObject",				TOK_STRING(UGCPerProjectDefaults, pcSpacePlanetObject, 0), NULL },
	{ "SpaceRingObject",				TOK_STRING(UGCPerProjectDefaults, pcSpaceRingObject, 0), NULL },
	{ "SpaceSunObject",					TOK_STRING(UGCPerProjectDefaults, pcSpaceSunObject, 0), NULL },
	{ "SpaceAggroDistance",				TOK_F32(UGCPerProjectDefaults, fSpaceAggroDistance, 0), NULL },
	{ "SpaceMaxActorDistance",			TOK_F32(UGCPerProjectDefaults, fSpaceMaxActorDistance, 0), NULL },
	{ "GroundSky",						TOK_REFERENCE(UGCPerProjectDefaults, hGroundSky, 0, "SkyInfo") },
	{ "GroundBuildingObject",			TOK_STRING(UGCPerProjectDefaults, pcGroundBuildingObject, 0), NULL },
	{ "GroundAggroDistance",			TOK_F32(UGCPerProjectDefaults, fGroundAggroDistance, 0), NULL },
	{ "GroundMaxActorDistance",			TOK_F32(UGCPerProjectDefaults, fGroundMaxActorDistance, 0), NULL },
	{ "CostumeSkeletonDef",				TOK_STRUCT(UGCPerProjectDefaults, eaCostumeSkeletonDefs, parse_UGCCostumeSkeletonSlotDef) },
	{ "CostumeRegionDef",				TOK_STRUCT(UGCPerProjectDefaults, eaCostumeRegionDefs, parse_UGCCostumeRegionDef) },
	{ "CostumeRegionScale",				TOK_REDUNDANTNAME | TOK_STRUCT(UGCPerProjectDefaults, eaCostumeRegionDefs, parse_UGCCostumeRegionDef) },
	{ "ProgressionNodeTypeProject",		TOK_AUTOINT(UGCPerProjectDefaults, eProgressionNodeTypeProject, 0), GameProgressionNodeTypeEnum },
	{ "ProgressionNodeType1",			TOK_AUTOINT(UGCPerProjectDefaults, eProgressionNodeType1, 0), GameProgressionNodeTypeEnum },
	{ "ProgressionNodeType2",			TOK_AUTOINT(UGCPerProjectDefaults, eProgressionNodeType2, 0), GameProgressionNodeTypeEnum },
	{ "SpecialComponent",				TOK_STRUCT(UGCPerProjectDefaults, eaSpecialComponents, parse_UGCSpecialComponentDef) },
	{ "Budget",							TOK_STRUCT(UGCPerProjectDefaults, ppDefaultBudgets, parse_UGCProjectBudget) },
	{ "CostumeNameField",				TOK_STRUCT(UGCPerProjectDefaults, eaCostumeNamingConventionFields, parse_UGCCostumeNamingConventionField) },
	{ "MapRegion",						TOK_STRUCT(UGCPerProjectDefaults, eaMapRegions, parse_UGCOverworldMapRegion) },
	{ "Cutscene",						TOK_STRING(UGCPerProjectDefaults, pcDialogTreePromptCameraPosition, 0), NULL },
	{ "TetheringAllowed",				TOK_AUTOINT(UGCPerProjectDefaults, bTetheringAllowed, 0), NULL },
	{ "ExteriorsAllowNormalSnapping",	TOK_AUTOINT(UGCPerProjectDefaults, bExteriorsAllowNormalSnapping, 0), NULL },
	{ "CheckedAttrib",					TOK_STRUCT(UGCPerProjectDefaults, checkedAttribs, parse_UGCCheckedAttribDef) },
	{ "BoundsSkyFade",					TOK_OPTIONALSTRUCT(UGCPerProjectDefaults, boundary, parse_WorldSkyVolumeProperties) },
	{ "FallbackPromptText",				TOK_STRING(UGCPerProjectDefaults, strFallbackPromptText, 0), NULL },
	{ "UGCTag",							TOK_INTARRAY(UGCPerProjectDefaults, eaiUGCTags),  UGCTagEnum},
	{ "DefaultDoorMap",					TOK_IGNORE, 0 },
	{ "}",								TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCPerProjectDefaults()
{
	int iSize = sizeof(UGCPerProjectDefaults);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCPerProjectDefaults, iSize, "UGCPerProjectDefaults", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct UGCPetContactListMap
#define TYPE_parse_UGCPetContactListMap UGCPetContactListMap
ParseTable parse_UGCPetContactListMap[] =
{
	{ "UGCPetContactListMap", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCPetContactListMap), 0, NULL, 0, NULL },
	{ "srcContactList",			TOK_STRUCTPARAM | TOK_POOL_STRING | TOK_STRING(UGCPetContactListMap, srcContactList, 0), NULL },
	{ "destContactList",		TOK_STRUCTPARAM | TOK_POOL_STRING | TOK_STRING(UGCPetContactListMap, destContactList, 0), NULL },
	{ "\n",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCPetContactListMap()
{
	int iSize = sizeof(UGCPetContactListMap);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCPetContactListMap, iSize, "UGCPetContactListMap", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct UGCAllegianceRelation
#define TYPE_parse_UGCAllegianceRelation UGCAllegianceRelation
ParseTable parse_UGCAllegianceRelation[] =
{
	{ "UGCAllegianceRelation", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCAllegianceRelation), 0, NULL, 0, NULL },
	{ "FilterValue",			TOK_STRUCTPARAM | TOK_STRING(UGCAllegianceRelation, pcFilterValue, 0), NULL },
	{ "AllegianceTagName",		TOK_STRUCTPARAM | TOK_STRING(UGCAllegianceRelation, pcTagName, 0), NULL },
	{ "\n",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCAllegianceRelation()
{
	int iSize = sizeof(UGCAllegianceRelation);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCAllegianceRelation, iSize, "UGCAllegianceRelation", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct UGCRespecClassLevel
#define TYPE_parse_UGCRespecClassLevel UGCRespecClassLevel
ParseTable parse_UGCRespecClassLevel[] =
{
	{ "UGCRespecClassLevel", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCRespecClassLevel), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "Level",					TOK_STRUCTPARAM | TOK_AUTOINT(UGCRespecClassLevel, iLevel, 0), NULL },
	{ "RewardTable",			TOK_REFERENCE(UGCRespecClassLevel, hRewardTable, 0, "RewardTable") },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCRespecClassLevel()
{
	int iSize = sizeof(UGCRespecClassLevel);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCRespecClassLevel, iSize, "UGCRespecClassLevel", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_UGCRespecClassLevel[];
#define TYPE_parse_UGCRespecClassLevel UGCRespecClassLevel
//Structparser.exe autogenerated ParseTable for struct UGCRespecClass
#define TYPE_parse_UGCRespecClass UGCRespecClass
ParseTable parse_UGCRespecClass[] =
{
	{ "UGCRespecClass", 		TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCRespecClass), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "hRespecClassName",	TOK_STRUCTPARAM | TOK_REFERENCE(UGCRespecClass, hRespecClassName, 0, "CharacterPath") },
	{ "Level",				TOK_STRUCT(UGCRespecClass, eaLevels, parse_UGCRespecClassLevel) },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCRespecClass()
{
	int iSize = sizeof(UGCRespecClass);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCRespecClass, iSize, "UGCRespecClass", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_UGCPetContactListMap[];
#define TYPE_parse_UGCPetContactListMap UGCPetContactListMap
extern ParseTable parse_UGCAllegianceRelation[];
#define TYPE_parse_UGCAllegianceRelation UGCAllegianceRelation
extern ParseTable parse_UGCRespecClass[];
#define TYPE_parse_UGCRespecClass UGCRespecClass
//Structparser.exe autogenerated ParseTable for struct UGCPerAllegianceDefaults
#define TYPE_parse_UGCPerAllegianceDefaults UGCPerAllegianceDefaults
ParseTable parse_UGCPerAllegianceDefaults[] =
{
	{ "UGCPerAllegianceDefaults", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCPerAllegianceDefaults), 0, NULL, 0, NULL },
	{ "{",							TOK_START, 0 },
	{ "AllegianceName",				TOK_STRUCTPARAM | TOK_POOL_STRING | TOK_STRING(UGCPerAllegianceDefaults, allegianceName, 0), NULL },
	{ "DefaultDoorMap",				TOK_STRING(UGCPerAllegianceDefaults, pcDefaultCrypticMap, 0), NULL },
	{ "Map",						TOK_STRUCT(UGCPerAllegianceDefaults, maps, parse_UGCPetContactListMap) },
	{ "Relation",					TOK_STRUCT(UGCPerAllegianceDefaults, relations, parse_UGCAllegianceRelation) },
	{ "RespecClass",				TOK_STRUCT(UGCPerAllegianceDefaults, respecClasses, parse_UGCRespecClass) },
	{ "}",							TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCPerAllegianceDefaults()
{
	int iSize = sizeof(UGCPerAllegianceDefaults);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCPerAllegianceDefaults, iSize, "UGCPerAllegianceDefaults", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct UGCPortalClickableInfo
#define TYPE_parse_UGCPortalClickableInfo UGCPortalClickableInfo
ParseTable parse_UGCPortalClickableInfo[] =
{
	{ "UGCPortalClickableInfo", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCPortalClickableInfo), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "mission_name",			TOK_STRING(UGCPortalClickableInfo, mission_name, 0), NULL },
	{ "layout_name",			TOK_STRING(UGCPortalClickableInfo, layout_name, 0), NULL },
	{ "room_name",				TOK_STRING(UGCPortalClickableInfo, room_name, 0), NULL },
	{ "challenge_name",			TOK_STRING(UGCPortalClickableInfo, challenge_name, 0), NULL },
	{ "is_volume",				TOK_AUTOINT(UGCPortalClickableInfo, is_volume, 0), NULL },
	{ "is_whole_map",			TOK_AUTOINT(UGCPortalClickableInfo, is_whole_map, 0), NULL },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCPortalClickableInfo()
{
	int iSize = sizeof(UGCPortalClickableInfo);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCPortalClickableInfo, iSize, "UGCPortalClickableInfo", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct UGCComponentPatrolPoint
#define TYPE_parse_UGCComponentPatrolPoint UGCComponentPatrolPoint
ParseTable parse_UGCComponentPatrolPoint[] =
{
	{ "UGCComponentPatrolPoint", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCComponentPatrolPoint), 0, NULL, 0, NULL },
	{ "{",							TOK_START, 0 },
	{ "ComponentID",				TOK_AUTOINT(UGCComponentPatrolPoint, componentID, 0), NULL },
	{ "Position",					TOK_VEC3(UGCComponentPatrolPoint, pos), NULL },
	{ "RoomID",						TOK_AUTOINT(UGCComponentPatrolPoint, roomID, 0), NULL },
	{ "prevConnectionInvalid",		TOK_AUTOINT(UGCComponentPatrolPoint, prevConnectionInvalid, 0), NULL },
	{ "nextConnectionInvalid",		TOK_AUTOINT(UGCComponentPatrolPoint, nextConnectionInvalid, 0), NULL },
	{ "}",							TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCComponentPatrolPoint()
{
	int iSize = sizeof(UGCComponentPatrolPoint);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCComponentPatrolPoint, iSize, "UGCComponentPatrolPoint", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_UGCComponentPatrolPoint[];
#define TYPE_parse_UGCComponentPatrolPoint UGCComponentPatrolPoint
//Structparser.exe autogenerated ParseTable for struct UGCComponentPatrolPath
#define TYPE_parse_UGCComponentPatrolPath UGCComponentPatrolPath
ParseTable parse_UGCComponentPatrolPath[] =
{
	{ "UGCComponentPatrolPath", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCComponentPatrolPath), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "PatrolPath",				TOK_AUTOINT(UGCComponentPatrolPath, patrolType, 0), WorldPatrolRouteTypeEnum },
	{ "PatrolPoint",			TOK_STRUCT(UGCComponentPatrolPath, points, parse_UGCComponentPatrolPoint) },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCComponentPatrolPath()
{
	int iSize = sizeof(UGCComponentPatrolPath);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCComponentPatrolPath, iSize, "UGCComponentPatrolPath", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct UGCTrapPointData
#define TYPE_parse_UGCTrapPointData UGCTrapPointData
ParseTable parse_UGCTrapPointData[] =
{
	{ "UGCTrapPointData", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCTrapPointData), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "id",					TOK_AUTOINT(UGCTrapPointData, id, 0), NULL },
	{ "pos",				TOK_VEC3(UGCTrapPointData, pos), NULL },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCTrapPointData()
{
	int iSize = sizeof(UGCTrapPointData);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCTrapPointData, iSize, "UGCTrapPointData", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_GroupVolumeProperties[];
#define TYPE_parse_GroupVolumeProperties GroupVolumeProperties
//Structparser.exe autogenerated ParseTable for struct UGCTrapSelfContained
#define TYPE_parse_UGCTrapSelfContained UGCTrapSelfContained
ParseTable parse_UGCTrapSelfContained[] =
{
	{ "UGCTrapSelfContained", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCTrapSelfContained), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "Volume",					TOK_OPTIONALSTRUCT(UGCTrapSelfContained, pVolume, parse_GroupVolumeProperties) },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCTrapSelfContained()
{
	int iSize = sizeof(UGCTrapSelfContained);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCTrapSelfContained, iSize, "UGCTrapSelfContained", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_UGCTrapSelfContained[];
#define TYPE_parse_UGCTrapSelfContained UGCTrapSelfContained
extern ParseTable parse_UGCTrapPointData[];
#define TYPE_parse_UGCTrapPointData UGCTrapPointData
//Structparser.exe autogenerated ParseTable for struct UGCTrapProperties
#define TYPE_parse_UGCTrapProperties UGCTrapProperties
ParseTable parse_UGCTrapProperties[] =
{
	{ "UGCTrapProperties", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCTrapProperties), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "SelfContained",		TOK_OPTIONALSTRUCT(UGCTrapProperties, pSelfContained, parse_UGCTrapSelfContained) },
	{ "Emitters",			TOK_STRUCT(UGCTrapProperties, eaEmitters, parse_UGCTrapPointData) },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCTrapProperties()
{
	int iSize = sizeof(UGCTrapProperties);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCTrapProperties, iSize, "UGCTrapProperties", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct UGCFreezeProjectMapInfo
#define TYPE_parse_UGCFreezeProjectMapInfo UGCFreezeProjectMapInfo
ParseTable parse_UGCFreezeProjectMapInfo[] =
{
	{ "UGCFreezeProjectMapInfo", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCFreezeProjectMapInfo), 0, NULL, 0, NULL },
	{ "{",							TOK_START, 0 },
	{ "MapName",					TOK_POOL_STRING | TOK_STRING(UGCFreezeProjectMapInfo, astrInternalMapName, 0), NULL },
	{ "OutMapName",					TOK_STRING(UGCFreezeProjectMapInfo, pcOutMapName, 0), NULL },
	{ "DisplayName",				TOK_STRING(UGCFreezeProjectMapInfo, pcDisplayName, 0), NULL },
	{ "MapDirectory",				TOK_STRING(UGCFreezeProjectMapInfo, pcMapDirectory, 0), NULL },
	{ "MapFile",					TOK_STRING(UGCFreezeProjectMapInfo, pcMapFile, 0), NULL },
	{ "MapLayerFile",				TOK_STRING(UGCFreezeProjectMapInfo, pcMapLayerFile, 0), NULL },
	{ "MapMissionFile1",			TOK_STRING(UGCFreezeProjectMapInfo, pcMapMissionFile1, 0), NULL },
	{ "MapMissionFile2",			TOK_STRING(UGCFreezeProjectMapInfo, pcMapMissionFile2, 0), NULL },
	{ "}",							TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCFreezeProjectMapInfo()
{
	int iSize = sizeof(UGCFreezeProjectMapInfo);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCFreezeProjectMapInfo, iSize, "UGCFreezeProjectMapInfo", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct UGCFreezeProjectCostumeInfo
#define TYPE_parse_UGCFreezeProjectCostumeInfo UGCFreezeProjectCostumeInfo
ParseTable parse_UGCFreezeProjectCostumeInfo[] =
{
	{ "UGCFreezeProjectCostumeInfo", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCFreezeProjectCostumeInfo), 0, NULL, 0, NULL },
	{ "{",								TOK_START, 0 },
	{ "CostumeName",					TOK_POOL_STRING | TOK_STRING(UGCFreezeProjectCostumeInfo, astrInternalCostumeName, 0), NULL },
	{ "CostumeNamePart",				TOK_STRINGARRAY(UGCFreezeProjectCostumeInfo, eaCostumeNameParts), NULL },
	{ "DisplayName",					TOK_STRING(UGCFreezeProjectCostumeInfo, pcDisplayName, 0), NULL },
	{ "CostumeFile",					TOK_STRING(UGCFreezeProjectCostumeInfo, pcCostumeFile, 0), NULL },
	{ "OutCostumeName",					TOK_STRING(UGCFreezeProjectCostumeInfo, pcOutCostumeName, 0), NULL },
	{ "}",								TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCFreezeProjectCostumeInfo()
{
	int iSize = sizeof(UGCFreezeProjectCostumeInfo);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCFreezeProjectCostumeInfo, iSize, "UGCFreezeProjectCostumeInfo", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_UGCFreezeProjectMapInfo[];
#define TYPE_parse_UGCFreezeProjectMapInfo UGCFreezeProjectMapInfo
extern ParseTable parse_UGCFreezeProjectCostumeInfo[];
#define TYPE_parse_UGCFreezeProjectCostumeInfo UGCFreezeProjectCostumeInfo
//Structparser.exe autogenerated ParseTable for struct UGCFreezeProjectInfo
#define TYPE_parse_UGCFreezeProjectInfo UGCFreezeProjectInfo
ParseTable parse_UGCFreezeProjectInfo[] =
{
	{ "UGCFreezeProjectInfo", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCFreezeProjectInfo), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "ProjectPrefix",			TOK_STRING(UGCFreezeProjectInfo, pcProjectPrefix, 0), NULL },
	{ "Map",					TOK_STRUCT(UGCFreezeProjectInfo, eaMaps, parse_UGCFreezeProjectMapInfo) },
	{ "Costume",				TOK_STRUCT(UGCFreezeProjectInfo, eaCostumes, parse_UGCFreezeProjectCostumeInfo) },
	{ "ProjectDirectory",		TOK_STRING(UGCFreezeProjectInfo, pcProjectDirectory, 0), NULL },
	{ "MissionFile",			TOK_STRING(UGCFreezeProjectInfo, pcMissionFile, 0), NULL },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCFreezeProjectInfo()
{
	int iSize = sizeof(UGCFreezeProjectInfo);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCFreezeProjectInfo, iSize, "UGCFreezeProjectInfo", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct UGCComponentValidPosition
#define TYPE_parse_UGCComponentValidPosition UGCComponentValidPosition
ParseTable parse_UGCComponentValidPosition[] =
{
	{ "UGCComponentValidPosition", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCComponentValidPosition), 0, NULL, 0, NULL },
	{ "{",							TOK_START, 0 },
	{ "position",					TOK_VEC3(UGCComponentValidPosition, position), NULL },
	{ "rotation",					TOK_F32(UGCComponentValidPosition, rotation, 0), NULL },
	{ "room_id",					TOK_AUTOINT(UGCComponentValidPosition, room_id, 0), NULL },
	{ "room_door",					TOK_AUTOINT(UGCComponentValidPosition, room_door, 0), NULL },
	{ "room_level",					TOK_AUTOINT(UGCComponentValidPosition, room_level, 0), NULL },
	{ "platform_height",			TOK_F32(UGCComponentValidPosition, platform_height, 0), NULL },
	{ "}",							TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCComponentValidPosition()
{
	int iSize = sizeof(UGCComponentValidPosition);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCComponentValidPosition, iSize, "UGCComponentValidPosition", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_PlayerCostume[];
#define TYPE_parse_PlayerCostume PlayerCostume
//Structparser.exe autogenerated ParseTable for struct UGCCostumeOverride
#define TYPE_parse_UGCCostumeOverride UGCCostumeOverride
ParseTable parse_UGCCostumeOverride[] =
{
	{ "UGCCostumeOverride", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCCostumeOverride), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "Type",				TOK_AUTOINT(UGCCostumeOverride, type, 0), UGCCostumeOverrideTypeEnum },
	{ "Name",				TOK_POOL_STRING | TOK_STRING(UGCCostumeOverride, astrName, 0), NULL },
	{ "ColorIndex",			TOK_AUTOINT(UGCCostumeOverride, colorIndex, 0), NULL },
	{ "StrValue",			TOK_STRING(UGCCostumeOverride, strValue, 0), NULL },
	{ "IntValue",			TOK_AUTOINT(UGCCostumeOverride, iValue, 0), NULL },
	{ "EntireCostume",		TOK_OPTIONALSTRUCT(UGCCostumeOverride, entireCostume, parse_PlayerCostume) },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCCostumeOverride()
{
	int iSize = sizeof(UGCCostumeOverride);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCCostumeOverride, iSize, "UGCCostumeOverride", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct UGCInteriorLightingProps
#define TYPE_parse_UGCInteriorLightingProps UGCInteriorLightingProps
ParseTable parse_UGCInteriorLightingProps[] =
{
	{ "UGCInteriorLightingProps", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCInteriorLightingProps), 0, NULL, 0, NULL },
	{ "{",							TOK_START, 0 },
	{ "child_light", 				TOK_IGNORE | TOK_FLATEMBED },
	{ "UID",						TOK_AUTOINT(UGCInteriorLightingProps, child_light.name_uid, 0), NULL },
	{ "Name",						TOK_STRING(UGCInteriorLightingProps, child_light.name_str, 0), NULL },
	{ "InnerAngle",					TOK_F32(UGCInteriorLightingProps, inner_angle, 0), NULL },
	{ "OuterAngle",					TOK_F32(UGCInteriorLightingProps, outer_angle, 0), NULL },
	{ "NoLights",					TOK_BIT, 0, 8, NULL},
	{ "}",							TOK_END, 0 },
	{ "", 0, 0 }
};
void FindAutoStructBitField(char *pStruct, int iAllocedSizeInWords, ParseTable *pTPIColumn);
int autoStruct_fixup_UGCInteriorLightingProps()
{
	int iSize = sizeof(UGCInteriorLightingProps);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCInteriorLightingProps, iSize, "UGCInteriorLightingProps", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	{
		int iSizeInWords = (sizeof(UGCInteriorLightingProps) + 7) / 4;
		UGCInteriorLightingProps *pTemp = alloca(iSizeInWords * 4);
		memset(pTemp, 0, iSizeInWords * 4);
		pTemp->no_lights = ~0;
		FindAutoStructBitField((char*)pTemp, iSizeInWords, &parse_UGCInteriorLightingProps[7]);
		pTemp->no_lights = 0;
	}
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct WorldUGCActorCostumeProperties
#define TYPE_parse_WorldUGCActorCostumeProperties WorldUGCActorCostumeProperties
ParseTable parse_WorldUGCActorCostumeProperties[] =
{
	{ "WorldUGCActorCostumeProperties", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(WorldUGCActorCostumeProperties), 0, NULL, 0, NULL },
	{ "{",								TOK_START, 0 },
	{ "Costume",						TOK_REFERENCE(WorldUGCActorCostumeProperties, hCostumeRef, 0, "PlayerCostume") },
	{ "CostumeName",					TOK_STRING(WorldUGCActorCostumeProperties, pcCostumeName, 0), NULL },
	{ "}",								TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_WorldUGCActorCostumeProperties()
{
	int iSize = sizeof(WorldUGCActorCostumeProperties);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_WorldUGCActorCostumeProperties, iSize, "WorldUGCActorCostumeProperties", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_DisplayMessage[];
#define TYPE_parse_DisplayMessage DisplayMessage
extern ParseTable parse_DisplayMessage[];
#define TYPE_parse_DisplayMessage DisplayMessage
extern ParseTable parse_WorldUGCActorCostumeProperties[];
#define TYPE_parse_WorldUGCActorCostumeProperties WorldUGCActorCostumeProperties
//Structparser.exe autogenerated ParseTable for struct WorldUGCActorProperties
#define TYPE_parse_WorldUGCActorProperties WorldUGCActorProperties
ParseTable parse_WorldUGCActorProperties[] =
{
	{ "WorldUGCActorProperties", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(WorldUGCActorProperties), 0, NULL, 0, NULL },
	{ "{",							TOK_START, 0 },
	{ "displayNameMsg",				TOK_EMBEDDEDSTRUCT(WorldUGCActorProperties, displayNameMsg, parse_DisplayMessage)},
	{ "groupDisplayNameMsg",		TOK_EMBEDDEDSTRUCT(WorldUGCActorProperties, groupDisplayNameMsg, parse_DisplayMessage)},
	{ "RankName",					TOK_POOL_STRING | TOK_STRING(WorldUGCActorProperties, pcRankName, 0), NULL },
	{ "Class",						TOK_STRING(WorldUGCActorProperties, pcClass, 0), NULL },
	{ "Costume",					TOK_STRUCT(WorldUGCActorProperties, eaCostumes, parse_WorldUGCActorCostumeProperties) },
	{ "}",							TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_WorldUGCActorProperties()
{
	int iSize = sizeof(WorldUGCActorProperties);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_WorldUGCActorProperties, iSize, "WorldUGCActorProperties", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_WorldUGCActorProperties[];
#define TYPE_parse_WorldUGCActorProperties WorldUGCActorProperties
//Structparser.exe autogenerated ParseTable for struct WorldUGCGroupDefProperties
#define TYPE_parse_WorldUGCGroupDefProperties WorldUGCGroupDefProperties
ParseTable parse_WorldUGCGroupDefProperties[] =
{
	{ "WorldUGCGroupDefProperties", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(WorldUGCGroupDefProperties), 0, NULL, 0, NULL },
	{ "{",							TOK_START, 0 },
	{ "RoomDoorsEverywhere",		TOK_AUTOINT(WorldUGCGroupDefProperties, bRoomDoorsEverywhere, 0), NULL },
	{ "ClickableName",				TOK_STRING(WorldUGCGroupDefProperties, strClickableName, 0), NULL },
	{ "EncounterActor",				TOK_STRUCT(WorldUGCGroupDefProperties, eaEncounterActors, parse_WorldUGCActorProperties) },
	{ "ActorProperties",			TOK_REDUNDANTNAME | TOK_STRUCT(WorldUGCGroupDefProperties, eaEncounterActors, parse_WorldUGCActorProperties) },
	{ "Cost",						TOK_AUTOINT(WorldUGCGroupDefProperties, iCost, 0), NULL },
	{ "DefaultSnapNormal",			TOK_AUTOINT(WorldUGCGroupDefProperties, bDefaultSnapNormal, 0), NULL },
	{ "}",							TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_WorldUGCGroupDefProperties()
{
	int iSize = sizeof(WorldUGCGroupDefProperties);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_WorldUGCGroupDefProperties, iSize, "WorldUGCGroupDefProperties", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_UGCFSMExternVarDef[];
#define TYPE_parse_UGCFSMExternVarDef UGCFSMExternVarDef
//Structparser.exe autogenerated ParseTable for struct WorldUGCFSMProperties
#define TYPE_parse_WorldUGCFSMProperties WorldUGCFSMProperties
ParseTable parse_WorldUGCFSMProperties[] =
{
	{ "WorldUGCFSMProperties", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(WorldUGCFSMProperties), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "HasPatrol",				TOK_AUTOINT(WorldUGCFSMProperties, bHasPatrol, 0), NULL },
	{ "PatrolType",				TOK_AUTOINT(WorldUGCFSMProperties, ePatrolType, 0), WorldPatrolRouteTypeEnum },
	{ "ExternVar",				TOK_STRUCT(WorldUGCFSMProperties, eaExternVars, parse_UGCFSMExternVarDef) },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_WorldUGCFSMProperties()
{
	int iSize = sizeof(WorldUGCFSMProperties);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_WorldUGCFSMProperties, iSize, "WorldUGCFSMProperties", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_DisplayMessage[];
#define TYPE_parse_DisplayMessage DisplayMessage
extern ParseTable parse_DisplayMessage[];
#define TYPE_parse_DisplayMessage DisplayMessage
extern ParseTable parse_DisplayMessage[];
#define TYPE_parse_DisplayMessage DisplayMessage
extern ParseTable parse_WorldUGCFactionRestrictionProperties[];
#define TYPE_parse_WorldUGCFactionRestrictionProperties WorldUGCFactionRestrictionProperties
extern ParseTable parse_WorldUGCActorProperties[];
#define TYPE_parse_WorldUGCActorProperties WorldUGCActorProperties
extern ParseTable parse_UGCFSMExternVarDef[];
#define TYPE_parse_UGCFSMExternVarDef UGCFSMExternVarDef
//Structparser.exe autogenerated ParseTable for struct WorldUGCProperties
#define TYPE_parse_WorldUGCProperties WorldUGCProperties
ParseTable parse_WorldUGCProperties[] =
{
	{ "WorldUGCProperties", 			TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(WorldUGCProperties), 0, NULL, 0, NULL },
	{ "{",							TOK_START, 0 },
	{ "VisibleName",				TOK_USEROPTIONBIT_1 | TOK_EMBEDDEDSTRUCT(WorldUGCProperties, dVisibleName, parse_DisplayMessage)},
	{ "Description",				TOK_USEROPTIONBIT_1 | TOK_EMBEDDEDSTRUCT(WorldUGCProperties, dDescription, parse_DisplayMessage)},
	{ "DefaultName",				TOK_USEROPTIONBIT_1 | TOK_EMBEDDEDSTRUCT(WorldUGCProperties, dDefaultName, parse_DisplayMessage)},
	{ "ImageOverride",				TOK_GLOBAL_NAME | TOK_POOL_STRING | TOK_STRING(WorldUGCProperties, pchImageOverride, 0), "Texture" },
	{ "NoDescription",				TOK_BOOLFLAG(WorldUGCProperties, bNoDescription, 0), NULL },
	{ "SortPriority",				TOK_AUTOINT(WorldUGCProperties, iSortPriority, 0), NULL },
	{ "restrictionProps", 			TOK_IGNORE | TOK_FLATEMBED },
	{ "MinLevel",					TOK_AUTOINT(WorldUGCProperties, restrictionProps.iMinLevel, 0), NULL },
	{ "MaxLevel",					TOK_AUTOINT(WorldUGCProperties, restrictionProps.iMaxLevel, 0), NULL },
	{ "Faction",					TOK_STRUCT(WorldUGCProperties, restrictionProps.eaFactions, parse_WorldUGCFactionRestrictionProperties) },
	{ "RestrictAllegiance",			TOK_REDUNDANTNAME | TOK_STRUCT(WorldUGCProperties, restrictionProps.eaFactions, parse_WorldUGCFactionRestrictionProperties) },
	{ "MapDefaultHeight",			TOK_F32(WorldUGCProperties, fMapDefaultHeight, 0), NULL },
	{ "DefaultHeight",				TOK_REDUNDANTNAME | TOK_F32(WorldUGCProperties, fMapDefaultHeight, 0), NULL },
	{ "MapOnlyPlatformsAreLegal",	TOK_AUTOINT(WorldUGCProperties, bMapOnlyPlatformsAreLegal, 0), NULL },
	{ "groupDefProps", 				TOK_IGNORE | TOK_FLATEMBED },
	{ "RoomDoorsEverywhere",		TOK_AUTOINT(WorldUGCProperties, groupDefProps.bRoomDoorsEverywhere, 0), NULL },
	{ "ClickableName",				TOK_STRING(WorldUGCProperties, groupDefProps.strClickableName, 0), NULL },
	{ "EncounterActor",				TOK_STRUCT(WorldUGCProperties, groupDefProps.eaEncounterActors, parse_WorldUGCActorProperties) },
	{ "ActorProperties",			TOK_REDUNDANTNAME | TOK_STRUCT(WorldUGCProperties, groupDefProps.eaEncounterActors, parse_WorldUGCActorProperties) },
	{ "Cost",						TOK_AUTOINT(WorldUGCProperties, groupDefProps.iCost, 0), NULL },
	{ "DefaultSnapNormal",			TOK_AUTOINT(WorldUGCProperties, groupDefProps.bDefaultSnapNormal, 0), NULL },
	{ "fsmProps", 					TOK_IGNORE | TOK_FLATEMBED },
	{ "HasPatrol",					TOK_AUTOINT(WorldUGCProperties, fsmProps.bHasPatrol, 0), NULL },
	{ "PatrolType",					TOK_AUTOINT(WorldUGCProperties, fsmProps.ePatrolType, 0), WorldPatrolRouteTypeEnum },
	{ "ExternVar",					TOK_STRUCT(WorldUGCProperties, fsmProps.eaExternVars, parse_UGCFSMExternVarDef) },
	{ "}",							TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_WorldUGCProperties()
{
	int iSize = sizeof(WorldUGCProperties);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_WorldUGCProperties, iSize, "WorldUGCProperties", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_ResourceInfo[];
#define TYPE_parse_ResourceInfo ResourceInfo
extern ParseTable parse_WorldUGCProperties[];
#define TYPE_parse_WorldUGCProperties WorldUGCProperties
extern ParseTable parse_UGCFSMMetadata[];
#define TYPE_parse_UGCFSMMetadata UGCFSMMetadata
extern ParseTable parse_UGCCostumeMetadata[];
#define TYPE_parse_UGCCostumeMetadata UGCCostumeMetadata
extern ParseTable parse_UGCGroupDefMetadata[];
#define TYPE_parse_UGCGroupDefMetadata UGCGroupDefMetadata
//Structparser.exe autogenerated ParseTable for struct UGCResourceInfo
#define TYPE_parse_UGCResourceInfo UGCResourceInfo
ParseTable parse_UGCResourceInfo[] =
{
	{ "UGCResourceInfo", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCResourceInfo), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "Name",				TOK_POOL_STRING | TOK_KEY | TOK_STRING(UGCResourceInfo, pcName, 0), NULL },
	{ "Filename",			TOK_POOL_STRING | TOK_CURRENTFILE(UGCResourceInfo, pcFilename), NULL},
	{ "ResInfo",			TOK_OPTIONALSTRUCT(UGCResourceInfo, pResInfo, parse_ResourceInfo) },
	{ "UGCProperties",		TOK_OPTIONALSTRUCT(UGCResourceInfo, pUGCProperties, parse_WorldUGCProperties) },
	{ "FSMMetadata",		TOK_OPTIONALSTRUCT(UGCResourceInfo, pFSMMetadata, parse_UGCFSMMetadata) },
	{ "CostumeMetadata",	TOK_OPTIONALSTRUCT(UGCResourceInfo, pCostumeMetadata, parse_UGCCostumeMetadata) },
	{ "DefMetadata",		TOK_OPTIONALSTRUCT(UGCResourceInfo, pDefMetadata, parse_UGCGroupDefMetadata) },
	{ "FSMExternVar",		TOK_IGNORE | TOK_IGNORE_STRUCT , 0 },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCResourceInfo()
{
	int iSize = sizeof(UGCResourceInfo);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCResourceInfo, iSize, "UGCResourceInfo", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct UGCAssetTag
#define TYPE_parse_UGCAssetTag UGCAssetTag
ParseTable parse_UGCAssetTag[] =
{
	{ "UGCAssetTag", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCAssetTag), 0, NULL, 0, NULL },
	{ "Name",			TOK_STRUCTPARAM | TOK_STRING(UGCAssetTag, pcName, 0), NULL },
	{ "DisplayName",	TOK_STRUCTPARAM | TOK_REFERENCE(UGCAssetTag, hDisplayName, 0, "Message") },
	{ "\n",				TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCAssetTag()
{
	int iSize = sizeof(UGCAssetTag);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCAssetTag, iSize, "UGCAssetTag", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_UGCAssetTag[];
#define TYPE_parse_UGCAssetTag UGCAssetTag
//Structparser.exe autogenerated ParseTable for struct UGCAssetTagCategory
#define TYPE_parse_UGCAssetTagCategory UGCAssetTagCategory
ParseTable parse_UGCAssetTagCategory[] =
{
	{ "UGCAssetTagCategory", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCAssetTagCategory), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "Name",					TOK_STRUCTPARAM | TOK_STRING(UGCAssetTagCategory, pcName, 0), NULL },
	{ "DisplayName",			TOK_REFERENCE(UGCAssetTagCategory, hDisplayName, 0, "Message") },
	{ "Tag",					TOK_STRUCT(UGCAssetTagCategory, eaTags, parse_UGCAssetTag) },
	{ "IsHidden",				TOK_AUTOINT(UGCAssetTagCategory, bIsHidden, 0), NULL },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCAssetTagCategory()
{
	int iSize = sizeof(UGCAssetTagCategory);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCAssetTagCategory, iSize, "UGCAssetTagCategory", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_UGCAssetTagCategory[];
#define TYPE_parse_UGCAssetTagCategory UGCAssetTagCategory
//Structparser.exe autogenerated ParseTable for struct UGCAssetTagType
#define TYPE_parse_UGCAssetTagType UGCAssetTagType
ParseTable parse_UGCAssetTagType[] =
{
	{ "UGCAssetTagType", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCAssetTagType), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "Name",				TOK_STRUCTPARAM | TOK_POOL_STRING | TOK_KEY | TOK_STRING(UGCAssetTagType, pcName, 0), NULL },
	{ "Filename",			TOK_POOL_STRING | TOK_CURRENTFILE(UGCAssetTagType, pcFilename), NULL},
	{ "Dictionary",			TOK_STRING(UGCAssetTagType, pcDictName, 0), NULL },
	{ "FilterByTypeName",	TOK_AUTOINT(UGCAssetTagType, bFilterType, 0), NULL },
	{ "DrawEditorOnly",		TOK_AUTOINT(UGCAssetTagType, bDrawEditorOnly, 0), NULL },
	{ "EnableIconGridView",	TOK_AUTOINT(UGCAssetTagType, bEnableIconGridView, 0), NULL },
	{ "PreferIconGridView",	TOK_AUTOINT(UGCAssetTagType, bPreferIconGridView, 0), NULL },
	{ "IsYTranslate",		TOK_AUTOINT(UGCAssetTagType, bIsYTranslate, 0), NULL },
	{ "TagCategory",		TOK_STRUCT(UGCAssetTagType, eaCategories, parse_UGCAssetTagCategory) },
	{ "SpaceModePreview",	TOK_IGNORE, 0 },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCAssetTagType()
{
	int iSize = sizeof(UGCAssetTagType);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCAssetTagType, iSize, "UGCAssetTagType", NULL, "NNOUGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
