#ifndef __NNOUGCCOMMON_C_AST_H_
#define __NNOUGCCOMMON_C_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \NNOUGCCommon.c
//autogeneratednocheckin

extern ParseTable parse_UGCResourceInfoDef[];
#define TYPE_parse_UGCResourceInfoDef UGCResourceInfoDef

extern ParseTable parse_UGCResourceInfoDefList[];
#define TYPE_parse_UGCResourceInfoDefList UGCResourceInfoDefList

extern ParseTable parse_UGCBacklinkTableComponentEntry[];
#define TYPE_parse_UGCBacklinkTableComponentEntry UGCBacklinkTableComponentEntry

#endif
