#ifndef __NNOUGCRESOURCE_H_AST_H_
#define __NNOUGCRESOURCE_H_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \NNOUGCResource.h
//autogeneratednocheckin

//auto-generated staticdefine for enum UGCInteractDuration
//autogeneratednocheckin
extern StaticDefineInt UGCInteractDurationEnum[];

//auto-generated staticdefine for enum UGCZOrderSort
//autogeneratednocheckin
extern StaticDefineInt UGCZOrderSortEnum[];

//auto-generated staticdefine for enum UGCComponentType
//autogeneratednocheckin
extern StaticDefineInt UGCComponentTypeEnum[];

//auto-generated staticdefine for enum UGCDialogTreePromptActionStyle
//autogeneratednocheckin
extern StaticDefineInt UGCDialogTreePromptActionStyleEnum[];

//auto-generated staticdefine for enum UGCDialogTreePromptType
//autogeneratednocheckin
extern StaticDefineInt UGCDialogTreePromptTypeEnum[];

//auto-generated staticdefine for enum UGCMissionObjectiveType
//autogeneratednocheckin
extern StaticDefineInt UGCMissionObjectiveTypeEnum[];

//auto-generated staticdefine for enum UGCWaypointMode
//autogeneratednocheckin
extern StaticDefineInt UGCWaypointModeEnum[];

//auto-generated staticdefine for enum UGCComponentHeightSnap
//autogeneratednocheckin
extern StaticDefineInt UGCComponentHeightSnapEnum[];

//auto-generated staticdefine for enum UGCWhenType
//autogeneratednocheckin
extern StaticDefineInt UGCWhenTypeEnum[];

extern ParseTable parse_UGCCheckedAttrib[];
#define TYPE_parse_UGCCheckedAttrib UGCCheckedAttrib

extern ParseTable parse_UGCInteractProperties[];
#define TYPE_parse_UGCInteractProperties UGCInteractProperties

extern ParseTable parse_UGCGenesisBackdropSkyOverride[];
#define TYPE_parse_UGCGenesisBackdropSkyOverride UGCGenesisBackdropSkyOverride

extern ParseTable parse_UGCGenesisBackdrop[];
#define TYPE_parse_UGCGenesisBackdrop UGCGenesisBackdrop

extern ParseTable parse_UGCGenesisSpace[];
#define TYPE_parse_UGCGenesisSpace UGCGenesisSpace

extern ParseTable parse_UGCGenesisPrefab[];
#define TYPE_parse_UGCGenesisPrefab UGCGenesisPrefab

extern ParseTable parse_UGCUnitializedMap[];
#define TYPE_parse_UGCUnitializedMap UGCUnitializedMap

extern ParseTable parse_UGCMap[];
#define TYPE_parse_UGCMap UGCMap

extern ParseTable parse_UGCDialogTreePromptAction[];
#define TYPE_parse_UGCDialogTreePromptAction UGCDialogTreePromptAction

extern ParseTable parse_UGCDialogTreePrompt[];
#define TYPE_parse_UGCDialogTreePrompt UGCDialogTreePrompt

extern ParseTable parse_UGCDialogTreeBlock[];
#define TYPE_parse_UGCDialogTreeBlock UGCDialogTreeBlock

extern ParseTable parse_UGCMissionMapLink[];
#define TYPE_parse_UGCMissionMapLink UGCMissionMapLink

extern ParseTable parse_UGCMission[];
#define TYPE_parse_UGCMission UGCMission

extern ParseTable parse_UGCMissionObjective[];
#define TYPE_parse_UGCMissionObjective UGCMissionObjective

extern ParseTable parse_UGCComponentList[];
#define TYPE_parse_UGCComponentList UGCComponentList

extern ParseTable parse_UGCComponentPlacement[];
#define TYPE_parse_UGCComponentPlacement UGCComponentPlacement

extern ParseTable parse_UGCWhenDialogPrompt[];
#define TYPE_parse_UGCWhenDialogPrompt UGCWhenDialogPrompt

extern ParseTable parse_UGCWhen[];
#define TYPE_parse_UGCWhen UGCWhen

extern ParseTable parse_UGCFSMVar[];
#define TYPE_parse_UGCFSMVar UGCFSMVar

extern ParseTable parse_UGCFSMProperties[];
#define TYPE_parse_UGCFSMProperties UGCFSMProperties

extern ParseTable parse_UGCRoomDetailData[];
#define TYPE_parse_UGCRoomDetailData UGCRoomDetailData

extern ParseTable parse_UGCComponent[];
#define TYPE_parse_UGCComponent UGCComponent

extern ParseTable parse_UGCCostumeSlot[];
#define TYPE_parse_UGCCostumeSlot UGCCostumeSlot

extern ParseTable parse_UGCCostumeScale[];
#define TYPE_parse_UGCCostumeScale UGCCostumeScale

extern ParseTable parse_UGCCostumePart[];
#define TYPE_parse_UGCCostumePart UGCCostumePart

extern ParseTable parse_UGCCostumeData[];
#define TYPE_parse_UGCCostumeData UGCCostumeData

extern ParseTable parse_UGCCostume[];
#define TYPE_parse_UGCCostume UGCCostume

extern ParseTable parse_UGCItem[];
#define TYPE_parse_UGCItem UGCItem

extern ParseTable parse_UGCSound[];
#define TYPE_parse_UGCSound UGCSound

extern ParseTable parse_UGCSoundDSP[];
#define TYPE_parse_UGCSoundDSP UGCSoundDSP

extern ParseTable parse_UGCTrapPowerGroup[];
#define TYPE_parse_UGCTrapPowerGroup UGCTrapPowerGroup

extern ParseTable parse_UGCProjectData[];
#define TYPE_parse_UGCProjectData UGCProjectData

#endif
