#ifndef __NNOUGCMISSIONCOMMON_H_AST_H_
#define __NNOUGCMISSIONCOMMON_H_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \NNOUGCMissionCommon.h
//autogeneratednocheckin

extern ParseTable parse_UGCMapTransitionInfo[];
#define TYPE_parse_UGCMapTransitionInfo UGCMapTransitionInfo

extern ParseTable parse_UGCMapInfo[];
#define TYPE_parse_UGCMapInfo UGCMapInfo

#endif
