#include "textparser.h"

//auto-generated staticdefine for enum UGCPlayStatus
//autogeneratednocheckin
StaticDefineInt UGCPlayStatusEnum[] =
{
	DEFINE_INT
	{ "SUCCESS", UGC_PLAY_SUCCESS},
	{ "WRONG_FACTION", UGC_PLAY_WRONG_FACTION},
	{ "NO_OBJECTIVE_MAP", UGC_PLAY_NO_OBJECTIVE_MAP},
	{ "GENESIS_GENERATION_ERROR", UGC_PLAY_GENESIS_GENERATION_ERROR},
	{ "NO_DIALOG_TREE", UGC_PLAY_NO_DIALOG_TREE},
	{ "NO_PROJECT", UGC_PLAY_NO_PROJECT},
	{ "BUDGET_ERROR", UGC_PLAY_BUDGET_ERROR},
	{ "UNKNOWN_ERROR", UGC_PLAY_UNKNOWN_ERROR},
	DEFINE_END
};
void autoEnum_fixup_UGCPlayStatus(void)
{
	static bool bOnce = false; if (bOnce) return; bOnce = true;
	RegisterNamedStaticDefine(UGCPlayStatusEnum, "UGCPlayStatus");
}

//auto-generated staticdefine for enum UGCChangeReason
//autogeneratednocheckin
StaticDefineInt UGCChangeReasonEnum[] =
{
	DEFINE_INT
	{ "AUTOWITHDRAW", UGC_CHANGE_AUTOWITHDRAW},
	{ "CSR_BAN", UGC_CHANGE_CSR_BAN},
	{ "TEMP_AUTOBAN", UGC_CHANGE_TEMP_AUTOBAN},
	{ "PERMANENT_AUTOBAN", UGC_CHANGE_PERMANENT_AUTOBAN},
	DEFINE_END
};
void autoEnum_fixup_UGCChangeReason(void)
{
	static bool bOnce = false; if (bOnce) return; bOnce = true;
	RegisterNamedStaticDefine(UGCChangeReasonEnum, "UGCChangeReason");
}

//auto-generated staticdefine for enum UGCProjectReportReason
//autogeneratednocheckin
StaticDefineInt UGCProjectReportReasonEnum[] =
{
	DEFINE_INT
	{ "MissionInappropriate", kUGCProjectReportReason_MissionInappropriate},
	DEFINE_END
};
void autoEnum_fixup_UGCProjectReportReason(void)
{
	static bool bOnce = false; if (bOnce) return; bOnce = true;
	RegisterNamedStaticDefine(UGCProjectReportReasonEnum, "UGCProjectReportReason");
}
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct UGCPlayLayerData
#define TYPE_parse_UGCPlayLayerData UGCPlayLayerData
ParseTable parse_UGCPlayLayerData[] =
{
	{ "UGCPlayLayerData", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCPlayLayerData), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "filename",			TOK_POOL_STRING | TOK_FILENAME(UGCPlayLayerData, filename, NULL), NULL},
	{ "LayerData",			TOK_LATEBINDSTRUCT(UGCPlayLayerData, eaDefs) },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCPlayLayerData()
{
	int iSize = sizeof(UGCPlayLayerData);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCPlayLayerData, iSize, "UGCPlayLayerData", NULL, "UGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
void DoAutoStructLateBind(ParseTable *pTPI, int iColumnIndex, char *pOtherTPIName);
void autoStruct_lateFixup_UGCPlayLayerData(void)
{
	DoAutoStructLateBind(parse_UGCPlayLayerData, 3, "GroupDef");
}
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct UGCPlayComponentData
#define TYPE_parse_UGCPlayComponentData UGCPlayComponentData
ParseTable parse_UGCPlayComponentData[] =
{
	{ "UGCPlayComponentData", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCPlayComponentData), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "ComponentID",			TOK_AUTOINT(UGCPlayComponentData, componentID, 0), NULL },
	{ "rot_ComponentMat4",		TOK_MAT4PYR_ROT(UGCPlayComponentData, componentMat4), NULL },
	{ "pos_ComponentMat4",		TOK_MAT4PYR_POS(UGCPlayComponentData, componentMat4), NULL },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCPlayComponentData()
{
	int iSize = sizeof(UGCPlayComponentData);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCPlayComponentData, iSize, "UGCPlayComponentData", NULL, "UGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_UGCPlayLayerData[];
#define TYPE_parse_UGCPlayLayerData UGCPlayLayerData
extern ParseTable parse_UGCPlayComponentData[];
#define TYPE_parse_UGCPlayComponentData UGCPlayComponentData
//Structparser.exe autogenerated ParseTable for struct UGCPlayResult
#define TYPE_parse_UGCPlayResult UGCPlayResult
ParseTable parse_UGCPlayResult[] =
{
	{ "UGCPlayResult", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCPlayResult), 0, NULL, 0, NULL },
	{ "{",				TOK_START, 0 },
	{ "Status",			TOK_AUTOINT(UGCPlayResult, eStatus, 0), UGCPlayStatusEnum },
	{ "ZoneMap",		TOK_OPTIONALLATEBINDSTRUCT(UGCPlayResult, pInfo) },
	{ "Filename",		TOK_POOL_STRING | TOK_STRING(UGCPlayResult, fstrFilename, 0), NULL },
	{ "LayerData",		TOK_STRUCT(UGCPlayResult, eaLayerDatas, parse_UGCPlayLayerData) },
	{ "ComponentData",	TOK_STRUCT(UGCPlayResult, eaComponentData, parse_UGCPlayComponentData) },
	{ "SkyDef",			TOK_STRINGARRAY(UGCPlayResult, eaSkyDefs), NULL },
	{ "}",				TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCPlayResult()
{
	int iSize = sizeof(UGCPlayResult);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCPlayResult, iSize, "UGCPlayResult", NULL, "UGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
void DoAutoStructLateBind(ParseTable *pTPI, int iColumnIndex, char *pOtherTPIName);
void autoStruct_lateFixup_UGCPlayResult(void)
{
	DoAutoStructLateBind(parse_UGCPlayResult, 3, "ZoneMapInfo");
}
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct UGCProjectAutosaveData
#define TYPE_parse_UGCProjectAutosaveData UGCProjectAutosaveData
ParseTable parse_UGCProjectAutosaveData[] =
{
	{ "UGCProjectAutosaveData", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCProjectAutosaveData), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "Timestamp",				TOK_AUTOINT(UGCProjectAutosaveData, iTimestamp, 0), NULL },
	{ "Data",					TOK_OPTIONALLATEBINDSTRUCT(UGCProjectAutosaveData, pData) },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCProjectAutosaveData()
{
	int iSize = sizeof(UGCProjectAutosaveData);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCProjectAutosaveData, iSize, "UGCProjectAutosaveData", NULL, "UGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
void DoAutoStructLateBind(ParseTable *pTPI, int iColumnIndex, char *pOtherTPIName);
void autoStruct_lateFixup_UGCProjectAutosaveData(void)
{
	DoAutoStructLateBind(parse_UGCProjectAutosaveData, 3, "UGCProjectData");
}
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct UGCProjectReportingDef
#define TYPE_parse_UGCProjectReportingDef UGCProjectReportingDef
ParseTable parse_UGCProjectReportingDef[] =
{
	{ "UGCProjectReportingDef", 			TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(UGCProjectReportingDef), 0, NULL, 0, NULL },
	{ "{",								TOK_START, 0 },
	{ "NaughtyThreshold",				TOK_AUTOINT(UGCProjectReportingDef, iNaughtyThreshold, 10), NULL },
	{ "NaughtyIncrement",				TOK_AUTOINT(UGCProjectReportingDef, iNaughtyIncrement, 2), NULL },
	{ "TemporaryBanTimer",				TOK_AUTOINT(UGCProjectReportingDef, uTemporaryBanTimer, 86400), NULL },
	{ "TemporaryBanCountResultsInBan",	TOK_AUTOINT(UGCProjectReportingDef, iTemporaryBanCountResultsInBan, 3), NULL },
	{ "NaughtyDecayInterval",			TOK_AUTOINT(UGCProjectReportingDef, uNaughtyDecayInterval, 21600), NULL },
	{ "NaughtyDecayValue",				TOK_AUTOINT(UGCProjectReportingDef, iNaughtyDecayValue, 1), NULL },
	{ "MaxReportsPerProject",			TOK_AUTOINT(UGCProjectReportingDef, iMaxReportsPerProject, 20), NULL },
	{ "}",								TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_UGCProjectReportingDef()
{
	int iSize = sizeof(UGCProjectReportingDef);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_UGCProjectReportingDef, iSize, "UGCProjectReportingDef", NULL, "UGCCommon.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
