#ifndef __UGCCOMMON_H_AST_H_
#define __UGCCOMMON_H_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \UGCCommon.h
//autogeneratednocheckin

//auto-generated staticdefine for enum UGCPlayStatus
//autogeneratednocheckin
extern StaticDefineInt UGCPlayStatusEnum[];

//auto-generated staticdefine for enum UGCChangeReason
//autogeneratednocheckin
extern StaticDefineInt UGCChangeReasonEnum[];

//auto-generated staticdefine for enum UGCProjectReportReason
//autogeneratednocheckin
extern StaticDefineInt UGCProjectReportReasonEnum[];

extern ParseTable parse_UGCPlayLayerData[];
#define TYPE_parse_UGCPlayLayerData UGCPlayLayerData

extern ParseTable parse_UGCPlayComponentData[];
#define TYPE_parse_UGCPlayComponentData UGCPlayComponentData

extern ParseTable parse_UGCPlayResult[];
#define TYPE_parse_UGCPlayResult UGCPlayResult

extern ParseTable parse_UGCProjectAutosaveData[];
#define TYPE_parse_UGCProjectAutosaveData UGCProjectAutosaveData

extern ParseTable parse_UGCProjectReportingDef[];
#define TYPE_parse_UGCProjectReportingDef UGCProjectReportingDef

#endif
